### ISSUE TITLE
Crash when calling "bind method"

### ISSUE THREAD

**Issue by hakuhan** [godotengine/godot-cpp#1009]
How to reproduce:

- Just click play.

Version:
Official Beta 13.

Callstack:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff204cc91e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff204fb5bd pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff20450406 abort + 125
3   libc++abi.dylib               	0x00007fff204beef2 abort_message + 241
4   libc++abi.dylib               	0x00007fff204b05e5 demangling_terminate_handler() + 242
5   libobjc.A.dylib               	0x00007fff203a9595 _objc_terminate() + 104
6   libc++abi.dylib               	0x00007fff204be307 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff204c0beb __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
8   libc++abi.dylib               	0x00007fff204c0bb2 __cxa_throw + 116
9   libc++.1.dylib                	0x00007fff2049b7bb std::__1::__throw_system_error(int, char const*) + 77
10  libc++.1.dylib                	0x00007fff204923ed std::__1::mutex::lock() + 29
11  org.godotengine.godot         	0x000000010b009976 0x1069ad000 + 73779574
12  libgdmelee.macos.template_debug	0x000000011607a51b godot::MethodBindT<godot::Object*>::ptrcall(void*, void const* const*, void*) const + 75

**Comment by hakuhan** [comment]
Crash happens in windows

**Comment by akien-mga** [comment]
Did you intend to close this? What was the solution?

**Comment by hakuhan** [comment]
Hi. I didn't solve this problem. Just report same bug at godotengine project: https://github.com/godotengine/godot/issues/71796#issuecomment-1399420372
