### ISSUE TITLE
ranlib can't find symbols for x86_64

### ISSUE THREAD

**Issue by Ghashy** [godotengine/godot-cpp#1012]
Hello!
Three days ago I had downloaded renewed Godot-cpp repository, and now it can't properly build for macOS x86_64.
It builds fine for m1 Mac, without warnings, and works perfect in Godot. But when I try to compile a universal library, it gives many warnings from ranlib, that it can not find symbols, and then Godot sees my classes but does not see my methods. I tried to compile on x86_64 machine Mac, but result is the same. I tried both cmake and scons for compiling, neither did the job.
I attach a text file with warnings.
[log.txt](https://github.com/godotengine/godot-cpp/files/10483700/log.txt)

**Comment by Calinou** [comment]
@Ghashy Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by Ghashy** [comment]
@Calinou  
Actually, I found out almost instantly after I posted this issue, that I forgot I had temporary commented  this methods - ClassDB::bind_method() in my code, I uncommented them and it worked)
Then I got another issue: AudioUnitRender failed on x86_mac (I am making an audio extension for Godot 4, by the way)
![Screenshot 2023-01-24 at 12 59 25](https://user-images.githubusercontent.com/109857267/214263639-b7f45d0d-c1c5-4bd6-a180-368361d40111.png)

But this problem sure is not in godot-cpp)
