### ISSUE TITLE
Compilation errors with Variant::call()

### ISSUE THREAD

**Issue by Trey2k** [godotengine/godot-cpp#1015]
Hello, I am currently looking at adding support to my module to compile to GDExtension. My module makes a lot of use of the Variant::call method. However it seems to not work in GDExtension. To test I added this method to [Summator](https://github.com/paddy-exe/GDExtensionSummator) template project:
```cpp
void Summator::call(Variant var)
{
    var.call("test", "Hello world!");
}
```
During compilation I get [this](https://pastebin.com/hYdTzrvc) error. 
I am very new to godot-cpp so it's entirely possible this is user error.

**Comment by mashumafi** [comment]
It looks like the compiler is trying to recursively call `call`. This would explain why it's trying to turn `GDExtensionCallError` into a `Variant`. My initial guesses would be either:

* `call_args.data()` is not resolving to `Variant**`
* `call_args.size()` returns `size_t` but the function expects `int`

**Comment by Trey2k** [comment]
> It looks like the compiler is trying to recursively call `call`. This would explain why it's trying to turn `GDExtensionCallError` into a `Variant`. My initial guesses would be either:
> 
> * `call_args.data()` is not resolving to `Variant**`
> * `call_args.size()` returns `size_t` but the function expects `int`

Makes sense, can't wait for your PR to be merged. Thank you!
