### ISSUE TITLE
Are the GDScript built-in functions available in GDNative?

### ISSUE THREAD

**Issue by danielytics** [godotengine/godot-cpp#107]
Are the GDScript built-in functions (as listed here http://docs.godotengine.org/en/3.0/classes/class_@gdscript.html) available from GDNative? Obviously many of the math functions are available in cstdlib and cmath, but not all, for example `clamp`, `lerp`, `wrapf` and it would also be useful if the same random number generator could be used globally.

**Comment by karroffel** [comment]
No, unfortunately not, they have to be hardcoded and not all of them have been implemented yet.

The only functions implemented are for printing, `Godot::print()`.

New ones should be implemented in the same class, but for now we need workarounds.

**Comment by danielytics** [comment]
If you let me know what you want for this, I'll be happy to open a PR. Its unfortunate that code can't be reused as it feels a little nasty to have the same code implemented multiple times within the engine, but I guess I'd rather have them duplicated than not available.

- I'm thinking at least `clamp`, `lerp`, `cartesian2polar`, `db2linear`, `deg2rad`, `sign`, `inverse_lerp`, `linear2db`, `load`, `nearest_po2`, `polar2cartesian`, `rad2deg`, `range`, `range_lerp`, `stepify`, `wrapf` and `wrapi`.
- `Color8` and `ColorN` are not needed as the functionality already exists in the `core/Color` class.
- The random number generation functions should probably wrap the functions in `godot/core/math/math_funcs.cpp`.

**Comment by BastiaanOlij** [comment]
@jacksondus shameless plug: https://github.com/BastiaanOlij/gdprocmesh

@danielytics if you're still up for it I think it would be nice to have some of those functions implemented. Not sure what the best place for them would be though...

**Comment by ricardoalcantara** [comment]
Hey! Can't we include the Godot files instead of re-implement it, when we build the godot-cpp? Or maybe make that interface with Godot:: like the print implementation?

**Comment by ricardoalcantara** [comment]
I achieve to use godot's source code in my gdnative sample, I added the {godot_path} and {godot_path}/platform/{x11/...} in my CPPPATH and I could use it without issue.

**Comment by Zylann** [comment]
I'd like math functions to be added like in the engine, under a `Math` namespace, for two reasons:
- They are not available, they should be
- My compiler throws warnings everywhere because of the use of C math functions taking a `double` but used with `float` (because of `real_t`), but in engine they are wrapped in such a way both `float` and `double` are available as overloads
