### ISSUE TITLE
scons doesn't recognize vsproj=yes

### ISSUE THREAD

**Issue by S-Davahan** [godotengine/godot-cpp#1071]
when trying to build, scons gives this warning:

Unknown SCons variables were passed and will be ignored:
vsproj=yes

**Comment by Calinou** [comment]
godot-cpp does not support generating a Visual Studio solution. Only Godot's core repository does.

**Comment by S-Davahan** [comment]
Ah, I see what's happened. I got mixed up in following the build instructions somehow and was using the wrong thing.

**Comment by staticgerbil** [comment]
While searching for information about using Visual Studio with gdextensions I came across this thread and thought I might say that while I agree that cross-platform build systems do make more sense in general, I personally would like Visual Studio solution / build support as an option for debugging.
Perhaps there are alternatives I am not aware of (or are using incorrectly) but I really really like Visual Studio's edit and continue functionality and I have had very little success with tools outside of the Visual Studio ecosystem in that area.
