### ISSUE TITLE
'godot::GDExample::_process': method with override specifier 'override' did not override any base class methods

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot-cpp#1073]
I'm looking at this tutorial: https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html

and it has a line:
` void _process(float delta) override;`
which gives an error:
`'godot::GDExample::_process': method with override specifier 'override' did not override any base class methods`

Why this happening?

**Comment by moonxorsun** [comment]
Try `virtual void _process(float delta) override;`?

**Comment by akien-mga** [comment]
The documentation is wrong, the `delta` argument is a `double`:
```
gen/include/godot_cpp/classes/node.hpp
232:    virtual void _process(double delta);
```
