### ISSUE TITLE
When exporting to window10 in Debug mode, the. dll file does not work properly, but the Release mode does.

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot-cpp#1076]

**Comment by Atem1995** [comment]
I retested it. When I used Chinese strings in gdExtension code, the text display of Label in godot was garbled, and the export in debug mode would not work properly. This is strange. I closed it in order not to increase the burden on the staff.

**Comment by Calinou** [comment]
@Atem1995 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Atem1995** [comment]
I'm sorry for the misunderstanding. I think it's because I changed the ModuleInitializationLevel. The problem is solved now.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "godotengine/godot-cpp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [godotengine/godot-cpp] When exporting to window10 in Debug mode, the. dll file does not work properly, but the Release mode does. (Issue #1076)





 
@Atem1995 Please upload a minimal reproduction project to make this easier to troubleshoot.
