### ISSUE TITLE
Inheriting from AudioStream doesn't allow override of _instantiate_playback

### ISSUE THREAD

**Issue by lucasrafael98** [godotengine/godot-cpp#1088]
I'm trying to make a custom AudioStream in GDExtension (code at the bottom). This attempt compiles, and I can add the custom stream to an audio player. When I try to set the player to "playing", however, it hits this error in Godot: 

https://github.com/godotengine/godot/blob/4762303f182e65c5293db8d22a4ce88521eba445/servers/audio/audio_stream.cpp#L187

Seems like GDVIRTUAL_CALL can't find the override of _instantiate_playback, but I don't know enough macro magic to know.

Code: 

```cpp
// .hpp
class CustomAudioStream : public AudioStream {
	GDCLASS(CustomAudioStream, AudioStream)
	friend class CustomAudioStreamPlayback;

protected:
	static void _bind_methods();

public:
	CustomAudioStream();
	~CustomAudioStream();

	virtual Ref<AudioStreamPlayback> _instantiate_playback() const override;
};

// .cpp 
CustomAudioStream::CustomAudioStream() {}
CustomAudioStream::~CustomAudioStream() {}

// no, trying to bind _instantiate_playback below doesn't make a difference
void CustomAudioStream::_bind_methods() {} 

Ref<AudioStreamPlayback> CustomAudioStream::_instantiate_playback() const {
	Ref<CustomAudioStreamPlayback> playback;
	playback.instantiate();

	return playback;
}


```

**Comment by dsnopek** [comment]
I think there may be a missing `GDVIRTUAL_BIND(_instantiate_playback())` here:

https://github.com/godotengine/godot/blob/4762303f182e65c5293db8d22a4ce88521eba445/servers/audio/audio_stream.cpp#L83

That would make this a Godot engine issue, and not a godot-cpp one

**Comment by dsnopek** [comment]
Er, nevermind, I was looking at the wrong class. The `GDVIRTUAL_BIND` is there:

https://github.com/godotengine/godot/blob/4762303f182e65c5293db8d22a4ce88521eba445/servers/audio/audio_stream.cpp#L252

**Comment by oparisy** [comment]
Hi! "It works for me" using the following signature in my `AudioStream` subclass:
```
Ref<AudioStreamPlayback> _instantiate_playback() const override;
```

So, maybe, try removing the `virtual` in yours? I've read it does not make much sense to repeat it in subclasses anyway; `override` is enough to get some help from the compiler in case of error.

It it works, it does not mean there is not something to improve in Godot macros; but I'm not versed enough in those to be the judge of that.

**Comment by lucasrafael98** [comment]
Hm... thanks for the suggestion, but even after upgrading Godot + my project + godot-cpp to 4.1, I still get the same error when removing virtual. Do you happen to have anything else in your subclass that might "make it work"?

**Comment by oparisy** [comment]
I was considering sharing my code example once cleaned up; you just motivated me to do so 😀

In the meantime I'd suggest having a look at the reproduction project I shared on https://github.com/godotengine/godot-cpp/issues/1207. Note that you'll have to apply the workaround I describe on the ticket (one line to uncomment).

See if it compiles and works properly in your environment. If so, you'll have a working example to compare with your code.

**Comment by lucasrafael98** [comment]
Thanks for the example :) it does compile and work perfectly, but even if I go so far as to copy your example's source files and SConstruct over to my project, the error continues to happen (and this is on two different computers). This is either a very esoteric bug or some sneaky lapse on my part (erring towards the latter).

**Comment by lucasrafael98** [comment]
Well, a note for anyone reading this issue: don't be clever and symlink `res://bin/` to another folder and actually place your .gdextension and required libs where they should be :laughing:   
The problem seems to be that I was symlinking `bin` to another folder to try and keep things organized, but that breaks something somewhere. I'm not sure if "the Godot user being overly picky about folder structure" is an issue that should actually be treated (perhaps the engine could throw an error if it notices `res://bin/` is a symlink?), so I'll close this. Thanks for the help!

**Comment by oparisy** [comment]
Happy to read that you found the cause of your problem! I had a look at the existing issues and did not find anything seemingly related. For reference, what is your environment/distro?

**Comment by lucasrafael98** [comment]
Fedora 38. It might, of course, have been, something else, but the symlink does seem to be the breaking factor.
