### ISSUE TITLE
Expose callable_mp macros in godot-cpp?

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot-cpp#1089]
Engine has a macros `callable_mp` which uses class **CallableCustomMethodPointerRetC** that allow to assign native method. But I cant find analogue in GDExtension.

Godot 4.0

**Comment by dsnopek** [comment]
This is added by this pair of PRs:

- https://github.com/godotengine/godot/pull/78813
- https://github.com/godotengine/godot-cpp/pull/1155
