### ISSUE TITLE
Binding generator isn't generating implementations for templated functions

### ISSUE THREAD

**Issue by ghsoares** [godotengine/godot-cpp#1093]
References https://github.com/godotengine/godot/issues/76213

I'm having a issue with `Callable::bind`, which is throwing LNK2019 when trying to call with any arbitrary arguments, let's take `uint64_t` as only argument for example, when compiling the extension, it throws the following error: `error LNK2019: unresolved external symbol, "public: class godot::Callable __cdecl godot::Callable::bind<unsigned __int64>(unsigned __int64 const &)const "`.

When inspecting `godot-cpp\gen\src\variant\callable.cpp`, it's missing the implementation for `Callable::bind`, so I guess that's why it throws the linker error. It is missing other templated member functions as well, for example `Callable::call` and `Signal::emit`.

Edit: It seens that the majority of the templated functions is already implemented in the .hpp files, only some specific cases where it isn't implemented in the .hpp neither in the .cpp

**Comment by fuzzybinary** [comment]
I've also run into this. It appears GDExtension doesn't currenlty have a way to call vararg methods on variants?

**Comment by dsnopek** [comment]
There's a work-in-progress PR to fix this: https://github.com/godotengine/godot-cpp/pull/1091
