### ISSUE TITLE
Crash when using Ref<InputEvent>

### ISSUE THREAD

**Issue by redsett** [godotengine/godot-cpp#1100]
Platform = Windows
Godot version = 4.0.2-stable
godot-cpp version = [feaba55](https://github.com/godotengine/godot-cpp/tree/feaba551b5a5b2d13ad1c3fdd8c90e67c67ff37c)

Issue:
I'm trying to override `_unhandled_input`, but it crashes when trying to resolve the Ref<>.
`void _unhandled_input(const Ref<InputEvent> &p_event) override { }`

![image](https://user-images.githubusercontent.com/17795893/235003580-44551bf6-53ae-4455-93fb-185ad7be18ae.png)

Reverting this commit fixes it. But I'm sure that something else breaks. :)
https://github.com/godotengine/godot-cpp/commit/feaba551b5a5b2d13ad1c3fdd8c90e67c67ff37c

@zhehangd @akien-mga

**Comment by dsnopek** [comment]
Related to PR #1045

**Comment by WiggleWizard** [comment]
For those who need a work around right now and are looking to capture `_gui_input()`...I found it feasible to simply make your own method in your custom Node that takes a `Ref<InputEvent>` then override `_gui_input` in GDScript and call your method. Could likely be applied to the other method overrides that require a `Ref<>&` that are crashing.
