### ISSUE TITLE
imported shared memory but unshared required

### ISSUE THREAD

**Issue by mathiasplans** [godotengine/godot-cpp#1103]
I get an error when trying the "GDExtension C++ example" from docs on HTML5 platform. The example works as expected on Windows platform.

The console output on Firefox:
```
imported shared memory but unshared required
    displayFailureNotice http://localhost:8000/web0/web0.html:212
    (Async: promise callback)
    <anonymous> http://localhost:8000/web0/web0.html:239
    <anonymous> http://localhost:8000/web0/web0.html:244
```
On Chrome:
```
WebAssembly.instantiate(): mismatch in shared state of memory, declared = 0, imported = 1
    displayFailureNotice http://localhost:8000/web0/web0.html:212
    (Async: promise callback)
    <anonymous> http://localhost:8000/web0/web0.html:239
    <anonymous> http://localhost:8000/web0/web0.html:244
````
Important to note that I changed the tools/javascript.py because of the problem in the issue #1081. I'm using emscripten (3.1.5~dfsg-3ubuntu1) on WSL.

**Comment by Calinou** [comment]
To my knowledge, GDExtension isn't supported on HTML5 yet.

**Comment by paddy-exe** [comment]
@Calinou is right. GDExtensions for Web don't work since there is still a dependancy issue with Emscripten for web export. 

Related: https://github.com/godotengine/godot-cpp/issues/554

**Comment by mathiasplans** [comment]
I tried a newer version (3.1.37) as well as the version that the engine's CI uses (2.0.27). Both still have the same problem. I guess there are no easy work-arounds.

**Comment by Esption** [comment]
@mathiasplans Not that I think support is working, but this is a different issue. How did you compile the example exactly? You'll need to pass `-sSIDE_MODULE=2 -sSHARED_MEMORY=1` (and possibly pthread, atomics, mutable-globals flags) to emscripten.  That error is basically just complaining that not every module has the same state for shared_memory, and the godot side of things is compiled with it on, so you need to compile your gdextension with it on too.
