### ISSUE TITLE
is it possible to call native rpc function?

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot-cpp#1111]
Is there some mechanism to call rpc native functions? 
Similar to `gdscripts` `some_rpc_func.rpc(val)` but in c++ and without declaration script version of the function?

**Comment by Calinou** [comment]
Which Godot version are you using?

**Comment by RonYanDaik** [comment]
> Which Godot version are you using?

4.0.3

**Comment by RonYanDaik** [comment]
Maybe we could receive something like __network_notification_ event/function with some data?

**Comment by Faless** [comment]
Yes, it is possible using the godot regualr node API ([`Node.rpc_config`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-rpc-config), and [`Node.rpc`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-rpc)/[`Node.rpc_id`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-rpc-id)).
I've added a test for it in #1157 .

**Comment by Faless** [comment]
Yes, exactly like a script would do (or an engine class would do).
That's how Godot knows the function exists and how to call it.

**Comment by Faless** [comment]
Closing as we now have a test/example #1157 .
