### ISSUE TITLE
What is legacy Godot 4.0 mode and how to disable it?

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot-cpp#1122]
I've just switched to master branch both for godot and for gdextension and got this:
`"Cannot load a GDExtension built for Godot 4.1+ in legacy Godot 4.0 mode"`
But cant find information how to switch to non legacy mode.

**Comment by RonYanDaik** [comment]
oh. you have to add to *.gdextension:

 compatibility_minimum = 4.1

**Comment by Calinou** [comment]
Reopening, as this should be documented.

**Comment by dsnopek** [comment]
After Godot PR https://github.com/godotengine/godot/pull/77963 there is no longer a "legacy Godot 4.0" mode, so the error message here could probably also be simplified to just:

```
Cannot load a GDExtension built for Godot 4.1+ in Godot 4.0
```

If you try to load a GDExtension in Godot 4.1 and it's missing "compatibility_minimum", it'll now give the error:

```
GDExtension configuration file must contain a "configuration/compatibility_minimum" key
```

So, assuming we update the first error message, there shouldn't be any confusion about what the developer is supposed to do anymore.

**Comment by dsnopek** [comment]
I just posted PR https://github.com/godotengine/godot-cpp/pull/1137, which update the error message as described above
