### ISSUE TITLE
Cannot change 'primitive_type' member when inheriting 'PrimitiveMesh'

### ISSUE THREAD

**Issue by poirierlouis** [godotengine/godot-cpp#1124]
Hello :)

I'm trying to implement a custom `PrimitiveMesh`.
I can inherit the class, register, compile and run it in Godot without errors. However I did not find a way to change the `primitive_type` member of `PrimitiveMesh`. It exists as a protected member in [godot](https://github.com/godotengine/godot/blob/5222a99f5d38cd5346254cefed8f65315bca4fcb/scene/resources/primitive_meshes.h#L68). But it is not made available in [godot-cpp](https://github.com/godotengine/godot-cpp/tree/godot-4.0.3-stable).

As stated in code, it will default to `PrimitiveType::PRIMITIVE_TRIANGLES`. While I do return an array with vertices, triangles are drawn but I need to draw with `PrimitiveType::PRIMITIVE_LINES` instead. Is there a way to update/change `primitive_type` that I'm not aware of?

Here is the generated code for `primitive_mesh.hpp` in my environment:
> Version: 4.0.3-stable
> OS: Windows

```cpp
class PrimitiveMesh : public Mesh {
	GDEXTENSION_CLASS(PrimitiveMesh, Mesh)

public:

	void set_material(const Ref<Material> &material);
	Ref<Material> get_material() const;
	Array get_mesh_arrays() const;
	void set_custom_aabb(const AABB &aabb);
	AABB get_custom_aabb() const;
	void set_flip_faces(bool flip_faces);
	bool get_flip_faces() const;
	void set_add_uv2(bool add_uv2);
	bool get_add_uv2() const;
	void set_uv2_padding(double uv2_padding);
	double get_uv2_padding() const;
	virtual Array _create_mesh_array() const;
protected:
	template <class T, class B>
	static void register_virtuals() {
		Mesh::register_virtuals<T, B>();
		if constexpr (!std::is_same_v<decltype(&B::_create_mesh_array),decltype(&T::_create_mesh_array)>) {
			BIND_VIRTUAL_METHOD(T, _create_mesh_array);
		}
	}

public:

};
```

I tried a "hacky" way. Looking at the parent class `Mesh`, I found the function:
```cpp
virtual uint32_t Mesh::_surface_get_primitive_type(int32_t index) const
```
I tried by overriding the function and returning `PrimitiveType::PRIMITIVE_LINES`. It did not change the result, as I suspect it is not used internally.

Any help would be appreciated. Also, I'm willing to help in any way I could if need be.

**Comment by poirierlouis** [comment]
After trying to inherit `PrimitiveMesh` in GDScript. I ran into the same situation where `primitive_type` cannot be accessed nor changed. Should I duplicate this issue in godot repository and reference this issue to keep track of it?

**Comment by Calinou** [comment]
> After trying to inherit `PrimitiveMesh` in GDScript. I ran into the same situation where `primitive_type` cannot be accessed nor changed. Should I duplicate this issue in godot repository and reference this issue to keep track of it?

Yes, please open an issue on the main Godot repository as this is not a GDExtension-specific issue.

Note that in general, support for extending abstract types from scripting wasn't extensively tested – it's a new feature in 4.0.

**Comment by poirierlouis** [comment]
Issue on main Godot repository [#77447](https://github.com/godotengine/godot/issues/77447).
