### ISSUE TITLE
_err_print_error exception (gdextension_interface_print_error is 0x0000000)

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot-cpp#1125]
### Godot version

https://github.com/godotengine/godot/pull/77578

### godot-cpp version

https://github.com/godotengine/godot-cpp/pull/1113

### System information

Win10 x64

### Issue description

![image](https://github.com/godotengine/godot-cpp/assets/3350340/62128e96-4f05-4764-8c8f-f5ea58594c9e)

>	librim.windows.template_debug.dev.x86_64.dll!godot::_err_print_error(const char * p_function, const char * p_file, int p_line, const char * p_error, bool p_editor_notify, bool p_is_warning) Line 46	C++
 	librim.windows.template_debug.dev.x86_64.dll!godot::Curve3D::sample_baked(double offset, bool cubic) Line 238	C++
 	librim.windows.template_debug.dev.x86_64.dll!ImpPath3D::sample_with_time(double time) Line 80	C++

![image](https://github.com/godotengine/godot-cpp/assets/3350340/cf735fa7-1884-41e1-aa9e-3b9af4dadd1b)

### Steps to reproduce

try to call Curve3D::sample_baked

### Minimal reproduction project

n/a

**Comment by dsnopek** [comment]
Thanks!

I've made a PR would should fix this issue: https://github.com/godotengine/godot-cpp/pull/1129
