### ISSUE TITLE
ProjectSettings::get_setting() returns 0

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot-cpp#1158]
### Godot version

4.1 rc2 https://github.com/godotengine/godot/commit/46424488edc341b65467ee7fd3ac423e4d49ad34

### godot-cpp version

4.1 rc2 https://github.com/godotengine/godot-cpp/commit/80986f8497b7bec307e0987d01412360d39cbb3f

### System information

Win 10 x64

### Issue description

ProjectSettings::get_singleton()->get_setting() returns 0.
at least for default_gravity and default_gravity_vector.

### Steps to reproduce

Vector3 gravity = ProjectSettings::get_singleton()->get_setting("physics/3d/default_gravity_vector");
float gravity_vec = ProjectSettings::get_singleton()->get_setting("physics/3d/default_gravity");

### Minimal reproduction project

N/A

**Comment by dsnopek** [comment]
I'm not able to reproduce this with Godot 4.1.

As a quick test, I added this code to `test/src/example.cpp`:

```cpp
void Example::_notification(int p_what) {
	if (p_what == NOTIFICATION_READY) {
		float gravity = ProjectSettings::get_singleton()->get_setting("physics/3d/default_gravity");
		printf("Gravity: %f\n", gravity);
	}
}
```

... and ran the automated tests, which produced this output:

```
Gravity: 9.800000
```

**Comment by RonYanDaik** [comment]
It dissapeared. Maybe engine update fixed, maybe was on my side.
