### ISSUE TITLE
No "ADD_PROPERTYI" macro available in GDExtension

### ISSUE THREAD

**Issue by ozzr** [godotengine/godot-cpp#1161]
### Godot version

Since 4.0 released including beta an rc stages

### godot-cpp version

any version of GDExtension 

### System information

Windows 10 i7-6800K

### Issue description

Modules have a wide variety of useful macros for exposing properties from a class
```c++
#define ADD_PROPERTY(m_property, m_setter, m_getter) ::ClassDB::add_property(get_class_static(), m_property, _scs_create(m_setter), _scs_create(m_getter))
#define ADD_PROPERTYI(m_property, m_setter, m_getter, m_index) ::ClassDB::add_property(get_class_static(), m_property, _scs_create(m_setter), _scs_create(m_getter), m_index)
#define ADD_PROPERTY_DEFAULT(m_property, m_default) ::ClassDB::set_property_default_value(get_class_static(), m_property, m_default)
#define ADD_GROUP(m_name, m_prefix) ::ClassDB::add_property_group(get_class_static(), m_name, m_prefix)
#define ADD_GROUP_INDENT(m_name, m_prefix, m_depth) ::ClassDB::add_property_group(get_class_static(), m_name, m_prefix, m_depth)
#define ADD_SUBGROUP(m_name, m_prefix) ::ClassDB::add_property_subgroup(get_class_static(), m_name, m_prefix)
#define ADD_SUBGROUP_INDENT(m_name, m_prefix, m_depth) ::ClassDB::add_property_subgroup(get_class_static(), m_name, m_prefix, m_depth)
#define ADD_LINKED_PROPERTY(m_property, m_linked_property) ::ClassDB::add_linked_property(get_class_static(), m_property, m_linked_property)
```

But in GDExtension there are only a few of them to be used
```c++
#define ADD_SIGNAL(m_signal) godot::ClassDB::add_signal(get_class_static(), m_signal)
#define ADD_GROUP(m_name, m_prefix) godot::ClassDB::add_property_group(get_class_static(), m_name, m_prefix)
#define ADD_SUBGROUP(m_name, m_prefix) godot::ClassDB::add_property_subgroup(get_class_static(), m_name, m_prefix)
#define ADD_PROPERTY(m_property, m_setter, m_getter) godot::ClassDB::add_property(get_class_static(), m_property, m_setter, m_getter)
```

Defining those missing macros by our selves do not work and the property is not exposed
```c++
#define ADD_PROPERTYI(m_property, m_setter, m_getter, m_index) godot::ClassDB::add_property(get_class_static(), m_property, m_setter, m_getter, m_index)
```

Those missing macros are very useful for migrating modules into GDExtension

Visual examples:
Inside the Code Editor
![macro_editor](https://github.com/godotengine/godot-cpp/assets/36895302/2732f303-c4d5-4e49-9166-bf0d75e74082)

Inside Godot Editor `(expected result is 5 properties exposed not only 1)`
![macro_godot](https://github.com/godotengine/godot-cpp/assets/36895302/a20da333-fc2b-4573-b7ce-1c8619404b4c)

### Steps to reproduce

1. Create a gdextension project
2. extract the test_macro files into the src folder.
3. build

OR in an existing project

Define the next macro somewhere in your project and include it in your class
```c++
#define ADD_PROPERTYI(m_property, m_setter, m_getter, m_index) godot::ClassDB::add_property(get_class_static(), m_property, m_setter, m_getter, m_index)
```

in the _**_bind_methods**_ expose any property as you would in a module

### Minimal reproduction project

[macro_test.zip](https://github.com/godotengine/godot-cpp/files/11924461/macro_test.zip)

**Comment by paddy-exe** [comment]
@ozzr I am confused by your Godot and Godot-cpp version. Are you using two incompatible versions with each other? Could you please share your exact commits as well?

Also in the documentation there's an example of `ADD_PROPERTY` and I tested both on Mac ans Windows. 

https://docs.godotengine.org/en/4.0/tutorials/scripting/gdextension/gdextension_cpp_example.html

**Comment by ozzr** [comment]
Hi, this issue exists in all versions of GDExtension and with every possible combination of the Engine. It is not an unique issue to any of the new godot-cpp versions. I have been testing it since godot 4.0 stable released

Look that I refer to ADD_PROPEERYI with a trailing 'I' which is used inside modules to expose properties like the ones in the reproduction project and not the ADD_PROPERTY which is one of the existing macros

**Comment by ozzr** [comment]
ClassDB::add_property has already a slot for providing an index. It just don't seems to work

**Comment by Remi123** [comment]
Here is my favorite macros for property and binding

``` C++
#define GETSET(type,variable,...) type variable{__VA_ARGS__}; type get_##variable(){return  variable;} void set_##variable(type value){variable = value;}
#define STR(x) #x
#define STRING_PREFIX(prefix,s) STR(prefix##s) 
#define BINDER(type,variable,...)         \
        ClassDB::bind_method( D_METHOD(STRING_PREFIX(set_,variable),"value"), &type::set_##variable,__VA_ARGS__);\
        ClassDB::bind_method( D_METHOD(STRING_PREFIX(get_,variable)), &type::get_##variable);
#define BINDER_PROPERTY(type,variant_type,variable,...)         \
        BINDER(type,variable,__VA_ARGS__)\
        ADD_PROPERTY(PropertyInfo(variant_type,#variable),STRING_PREFIX(set_,variable),STRING_PREFIX(get_,variable));
#define BINDER_PROPERTY_PARAMS(type,variant_type,variable,...)         \
        BINDER(type,variable)\
        ADD_PROPERTY(PropertyInfo(variant_type,#variable,__VA_ARGS__),STRING_PREFIX(set_,variable),STRING_PREFIX(get_,variable));
```

So I can write a bunch of things like this : 

```C++
GETSET(int,important_variable);

protected:
static void _bind_methods() {
    BINDER_PROPERTY_PARAMS(MyClass, Variant::INT,important_variable, PROPERTY_HINT_ENUM, "A,B,C");
}
```

Don't ask how I wrote those macros. I don't want to remember all the rules of the preprocessor.

**Comment by ozzr** [comment]
@Remi123  Looks like I am replacing my custom macros by yours, starting today ;)

**Comment by ozzr** [comment]
@paddy-exe is there any documentation on how is that GDExtension works? or anyone who could guide me somehow so I can track the cause of this issue?

**Comment by paddy-exe** [comment]
> @paddy-exe is there any documentation on how is that GDExtension works? or anyone who could guide me somehow so I can track the cause of this issue?

Unfortunately I don't have the time to work on more documentation for GDExtension currently. However you can join the `#gdextension` channel on RocketChat and ask there.

**Comment by ozzr** [comment]
@paddy-exe thanks, I will do that
