### ISSUE TITLE
Build error due to country issue ( include resolution )

### ISSUE THREAD

**Issue by Rliop913** [godotengine/godot-cpp#1177]
### Godot version

4.1 stable

### godot-cpp version

4.1 stable

### System information

windows 10 

### Issue description

Error in 
file_path : gen/include/godot_cpp/classes/rich_text_label.hpp
line 98, 
error function name: push_list
why: the bullet "*"
solve: changed "*" into "\u2022"

result : build success
--EDITED--
ADDITIONAL ERROR
file path: gen/include/godot_cpp/classes/rich_text_label.hpp
added info: #include<locale.h>

file path: gen/src/classes/rich_text_label.cpp
added info:
line 208: setlocale(LC_ALL, "english");

why: compile error

result: successful running in godot 4.1
### Steps to reproduce

build in korea

### Minimal reproduction project

just build in korea

**Comment by dsnopek** [comment]
Are you building with MSVC?

If so, PR https://github.com/godotengine/godot-cpp/pull/1175 may fix your issue

**Comment by Rliop913** [comment]
> Are you building with MSVC?
> 
> If so, PR https://github.com/godotengine/godot-cpp/pull/1175 may fix your issue

i'm using scons and cmake

**Comment by dsnopek** [comment]
Ok, but is the compiler MSVC? Or, something else like g++ or clang?

**Comment by Rliop913** [comment]
> Ok, but is the compiler MSVC? Or, something else like g++ or clang?

i'm using scons for compile.
 separately, i'm trying #1175 now

**Comment by Rliop913** [comment]
> Ok, but is the compiler MSVC? Or, something else like g++ or clang?


you're right.
PR 1174 was issue was my issue
thanks.
