### ISSUE TITLE
Unable to bind indexed properties

### ISSUE THREAD

**Issue by mihe** [godotengine/godot-cpp#1182]
### Godot version

4.2-dev (f880892c3)

### godot-cpp version

4.2-dev (749b0b9ae)

### System information

Windows 11 (10.0.22621)

### Issue description

In Godot itself you have the ability to bind a property with what's called an "index", which essentially just binds an integer (usually an enum value) to the property that will always be passed in as the first argument to its getter and setter functions. You typically do this using the `ADD_PROPERTYI` macro, as seen [here](https://github.com/godotengine/godot/blob/f880892c3db07e7702241ca2ddd0c8db2d644473/scene/3d/physics_body_3d.cpp#L48-L53).

In godot-cpp there is an index parameter for `ClassDB::add_property`, but it seems that it's currently being discarded completely, along with the rest of the (seemingly unused) `PropertySetGet` struct, as seen [here](https://github.com/godotengine/godot-cpp/blob/749b0b9ae03ecac470027b17c6414e7a0e730923/src/core/class_db.cpp#L108-L116). As far as I can tell this has been the case for as long as GDExtension has been a thing.

Since the index is being discarded currently, it gets the default value of `-1` and leads to the binding of the property emitting errors saying `ERROR: Invalid function for setter 'MyNode::my_setter for property 'my_property'.`

The only workaround is to not use indexed properties, and instead create and bind a bespoke setter/getter method for each property.

### Steps to reproduce

Add (and register) the following class in an extension of your choosing:

```cpp
class MyNode : public Node {
    GDCLASS(MyNode, Node)

    void my_setter(int32_t p_index, real_t p_value) { }
    real_t my_getter(int32_t p_index) const { return 21.0f; }

    static void _bind_methods() {
        ClassDB::bind_method(D_METHOD("my_setter", "index", "value"), &MyNode::my_setter);
        ClassDB::bind_method(D_METHOD("my_getter", "index"), &MyNode::my_getter);
        ClassDB::add_property(get_class_static(), PropertyInfo(Variant::FLOAT, "my_property"), "my_setter", "my_getter", 42);
    }
};
```

... and then run Godot from within a terminal/console, since the error message is only emitted into stderr when starting the editor, which should look something like this:

```
ERROR: Invalid function for setter 'MyNode::my_setter for property 'my_property'.
   at: (core\object\class_db.cpp:980)
```

### Minimal reproduction project

N/A

**Comment by dsnopek** [comment]
> The fix here is to either change `classdb_register_extension_class_property` to also take an index as its last argument, which I presume would be a breaking change, or to introduce a new function called something like `classdb_register_extension_class_property_indexed` that is identical to the original with the exception of also having an index argument.

Yep, for compatibility it will have to be a new function. If it would make the implementation simpler, you can have the old function call the new function.

**Comment by mihe** [comment]
Alright, sounds good. I'll throw together some pull requests within the next day or two.
