### ISSUE TITLE
Editor debugging (GDScript) and Output are broken when using GDExtension?

### ISSUE THREAD

**Issue by sfreed141** [godotengine/godot-cpp#1185]
### Godot version

4.1.stable

### godot-cpp version

4.1

### System information

Windows 11

### Issue description

I noticed that my breakpoints are never hit and I get no Output (from print statements) when following the [GDExtension tutorial](https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html) and was able to repro it in the test project in this repo too.

### Steps to reproduce

1. `git clone --recurse-submodules -b 4.1 https://github.com/godotengine/godot-cpp`
2. `cd godot-cpp/test`
3. `scons platform=windows`
4. Open Godot v4.1.stable and import `test/project`
5. Add a breakpoint and print statement at beginning of `main.gd::_ready()`
6. Run Project (F5)

### Minimal reproduction project

N/A (repro project is this repo)

**Comment by Calinou** [comment]
The engine debugger only supports breakpoints in GDScript, not GDExtension or C++ code.

**Comment by sfreed141** [comment]
@Calinou Thanks for the quick reply. To clarify, the breakpoints are made in the script editor for GDScript.

**Comment by sfreed141** [comment]
Huh, so I sanity checked with a brand new project with no GDExtension and also wasn't hitting breakpoints. I restarted my computer and now they all work again. Sorry for the trouble!
