### ISSUE TITLE
Reload Godot Crash when using `UtilityFunctions::print("something")` in class destructor

### ISSUE THREAD

**Issue by mohsenph69** [godotengine/godot-cpp#1194]
### Godot version

4.1

### godot-cpp version

4.1

### System information

Linux manjaro

### Issue description

I spend hours to find why my Terrain plugin crash when reloading the scene
And Finally I found that

Every time you output something to console with `UtilityFunctions::print` in class destructor, when you reload the scene it will crash
It will work in other situation, Only crash when Reloading the current project

### Steps to reproduce

Create a GDExtension lib, and create a class which inherit from **Node3D**

In the destructor of your class out put something with `UtilityFunctions::print`

Go to project / reload current project

Project will not reload and it will crash

But off-course you can Run that again and it will work

### Minimal reproduction project

 "N/A"

**Comment by Zylann** [comment]
See also https://github.com/godotengine/godot/issues/79506

**Comment by mohsenph69** [comment]
Yeah you are right it could be from Godot itself

**Comment by dsnopek** [comment]
Yeah, `UtilityFunctions::print()` in godot-cpp just forwards to Godot's `VariantUtilityFunctions::print()` function. I don't think this is a godot-cpp bug.

**Comment by akien-mga** [comment]
Probably fixed by https://github.com/godotengine/godot/pull/80161.
