### ISSUE TITLE
Missing implementation of `Transform3D::operator*(Vector3D)`

### ISSUE THREAD

**Issue by akriegman** [godotengine/godot-cpp#1222]
### Godot version

4.1

### godot-cpp version

4.1

### System information

Linux

### Issue description

`godot-cpp` seems to have implementations for `Transform3D::operator*(Transform3D)` and `Transform3D::operator*(float)`,  but not for `Transform3D::operator*(Vector3D)`. GDscript has all three of these. I assume this is just an oversight?

### Steps to reproduce

```
Transform3D t;
Vector3 v;
t * v;
```

### Minimal reproduction project

N/A

**Comment by akriegman** [comment]
Nevermind, I saw that there's a function `Transform3D::xform(Vector3)`. I guess the code is the documentation for this?

**Comment by AThousandShips** [comment]
These are not present in the main engine either, you are indeed supposed to use `xform`

**Comment by dsnopek** [comment]
Thanks!

One of godot-cpp's design goals is to mimick the in-engine API that Godot modules use, so that the same code (with some `#ifdef`s) can be used both in-engine or in a GDExtension. So, if we don't have these operators in the engine, then we shouldn't add them in godot-cpp.
