### ISSUE TITLE
Android: Non-existent interface function: `callable_custom_create`

### ISSUE THREAD

**Issue by MarioLiebisch** [godotengine/godot-cpp#1252]
### Godot version

v4.2.dev.custom_build [c12d63556]

### godot-cpp version

master [c44c3d5]

### System information

Windows 11, Pixel 7 Pro

### Issue description

Using the latest master builds perfectly fine for both Windows as well as Android.

The windows build works correctly in both editor and exported version.

However, using the current master branch with Android (master branch, too), loading the GDExtension library will always fail:

```logcat
09-24 15:03:04.558  1887  1964 D BatteryInfoBroadcast: onReceive: android.intent.action.BATTERY_CHANGED isPowerSaveMode: false remainingTimeMillis: 142328425
09-24 15:03:04.561   398   398 I servicemanager: Found vendor.google.google_battery.IGoogleBattery/default in device VINTF manifest.
09-24 15:03:04.562  9813  9813 E godot   : USER ERROR: Attempt to get non-existent interface function: callable_custom_create
09-24 15:03:04.562  9813  9813 E godot   :    at: get_interface_function (core\extension\gdextension.cpp:451)
09-24 15:03:04.562  9813  9813 E godot   : USER ERROR: Unable to load GDExtension interface function callable_custom_create()
09-24 15:03:04.562  9813  9813 E godot   :    at: init (.../godot-cpp/src/godot.cpp:390)
09-24 15:03:04.562  9813  9813 E godot   : USER ERROR: GDExtension initialization function 'entrypoint' returned an error.
09-24 15:03:04.562  9813  9813 E godot   :    at: open_library (core\extension\gdextension.cpp:479)
09-24 15:03:04.563  9813  9813 E godot   : USER ERROR: Failed loading resource: res://addons/.../custom.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
09-24 15:03:04.563  9813  9813 E godot   :    at: _load (core\io\resource_loader.cpp:274)
09-24 15:03:04.563  9813  9813 E godot   : USER ERROR: Error loading extension: res://addons/.../custom.gdextension
09-24 15:03:04.563  9813  9813 E godot   :    at: load_extensions (core\extension\gdextension_manager.cpp:143)
09-24 15:03:04.567  9813  9813 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10339; state: ENABLED
09-24 15:03:04.588   881   881 D usf_sensor_hal: accelerometer: Enter Batch. period = 20000000, latency = 0.
```

Switching to the 4.1 branch (currently at [4eed2d7](https://github.com/godotengine/godot-cpp/commit/4eed2d7be017ef06521665604990114c9fff7c77)) fixes the issue, so I don't think it is project specific, but let me know in case I should try to create a repro project.

The GDExtension library is built with CMake, but no custom flags/settings. The entry point itself is trivial (only registering init/terminator).

### Steps to reproduce

Build a native library and try running it (deploying from editor should be enough, there won't be any error printed in the editor, it only appears in logcat).

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
have you tried regenerating the api dump?

**Comment by MarioLiebisch** [comment]
> have you tried regenerating the api dump?
Forgot to mention it. That's been my very first idea (after rebuilding everything from scratch), but that didn't make a difference. The API stuff itself should be okay, otherwise the Windows build should fail the same way, shouldn't it?

**Comment by dsnopek** [comment]
I haven't tracked down where the specific commit hashes you listed are in the history, but I'm guess that you're using a version of Godot that's from before `callable_custom_create()` was added, but a version of godot-cpp from after it was added. Updating your version of Godot to the latest `master` would probably fix this.

**Comment by MarioLiebisch** [comment]
Commit [c12d63556](https://github.com/godotengine/godot/commit/c12d63556b5c1da03a00dd4c45c40e60bd8d68c2) was the latest commit on `master` up until about 7 hours ago (i.e. when I created this issue).

**Comment by MarioLiebisch** [comment]
Closing it for now. I added a label with the engine's version info hash and the used runtime is indeed an older build. Seems like Gradle doesn't like to follow symbolic links. Will reopen/update in case tearing everything down doesn't fix it.

**Comment by MarioLiebisch** [comment]
Just forgot mentioning my final conclusion (I think I wrote it down, then forgot submitting): Everything built/rebuilt properly and with the latest version, etc. I just completely missed the fact one has to "reinstall" the Android template after rebuilding/updating the runtime.

**Comment by tavurth** [comment]
Hmm I'm seeing this without any android template installed 🤔

```
  Attempt to get non-existent interface function: callable_custom_create.
  /Volumes/KaixoDev/kaixo-4/godot-cpp/src/godot.cpp:390 - Unable to load GDExtension interface function callable_custom_create()
  core/extension/gdextension.cpp:522 - GDExtension initialization function 'zigzag_library_init' returned an error.
```

Previously the same code was running ok on 4.0.1

**Comment by MarioLiebisch** [comment]
@tavurth Sounds like the same issue as I've had. Your GDExtension code is newer than the runtime sitting in `<project>/android/build`. Use the project menu to "install" the template and it should work again (given the template is up to date).

**Comment by tavurth** [comment]
@MarioLiebisch except I have no android build template installed for this project and never have done 🤔

**Comment by dsnopek** [comment]
@tavurth:

> Using Godot v4.2.dev5.official [e3e2528ba]

godot-cpp's `master` branch is meant to work with Godot's `master` branch. Godot 4.2.dev5 is a little behind Godot `master` and is missing some things that godot-cpp `master` depends on. So, you could compile your own Godot from `master`, or wait for the next 4.2 dev release (once the "beta" cycle starts, we won't be adding these sort of new features to Godot anymore).

**Comment by tavurth** [comment]
@MarioLiebisch @dsnopek That's working thank you guys!

1. Downgraded to 4.1.1
2. Swapped godot-cpp to branch 4.1
