### ISSUE TITLE
how to play wav audio by godot-cpp

### ISSUE THREAD

**Issue by TheRising-cxf** [godotengine/godot-cpp#1262]
### Godot version

4.0

### godot-cpp version

4.0

### System information

win10

### Issue description

It was correct when I played mp3 and failed when I played wav

### Steps to reproduce

        AudioStream* stream = NULL;
        if (Path->get_text().get_extension() == "mp3") {
            AudioStreamMP3 backstream;
            godot::PackedByteArray data = godot::FileAccess::get_file_as_bytes(Path->get_text());
            backstream.set_data(data);
            backstream.set_loop(true);
            stream = Object::cast_to<AudioStream>(&backstream);
        }
        else if(Path->get_text().get_extension() == "wav"){
            AudioStreamWAV backstream;
            godot::PackedByteArray data = godot::FileAccess::get_file_as_bytes(Path->get_text());
            backstream.set_data(data);
           // backstream.set_loop_mode(godot::AudioStreamWAV::LOOP_FORWARD);
            stream = Object::cast_to<AudioStream>(&backstream);
        }
        if (stream) {
            m_backgroundmp3Player->set_stream(stream);
            m_backgroundmp3Player->set_autoplay(true);
            m_backgroundmp3Player->play();
        }

### Minimal reproduction project

        AudioStream* stream = NULL;
        if (Path->get_text().get_extension() == "mp3") {
            AudioStreamMP3 backstream;
            godot::PackedByteArray data = godot::FileAccess::get_file_as_bytes(Path->get_text());
            backstream.set_data(data);
            backstream.set_loop(true);
            stream = Object::cast_to<AudioStream>(&backstream);
        }
        else if(Path->get_text().get_extension() == "wav"){
            AudioStreamWAV backstream;
            godot::PackedByteArray data = godot::FileAccess::get_file_as_bytes(Path->get_text());
            backstream.set_data(data);
           // backstream.set_loop_mode(godot::AudioStreamWAV::LOOP_FORWARD);
            stream = Object::cast_to<AudioStream>(&backstream);
        }
        if (stream) {
            m_backgroundmp3Player->set_stream(stream);
            m_backgroundmp3Player->set_autoplay(true);
            m_backgroundmp3Player->play();
        }

**Comment by AThousandShips** [comment]
Have you set the correct format?

**Comment by AThousandShips** [comment]
The WAV format can't be loaded like this, see https://github.com/godotengine/godot-proposals/issues/732

Not a bug but a limitation, see the proposal
