### ISSUE TITLE
Crypto class has no _new() method

### ISSUE THREAD

**Issue by ashtonmeuser** [godotengine/godot-cpp#1268]
### Godot version

4.1.2-stable

### godot-cpp version

godot-4.1.2-stable

### System information

MacOS 13.4, Windows 10

### Issue description

The generated Crypto class has no way of declaring a new reference. In the Godot 3.x branch of the C++ bindings, there exists a static `_new()` method. No such method exists in the 4.x branch. That means that users must manually use `unreference()` or errors indicating orphaned objects is thrown.

### Steps to reproduce

Build Godot C++ bindings. View resultant _godot-cpp/gen/include/godot_cpp/classes/crypto.hpp_ file. Note that there is no static `_new()` method (or similar equivalent).

### Minimal reproduction project

N/A

**Comment by dsnopek** [comment]
I'm not really familiar with how this worked in GDNative - can you share how you expect to use the `_new()` method?

Is there a reason you can't do something like:

```c++
Ref<Crypto> crypto;
crypto.instantiate();
Ref<CryptoKey> key = crypto->generate_rsa(4096);
```

I'm not entirely sure what you're trying to do with the `Crypt` class :-)

**Comment by ashtonmeuser** [comment]
Thanks! That works. I was looking for a single-line replacement for Godot 3.x's `Crypto::_new()->generate_random_bytes(n)` but this can be (hackily) achieved with `[n]()->PackedByteArray{Ref<Crypto> c;c.instantiate();return c->generate_random_bytes(n);}()`. Closing this issue.
