### ISSUE TITLE
`is_connected` returns false when it handler is registered

### ISSUE THREAD

**Issue by Naros** [godotengine/godot-cpp#1293]
### Godot version

4.2

### godot-cpp version

4.2

### System information

Windows 11

### Issue description

When verifying whether a code path is connected to another object when using `is_connected`, it always returns false, i.e.:
```cpp
if (!obj->is_connected("changed", callable_mp(this, &MyClass::_on_changed)))
  obj->connect("changed", callable_mp(this, &MyClass::_on_changed));
```
When this code path is executed twice for the same `obj` reference, it should only register the connection once.

### Steps to reproduce

1. In a simple GDExtension example, add the following C++ header and implementation file:
```cpp
// test.hpp

#include <godot_cpp/classes/node3d.hpp>
#include <godot_cpp/classes/resource.hpp>
#include <godot_cpp/templates/hash_map.hpp>
#include <godot_cpp/variant/utility_functions.hpp>

using namespace godot;

class CallableResource : public Resource
{
    GDCLASS(CallableResource, Resource);

    bool _value = false;

    static void _bind_methods() { }

    CallableResource() {}

    bool get_value() const { return _value; }
    void set_value(bool p_value) { _value = p_value; emit_changed(); }
};

class CallableNode : public Node3D
{
    GDCLASS(CallableNode, Node3D);

    HashMap<StringName, Ref<CallableResource>> _resources;

    static void _bind_methods();

    void _on_changed();

    CallableNode();

    bool get_value() const { return _resources["test"]->get_value(); }
    void set_value(bool p_value);

    int get_num_connections(Ref<CallableResource> res) { return res->get_signal_connection_list("changed").size(); }
};
```
```cpp
// implementation
#include "test.h"

void CallableNode::_bind_methods()
{
    ClassDB::bind_method(D_METHOD("get_value"), &CallableNode::get_value);
    ClassDB::bind_method(D_METHOD("set_value", "value"), &CallableNode::set_value);
    ADD_PROPERTY(PropertyInfo(Variant::BOOL, "value"), "set_value", "get_value");
}

CallableNode::CallableNode()
{
    _resources["test"] = Ref<CallableResource>(memnew(CallableResource));
}

void CallableNode::_on_changed()
{
    UtilityFunctions::print("Resource 'changed' callback fired");
}

void CallableNode::set_value(bool p_value)
{
    Ref<CallableResource> res = _resources["test"];
    UtilityFunctions::print("Resource currently has ", get_num_connections(res), " active connections to 'changed'");

    if (res.is_valid() && !res->is_connected("changed", callable_mp(this, &CallableNode::_on_changed)))
    {
        UtilityFunctions::print("Connecting to resource's 'changed' signal.");
        res->connect("changed", callable_mp(this, &CallableNode::_on_changed));
        UtilityFunctions::print("Resource now has ", get_num_connections(res), " active connections to 'changed'");
    }
    else
    {
        UtilityFunctions::print("Callback already registered.");
    }

    if (res.is_valid())
    {
        res->set_value(p_value);
        notify_property_list_changed();
    }
}
```

2. Register the two classes during start-up in EDITOR or SCENE scope.
3. In a blank project using the GDExtension sample, create a test scene, and add the `CallableNode` to the scene.  
4. In the inspector dock, there will be a check-box that you can toggle.
5. The first click establishes the first connection
6. The subsequent clicks establishes a new connection per click
7. Logs will report the number of connections for the `changed` signal before and after the toggle's logic.

Since there is only ever 1 `CallableResource` created and there is only 1 instance of the `CallableNode`, there should only ever be a single connection established; however the connections continue to accrue and the `"Callback already registered"` text is never output to the logs although it should on the 2+ clicks of the checkbox in the inspector.

### Minimal reproduction project

N/A

**Comment by dsnopek** [comment]
Thanks! I'm able to reproduce this issue and I have an idea about a fix

**Comment by dsnopek** [comment]
This would be fixed by PR https://github.com/godotengine/godot-cpp/pull/1294 which is still awaiting review
