### ISSUE TITLE
Godot fails to generate bindings for static method returning Object

### ISSUE THREAD

**Issue by SilicDev** [godotengine/godot-cpp#1295]
### Godot version

4.1.2

### godot-cpp version

4.1.2

### System information

Windows 11

### Issue description

Using godot_cpp I'm unable to bind a static method that returns an `Object` (or any subclass of it). However other return types like `int` or `String` work without issue. This is particularly a problem for static functions with complex return objects as they need to be translated to some other format (i. e. `Dictionary`) or wrapped in an array as `TypedArray` works as well even if typed with `Object`.

The build fails, as Godot seems to try to access the type info of the returned Object type before it's fully initialized:

```cl /Fosrc\classes\static_worker.windows.template_debug.x86_64.obj /c src\classes\static_worker.cpp /TP /std:c++17 /nologo /EHsc /utf-8 /MT /O2 /DTYPED_METHOD_BIND /DNOMINMAX /DWINDOWS_ENABLED /DDEBUG_ENABLED /DDEBUG_METHODS_ENABLED /DNDEBUG /Igodot-cpp\gdextension /Igodot-cpp\include /Igodot-cpp\gen\include /Isrc
static_worker.cpp
godot-cpp\include\godot_cpp/core/method_bind.hpp(701): error C2027: use of undefined type "godot::GetTypeInfo<R,void>"
        with
        [
            R=godot::Object
        ]
godot-cpp\include\godot_cpp/core/method_bind.hpp(701): note: see declaration of "godot::GetTypeInfo<R,void>"
        with
        [
            R=godot::Object
        ]
godot-cpp\include\godot_cpp/core/method_bind.hpp(697): note: while compiling class template member function "GDExtensionClassMethodArgumentMetadata godot::MethodBindTRS<R>::get_argument_metadata(int) const"
        with
        [
            R=godot::Object
        ]
godot-cpp\include\godot_cpp/core/method_bind.hpp(726): note: see reference to class template instantiation "godot::MethodBindTRS<R>".
        with
        [
            R=godot::Object
        ]
godot-cpp\include\godot_cpp/core/class_db.hpp(252): note: see reference to function template instantiation "godot::MethodBind *godot::create_static_method_bind<godot::Object,>(R (__cdecl *)(void))" der Funktions-Vorlage.
        with
        [
            R=godot::Object
        ]
src\classes\static_worker.cpp(34): note: see reference to function template instantiation "godot::MethodBind *godot::ClassDB::bind_static_method<godot::MethodDefinition,godot::Object(__cdecl *)(void),>(godot::StringName,N,M)" der Funktions-Vorlage.
        with
        [
            N=godot::MethodDefinition,
            M=godot::Object (__cdecl *)(void)
        ]
godot-cpp\include\godot_cpp/core/method_bind.hpp(701): error C2065: "METADATA": undefined identifier
scons: *** [src\classes\static_worker.windows.template_debug.x86_64.obj] Error 2
scons: building terminated because of errors.
```

### Steps to reproduce

1. Setup MRP as functional GDExtension project (should only need to add godot_cpp)
2. Run `scons`
The build should fail due to the static method `get_object`.

### Minimal reproduction project

MRP contains a simple cpp project with a class binding static methods for every possible return type.

[Static_Bindings_MRP.zip](https://github.com/godotengine/godot-cpp/files/13246216/Static_Bindings_MRP.zip)

**Comment by shackra** [comment]
I'm not seeing the other error I was getting from my Stackoverflow question:

```
In file included from godot-cpp/include/godot_cpp/core/method_bind.hpp:34:
godot-cpp/include/godot_cpp/core/binder_common.hpp: In instantiation of 'void godot::call_with_variant_args_static_ret(R (*)(P ...), const Variant**, Variant&, GDExtensionCallError&, IndexSequence<Is ...>) [with R = SingleHandRankingEvaluationResult; P = {PackedStringArray}; long unsigned int ...Is = {0}]':
godot-cpp/include/godot_cpp/core/binder_common.hpp:584:35:   required from 'void godot::call_with_variant_args_static_ret_dv(R (*)(P ...), const void* const*, int, Variant&, GDExtensionCallError&, const std::vector<Variant>&) [with R = SingleHandRankingEvaluationResult; P = {PackedStringArray}; GDExtensionConstVariantPtr = const void*]'
godot-cpp/include/godot_cpp/core/method_bind.hpp:707:39:   required from 'godot::Variant godot::MethodBindTRS<R, P>::call(GDExtensionClassInstancePtr, const void* const*, GDExtensionInt, GDExtensionCallError&) const [with R = SingleHandRankingEvaluationResult; P = {godot::PackedStringArray}; GDExtensionClassInstancePtr = void*; GDExtensionConstVariantPtr = const void*; GDExtensionInt = long int]'
godot-cpp/include/godot_cpp/core/method_bind.hpp:705:18:   required from here
godot-cpp/include/godot_cpp/core/binder_common.hpp:546:15: error: no match for 'operator=' (operand types are 'godot::Variant' and 'SingleHandRankingEvaluationResult')
  546 |         r_ret = (p_method)(VariantCasterAndValidate<P>::cast(p_args, Is, r_error)...);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from godot-cpp/include/godot_cpp/core/property_info.hpp:38,
                 from godot-cpp/include/godot_cpp/core/object.hpp:36,
                 from godot-cpp/include/godot_cpp/core/method_ptrcall.hpp:36,
                 from godot-cpp/include/godot_cpp/core/binder_common.hpp:36:
godot-cpp/include/godot_cpp/variant/variant.hpp:252:18: note: candidate: 'godot::Variant& godot::Variant::operator=(const godot::Variant&)'
  252 |         Variant &operator=(const Variant &other);
      |                  ^~~~~~~~
godot-cpp/include/godot_cpp/variant/variant.hpp:252:43: note:   no known conversion for argument 1 from 'SingleHandRankingEvaluationResult' to 'const godot::Variant&'
  252 |         Variant &operator=(const Variant &other);
      |                            ~~~~~~~~~~~~~~~^~~~~
godot-cpp/include/godot_cpp/variant/variant.hpp:253:18: note: candidate: 'godot::Variant& godot::Variant::operator=(godot::Variant&&)'
  253 |         Variant &operator=(Variant &&other);
      |                  ^~~~~~~~
godot-cpp/include/godot_cpp/variant/variant.hpp:253:38: note:   no known conversion for argument 1 from 'SingleHandRankingEvaluationResult' to 'godot::Variant&&'
  253 |         Variant &operator=(Variant &&other);
      |                            ~~~~~~~~~~^~~~~
godot-cpp/include/godot_cpp/core/binder_common.hpp: In instantiation of 'void godot::call_with_ptr_args_static_method_ret_helper(R (*)(P ...), const void* const*, void*, IndexSequence<Is ...>) [with R = SingleHandRankingEvaluationResult; P = {PackedStringArray}; long unsigned int ...Is = {0}; GDExtensionConstTypePtr = const void*]':
godot-cpp/include/godot_cpp/core/binder_common.hpp:594:54:   required from 'void godot::call_with_ptr_args_static_method_ret(R (*)(P ...), const void* const*, void*) [with R = SingleHandRankingEvaluationResult; P = {PackedStringArray}; GDExtensionConstTypePtr = const void*]'
godot-cpp/include/godot_cpp/core/method_bind.hpp:713:39:   required from 'void godot::MethodBindTRS<R, P>::ptrcall(GDExtensionClassInstancePtr, const void* const*, GDExtensionTypePtr) const [with R = SingleHandRankingEvaluationResult; P = {godot::PackedStringArray}; GDExtensionClassInstancePtr = void*; GDExtensionConstTypePtr = const void*; GDExtensionTypePtr = void*]'
godot-cpp/include/godot_cpp/core/method_bind.hpp:711:15:   required from here
godot-cpp/include/godot_cpp/core/binder_common.hpp:589:28: error: 'encode' is not a member of 'godot::PtrToArg<SingleHandRankingEvaluationResult>'
  589 |         PtrToArg<R>::encode(p_method(PtrToArg<P>::convert(p_args[Is])...), r_ret);
      |         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scons: *** [godot/poker.os] Error 1
```

**Comment by SilicDev** [comment]
I didn't include it because I'm relatively certain it's unrelated to the static method bind as I did not get it on my local MRP and it may be another issue causing that.

**Comment by shackra** [comment]
I see, @SilicDev, but I do get it despite changing the static method to a normal one, and it have me worried.

**Comment by SilicDev** [comment]
That's probably better suited for a more focused question on StackOverFlow, or any of the other help channels available https://docs.godotengine.org/en/stable/community/channels.html as this issue is specifically about the binding of static methods.

**Comment by dsnopek** [comment]
I don't know that we support (or want to support) passing around `Object` (as an argument or return value) rather than `Object *`.

One of godot-cpp's design goals is to have the same API as used internally in the engine (at least as much as is possible) and I don't think you can bind a function that passes `Object` (as opposed to `Object *`) in the engine either. I'd need to test it to be sure, though.

**Comment by SilicDev** [comment]
Hmm. Tbh with the `Ref<T>` class, I had to barely think about passing pointers so far, so I didn't even think of that, but you are correct with `Ref<T>` and the like we are mostly passing pointers around, so I'd assume `Object *` is the way to do this. (which builds correctly). So for the Binder this issue can likely be marked as resolved although it should maybe be documented if possible if it isn't already.

**Comment by shackra** [comment]
It should be documented indeed.

--
Jorge

**Comment by AThousandShips** [comment]
Note that passing a plain value of `Object` isn't really valid in c++ to begin with as it is a polymorphic type AFAIK, unless you pass by reference or pointer you break things, so unsure if this really aught to be documented

**Comment by SilicDev** [comment]
As it's probably to hard to guess, while I know C++ I don't have a lot of experience actually working with it, so this is something I've also only run into recently, but I see why it is an antipattern and agree probably shouldn't be supported. 
I'd still advocate for some sort of documentation as `String`, `Array` etc all can be passed directly (as they are considered value-types for the sake of the API) and due to the usage of templates the error isn't exactly obvious. This may be as simple as adding a static_assert that prints something along the lines of "'R' is an object instance, did you mean 'R *'?" although I'm aware that isn't necessarily common for c++ APIs.

**Comment by AThousandShips** [comment]
But the thing is that this is basic C++, and I don't think this limitation should be in the documentation, and especially not an error, as it's just not correct code to pass a polymorphic class like this

**Comment by SilicDev** [comment]
I'll close the issue then, even if I will add for the record that I disagree with this reasoning: Unless it comes with a significant overhead I see no reason not to add a message to make the error clearer, especially if it is not easy to read from the error and can be triggered as easily as a typo. 
(example: copying a `Ref<T>` return method for a non `RefCounted` type (i. e. `Node`s)) but maybe someone with more experience in C++ may not even make this mistake, or realise it immediately. 
Admittedly my own gdextension codebase only uses pointers or `Ref<T>`, except for designated value types, but it never really stood out to me so I didn't notice it on the StackOverflow question that started this.
