### ISSUE TITLE
msvc builds cause warning `c4530`

### ISSUE THREAD

**Issue by Repiteo** [godotengine/godot-cpp#1297]
### Godot version

v4.2.beta.custom_build [5ee983188]

### godot-cpp version

c1196a1ab0a1ca166d0e5e2f08f9fe4156118c5e

### System information

Windows 11

### Issue description

Recently, my godot-cpp builds have had their logs absolutely FLOODED with this message en-masse:
```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vector(1612): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vector(1601): note: while compiling class template member function 'void std::vector<GDExtensionClassMethodArgumentMetadata,std::allocator<GDExtensionClassMethodArgumentMetadata>>::_Reallocate_exactly(const unsigned __int64)'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vector(1685): note: see the first reference to 'std::vector<GDExtensionClassMethodArgumentMetadata,std::allocator<GDExtensionClassMethodArgumentMetadata>>::_Reallocate_exactly' in 'std::vector<GDExtensionClassMethodArgumentMetadata,std::allocator<GDExtensionClassMethodArgumentMetadata>>::reserve'
D:\Godot\godot-libusb\godot-cpp\include\godot_cpp/core/method_bind.hpp(134): note: see the first reference to 'std::vector<GDExtensionClassMethodArgumentMetadata,std::allocator<GDExtensionClassMethodArgumentMetadata>>::reserve' in 'godot::MethodBind::get_arguments_metadata_list'
D:\Godot\godot-libusb\godot-cpp\include\godot_cpp/core/method_bind.hpp(131): note: see reference to class template instantiation 'std::vector<GDExtensionClassMethodArgumentMetadata,std::allocator<GDExtensionClassMethodArgumentMetadata>>' being compiled
```
I haven't been actively building a gdextension up until this past week or so, so I can't speak for how long this has potentially been in place. The last time I was actively building was late July, and it wasn't present at that time

### Steps to reproduce

1. build with msvc
2. cry

### Minimal reproduction project

N/A

**Comment by dsnopek** [comment]
Hm, this sounds like it's related to PR https://github.com/godotengine/godot-cpp/pull/1216 which disabled exceptions by default. We do use STL a bit in godot-cpp - I wonder if that means exceptions need to be enabled?

Do you still get the error when you build with `scons disable_exceptions=no`?

**Comment by Repiteo** [comment]
I tried building with that & the warning still appeared

**Comment by Repiteo** [comment]
Wait, I figured it out! The `is_msvc` define wasn't working because the order was out of wack! We never realized this because it was using the problematic `env.get("is_msvc", False):` syntax instead of ensuring a valid value ahead of time and then using `env[is_msvc]`. This is the same issue that I was already addressing in another PR, but I never expanded it to `is_msvc` there; I'll do that now and link it after!
