### ISSUE TITLE
Using GDCLASS macro makes private class members public

### ISSUE THREAD

**Issue by tcoxon** [godotengine/godot-cpp#1305]
### Godot version

4.1.1.stable.official

### godot-cpp version

Tag: godot-4.1.1-stable

### System information

Arch Linux (rolling release)

### Issue description

I noticed while working on the Terrain3D plugin that classes are able to access certain private members of another class it isn't friends with.

Specific example:

1. This line accesses Terrain3DStorage::_update_regions: https://github.com/TokisanGames/Terrain3D/blob/5dfaa132010db7bb5486d6197d8fe151fc13d0ed/src/terrain_3d.cpp#L70
2. That member is in Terrain3DStorage's private section: https://github.com/TokisanGames/Terrain3D/blob/5dfaa132010db7bb5486d6197d8fe151fc13d0ed/src/terrain_3d_storage.h#L102

Terrain3D doesn't use `friend` declarations anywhere.

Zylann on the discord server for Terrain3D pointed out it could be a side-effect of the GDCLASS macro, and indeed, GDCLASS in godot-cpp ends without a `private:`
https://github.com/godotengine/godot-cpp/blob/2dfe7929de31e52258380e414cce6978c1c94344/include/godot_cpp/classes/wrapped.hpp#L368

The final line of the GDCLASS macro in the engine itself does end with `private:`.

### Steps to reproduce

1. Clone the [Terrain3D](https://github.com/TokisanGames/Terrain3D/) repository
2. Build it and note no compiler errors

### Minimal reproduction project

N/A

**Comment by capnm** [comment]
https://github.com/godotengine/godot-cpp/pull/1292
