### ISSUE TITLE
Try to use godot::thread, std::thread, std::async, to copy the yield(gdscripts)/await(c#) ?

### ISSUE THREAD

**Issue by chriztheanvill** [godotengine/godot-cpp#1336]
### Godot version

4.2.1.stable

### godot-cpp version

4.2

### System information

Godot v4.2.1.stable - openSUSE Tumbleweed 20231211 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

Trying to implement this to C++.
```cpp
// GDscript
$AnimationPlayer.play('dissolve')
yield($AnimationPlayer, 'animation_finished')
get_tree().change_scene(target)
$AnimationPlayer.play_backwards('dissolve')

// C#
public async void ChangeScene(string target)
{
  anim.Play("Dissolve");
  await ToSignal(anim, "animation_finished");
  GetTree().ChangeSceneToFile(target);
  anim.PlayBackwards("Dissolve");
}
```

Tried to use `godot::thread, std::thread, std::async and chrono`, to change the scene but godot complains about standard libs.
Also tried to get the AnimationPlayer reproduction time, wait, then change scene, but cant change scene with a thread.

### Steps to reproduce

Try `godot::thread, std::thread, std::async + std::chronos`, add a thread to wait the seconds then change the scene.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels *first* to see if this is a bug or user error.

**Comment by Calinou** [comment]
Closing per the above comment.
