### ISSUE TITLE
Variant::Operation::OP_POWER is missing

### ISSUE THREAD

**Issue by limbonaut** [godotengine/godot-cpp#1348]
### Godot version

4.2.1-stable

### godot-cpp version

4.2.1-stable

### System information

N/A

### Issue description

`Variant::Operation::OP_POWER` is strangely missing.
It is present in the engine code and in GDScript.

### Steps to reproduce

Check variant.hpp.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Potential problem is that this would break compatibility by changing the order, unsure how to resolve this, and how it interacts with the engine
