### ISSUE TITLE
Default values for arguments are in wrong order

### ISSUE THREAD

**Issue by lihop** [godotengine/godot-cpp#1352]
### Godot version

4.2.1-stable

### godot-cpp version

godot-4.2.1-stable

### System information

Linux (NixOS 24.05 Uakari)

### Issue description

Default values for arguments should be passed in reverse order, however godot-cpp expects them to be in non-reverse order. Functions do receive the correct arguments, but the in-editor documentation is incorrect. It also causes an error when mixing default values of different types.

From [the documentation](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/object_class.html#registering-an-object):

> Default values for arguments can be passed in reverse order:
> ```
> ClassDB::bind_method(D_METHOD("methodname", "arg1name", "arg2name"), &MyCustomType::method, DEFVAL(-1)); // default value for arg2name
> ```

Given the example method:
https://github.com/godotengine/godot-cpp/blob/78ffea5b136f3178c31cddb28f6b963ceaa89420/test/src/example.cpp#L229

| Expected | Actual |
|--------------|----------|
| ![int def_args(a: int = 200, b: int = 100)](https://github.com/godotengine/godot-cpp/assets/3696783/e94ce5c1-9ac9-4ec2-b97e-3fe932d2ef8a) |  ![int def_args(a: int = 100, b: int = 200)](https://github.com/godotengine/godot-cpp/assets/3696783/43ae96db-358e-49ac-8d3e-00920605a151) |

### Steps to reproduce

1. Create a method with mixed default values:
    ```c++
    // example.h
    int mixed_def_args(String p_a = "a", int p_b = 200);
    
    // example.cpp
    int Example::mixed_def_args(String p_a, int p_b) {
        return p_a.length() + p_b;
    }
    void Example::_bind_methods() {
        ClassDB::bind_method(D_METHOD("mixed_def_args", "a", "b"), &Example::mixed_def_args, DEFVAL(200), DEFVAL("a"));
    }
    ```
    ```gdscript
    # main.gd
    func _ready():
        var example: Example = $Example
        print(mixed_def_args())
    ```
 
 **Expected**
![int mixed_def_args(a: String = "a", b: int = 200)](https://github.com/godotengine/godot-cpp/assets/3696783/403ac702-ce87-4396-9b7e-fe3f5a8d487b)
 Console output:
 ```
 201
 ```
 
 **Actual**
![int mixed_def_args(a: String = 200, b: int = "a")](https://github.com/godotengine/godot-cpp/assets/3696783/88f27db0-9339-4512-ac0e-54c0af295d2b)
![2024-01-07-232341_405x222_scrot](https://github.com/godotengine/godot-cpp/assets/3696783/e57a0127-b8bb-4583-b4a3-b0bc77213cb7)
Error message: `Invalid type in function 'mixed_def_args' in base 'Example'. Cannot convert argument 1 from Object to String.`

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
You've got this backwards, the arguments are in the same order, see:
```
ClassDB::bind_method(D_METHOD("load_threaded_request", "path", "type_hint", "use_sub_threads", "cache_mode"), &ResourceLoader::load_threaded_request, DEFVAL(""), DEFVAL(false), DEFVAL(CACHE_MODE_REUSE));
```
And
```
Error load_threaded_request(const String &p_path, const String &p_type_hint = "", bool p_use_sub_threads = false, CacheMode p_cache_mode = CACHE_MODE_REUSE);
```

**Comment by AThousandShips** [comment]
I'm writing up a documentation fix for this

**Comment by lihop** [comment]
Hi @AThousandShips, thanks for the review.
I did have it backwards, and can confirm that the additional test cases in the PR pass when the arguments are in the same order.
Thanks for initiating a clarification in the documentation!

**Comment by AThousandShips** [comment]
Not completed, let's merge the PR first 🙂

**Comment by dsnopek** [comment]
Oops, sorry :-)
