### ISSUE TITLE
Image: expose mipmap related methods 

### ISSUE THREAD

**Issue by ozzr** [godotengine/godot-cpp#1369]
### Godot version

master

### godot-cpp version

master

### System information

Any

### Issue description

The methods below are available when writing modules but they are not exposed to GDExtension. They are simple to port but since they are already available in the core of the engine exposing them should be more than welcome to avoid unnneccesary work on compatibility classes to mimic already existing behaviours.

```cpp
       // per object methods

	int get_mipmap_byte_size(int p_mipmap) const; //get where the mipmap begins in data
	int get_mipmap_offset(int p_mipmap) const; //get where the mipmap begins in data
	void get_mipmap_offset_and_size(int p_mipmap, int &r_ofs, int &r_size) const; //get where the mipmap begins in data
	void get_mipmap_offset_size_and_dimensions(int p_mipmap, int &r_ofs, int &r_size, int &w, int &h) const; //get where the mipmap begins in data

       // Static Methods
	static int get_format_pixel_size(Format p_format);
	static int get_format_pixel_rshift(Format p_format);
	static int get_format_block_size(Format p_format);
	static void get_format_min_pixel_size(Format p_format, int &r_w, int &r_h);

	static int get_image_data_size(int p_width, int p_height, Format p_format, bool p_mipmaps = false);
	static int get_image_required_mipmaps(int p_width, int p_height, Format p_format);
	static Size2i get_image_mipmap_size(int p_width, int p_height, Format p_format, int p_mipmap);
	static int get_image_mipmap_offset(int p_width, int p_height, Format p_format, int p_mipmap);
	static int get_image_mipmap_offset_and_dimensions(int p_width, int p_height, Format p_format, int p_mipmap, int &r_w, int &r_h);

```

### Steps to reproduce

calling the mentioned methods above fails in extensions 

### Minimal reproduction project

access image method from extension code

**Comment by AThousandShips** [comment]
They'd have to be exposed to scripting first and that should be discussed [here](https://github.com/godotengine/godot-proposals/issues)

**Comment by dsnopek** [comment]
There's really nothing to do in godot-cpp to exposed these. Once they are exposed in the engine, the methods will get automatically generated in godot-cpp from the `extension_api.json` as well. So, I'm going to close this one.
