### ISSUE TITLE
Array operator [] slower than GDscript

### ISSUE THREAD

**Issue by wagnerfs** [godotengine/godot-cpp#1393]
### Godot version

4.2.1.stable

### godot-cpp version

4.2.1.stable

### System information

Windows 10

### Issue description

I've been trying to manipulate meshes in Godot, specificaly `ArrayMesh` from `mesh->surface_get_arrays(0)`.
apparently a code like:
```gdscript
for i in arrays[Mesh.ARRAY_VERTEX].size():
    arrays[Mesh.ARRAY_VERTEX][i] += Vector3(1, 1, 1)
    arrays[Mesh.ARRAY_NORMAL][i] += Vector3(1, 1, 1)
```
runs in around 23074 microseconds, which's much faster than:
```c++
PackedVector3Array arrays_vertex = arrays[Mesh::ARRAY_VERTEX];
PackedVector3Array arrays_normal = arrays[Mesh::ARRAY_NORMAL];
for (int i = 0; i < arrays_vertex.size(); i++) {
    arrays_vertex[i] += Vector3(1, 1, 1);
    arrays_normal[i] += Vector3(1, 1, 1);
}
```
which runs in around 26807 microseconds.

The only thing I can think of is that the `operator[]` is generating a high overhead when requested in GDextension.
I'm not too familiar with godot_cpp but the quick look I gave in `array.cpp` I noticed that the `operator[]` is implemented in `packed_arrays.cpp` instead and the code looks quite different too.

### Steps to reproduce

See above

### Minimal reproduction project

Not applied

**Comment by dsnopek** [comment]
Is performance better if you use `ptrw()` instead of `operator []`? So, something like:

```
Vector3 *arrays_vertex = arrays[Mesh::ARRAY_VERTEX].ptrw();
Vector3 *arrays_normal = arrays[Mesh::ARRAY_NORMAL].ptrw();
int size = arrays[Mesh::ARRAY_VERTEX].size();
for (int i = 0; i < size; i++) {
    arrays_vertex[i] += Vector3(1, 1, 1);
    arrays_normal[i] += Vector3(1, 1, 1);
}
```

There is some overhead associated with crossing the Godot <-> GDExtension boundary, and using `ptrw()` would avoid that as much as possible. I don't know if that is what's causing the slowness in your case, but it's worth a try!
