### ISSUE TITLE
Unable to catch error message

### ISSUE THREAD

**Issue by 28176004** [godotengine/godot-cpp#1394]
### Godot version

v4.2-stable

### godot-cpp version

4.2.1-stable

### System information

Windows 10

### Issue description

I used godot_cpp to reproduce the official demo "compute_shader_heightmap". An error occurred in the code, but vs code was unable to catch the error message. Output only in the editor. How do I get vs code to capture the underlying error output
![屏幕截图(9)](https://github.com/godotengine/godot-cpp/assets/44051488/b5d8e811-2830-4b3c-bdca-43e4fd53d623)
![屏幕截图(10)](https://github.com/godotengine/godot-cpp/assets/44051488/0ba8b748-2906-4183-9123-ac4e0086a8d8)

### Debug configuration
```
{
      "name": "Map_start",
      "type": "cppdbg",
      "request": "launch",
      "program": "d:/Godot/Godot_v4.2-stable_win64.exe",
      "args": ["--path", "d:/Project/War2/Editor"],  
      "stopAtEntry": false,
      "cwd": "${fileDirname}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "miDebuggerPath": "C:\\w64devkit\\bin\\gdb.exe",
      "setupCommands": [
        {        
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        },
        {
          "text": "-gdb-set disassembly-flavor intel",
          "ignoreFailures": true
        }
      ]
    }
```

### Minimal reproduction project

N/A

**Comment by pupil1337** [comment]
The officially released stable editor does not have debugging information, cannot debug godot. Need compile godot self, and launch it.
