### ISSUE TITLE
using gdextension:register a class extend TileMap,add some layers,then delete a layers ,consle log:"editor/editor_inspector.cpp:1742 - Could not find a function to move arrays elements for class my tileMap. Register a move element function using EditorData::add_move_array_element_function"

### ISSUE THREAD

**Issue by MAXFROMCODE** [godotengine/godot-cpp#1398]
### Godot version

4.2.1 stable

### godot-cpp version

Godot Engine v4.2.1.stable.official

### System information

windows10

### Issue description

a class extend TileMap can not delete layer

### Steps to reproduce

1、create a gdextension class extend TileMap,register;
![1709374989849](https://github.com/godotengine/godot-cpp/assets/142991584/654efad4-b19a-4aea-a08e-45e51d9ac735)
2、cereate node and add some layers ;
![image](https://github.com/godotengine/godot-cpp/assets/142991584/9a3e6409-6ee1-49a8-bbb5-9d7a3aaca5d0)
3、delete a layer,then consle will log :" editor/editor_inspector.cpp:1742 - Could not find a function to move arrays elements for class DynamicTileMap. Register a move element function using EditorData::add_move_array_element_function".
![image](https://github.com/godotengine/godot-cpp/assets/142991584/3e1c1a4f-f8bf-4bc4-aef7-ebad9ee57d40)

by the way:how to resolve this bug?
change node type to TileMap,and choose layer what you want delete,and change back to you class type

### Minimal reproduction project

N/A

**Comment by MAXFROMCODE** [comment]
forget to say ! move element index is not also

**Comment by MAXFROMCODE** [comment]
i  found can not do any edit operater

**Comment by dsnopek** [comment]
Thanks!

This is the same issue as described on proposal https://github.com/godotengine/godot-proposals/issues/8293, which could potentially be fixed via PR https://github.com/godotengine/godot/pull/84126

Please feel free to thumbs up or share your experience over there!
