### ISSUE TITLE
is_finite function missing from Basis, Vector2, Vector3, etc.(about 11 classes should have it)

### ISSUE THREAD

**Issue by Ughuuu** [godotengine/godot-cpp#1434]
### Godot version

4.2

### godot-cpp version

4.2

### System information

mac m1

### Issue description

In `godot` > `core/math/basis.h` there is `bool is_finite() const;`
In `godot-cpp` there isn't such a method. I tried to replicate it, but it's also missing on `Vector2` and `Vector3` and other classes (more can be found in extension_api.json file with all places it should be).

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by AThousandShips** [comment]
I'll write up a transfer PR tomorrow for these classes syncing them

**Comment by Ughuuu** [comment]
Perfect, initially I wanted to do a PR but there seems to be a bit of work to do.
