### ISSUE TITLE
ImporterMesh generate_lods doesn't produce lods

### ISSUE THREAD

**Issue by Redcroft** [godotengine/godot-cpp#1464]
### Godot version

4.2.2

### godot-cpp version

4.2

### System information

NixOS, Ryzen 3950X

### Issue description

I have an ImporterMesh which brings in surfaces just fine, but after adding all the surfaces and trying to generate lods, none are generated

### Steps to reproduce

```
  importer_mesh->generate_lods(UtilityFunctions::deg_to_rad(25), UtilityFunctions::deg_to_rad(60), Array());
  UtilityFunctions::print(importer_mesh->get_mesh()->_surface_get_lods(0));
```

no lods are generated, and the print debug is just `{  }`.

### Minimal reproduction project

[lod.debug.zip](https://github.com/godotengine/godot-cpp/files/15355478/lod.debug.zip)

**Comment by AThousandShips** [comment]
This isn't likely to be unique to godot-cpp, please make sure this *only* occurs with extension and not GDScript or C#, if it does occur with those please report over [here](https://github.com/godotengine/godot/issues)

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
