### ISSUE TITLE
Godot-cpp fails to generate vsproj when vsproj=yes. command is ignored

### ISSUE THREAD

**Issue by jak6jak** [godotengine/godot-cpp#1470]
### Godot version

daa81bb

### godot-cpp version

b697ba8

### System information

Windows 11

### Issue description

When building godot-cpp or the recommended template inside the readme it fails to recognize the vsproj=yes command. I get the following error: ```WARNING: Unknown SCons variables were passed and will be ignored:
    vsproj=yes``` the build succeeds but is unable to generate vsproj. 

### Steps to reproduce

1. clone godot-cpp or godot-cpp template: https://github.com/godotengine/godot-cpp-template
2. Run command scons vsproj=yes
3. Observe that the build is successfully but without generating vsproj

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
There's no such option for godot-cpp, just for Godot itself, so this would be proposing a new feature
