### ISSUE TITLE
GDExtension doesn't call _init() method

### ISSUE THREAD

**Issue by ashtonmeuser** [godotengine/godot-cpp#1501]
### Godot version

v4.2.2.stable.official [15073afe3]

### godot-cpp version

godot-4.2.2-stable [98c143a48]

### System information

macOS 14.5 (23F79)

### Issue description

GDExtension `_init()` method is not called on instantiation of a new instance.

### Steps to reproduce

1. Create a simple GDExtension class following [this example](https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html). Register `_init()` method and print from it.
    ```cpp
    void DummyNode::_bind_methods() {
      ClassDB::bind_method(D_METHOD("_init"), &DummyNode::_init);
    }
    DummyNode::DummyNode() {
      UtilityFunctions::print("DummyNode constructor");
    }
    DummyNode::~DummyNode() {
      UtilityFunctions::print("DummyNode destructor");
    }
    void DummyNode::_init() {
      UtilityFunctions::print("DummyNode _init");
    }
    void DummyNode::_ready() {
      UtilityFunctions::print("DummyNode _ready");
    }
    ```

1. Create an instance of the class in GDScript.
    ```gdscript
    DummyNode.new()
    ```

1. Expect to see "DummyNode _init" printed but no such log is present. Other expected initialization methods are called.

### Minimal reproduction project

N/A

**Comment by dsnopek** [comment]
`_init()` as a constructor is a GDScript thing - it has no special meaning in GDExtension, it'll be just like any function which would need to be called manually.

If you need to do initialization, I'd recommend doing it in the C++ constructor (`DummyNode::DummyNode()` in this case) or when `NOTIFICATION_POSTINITIALIZE` is sent to `_notification()`.

**Comment by ashtonmeuser** [comment]
Understood. It seems the only environment in which `_init()` is automatically called is Godot 3.x GDNative addons. Closing this issue.
