### ISSUE TITLE
How to build a target with godot-cpp and gdextension for HTML export ？

### ISSUE THREAD

**Issue by MoonLighting7** [godotengine/godot-cpp#1515]
### Godot version

master

### godot-cpp version

master

### System information

windos 11 

### Issue description

I need a tool to integrate compiling WebAssembly targets.

### Steps to reproduce

**

### Minimal reproduction project

**

**Comment by AThousandShips** [comment]
This is for reporting bugs, not asking support questions, please ask in other [channels](https://godotengine.org/community/)
