### ISSUE TITLE
The Signal class is un-used

### ISSUE THREAD

**Issue by xana43** [godotengine/godot-cpp#1523]
### Godot version

Godot v4.2.3.rc (b9f01dcf8)

### godot-cpp version

godot-4.2-stable (9da6ecd)

### System information

Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XT (RADV NAVI31) () - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

When conntecting a signal from an engine class, such as node. You have to use the name of the signal then the callable to connect it to, however the Signal class still exists yet doesn't get used at all like it does in GDScript.

### Steps to reproduce

Create a class that inherits from Node, then define a new signal. Example being

```
class SignalTest final : public Node3D {
           GDCLASS(SignalTest,Node3D)
public:
           Signal testSignal{this,"test_signal"};
private:
    static void _bind_methods(){
              ADD_SIGNAL("test_signal");
    }

};
```

then in another class

```
class TestSignalUsage final: public Node3D {
          GDCLASS(TestSignalUsage,Node3D)
      void _ready() override{
               SignalTest* signalTestInstance = get_node<SignalTest>(signalTestNodePath);
               //signalTestInstance->visiblity_changed.connect(Callable(this,"do_something")); doesn't work at all as this doesn't exist
              signalTestInstance->connect("visibility_changed",Callable(this,"do_something")); //connects the visibility signal
              signalTestInstance->testSignal.connect(Callable(this,"do_something")); // works exactly like it does in gdscript
       }

void doSomething();
static void _bind_methods(){
    ClassDB::bind_method(D_METHOD("do_something"),&TestSignalUsage::doSomething);
}
};
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
You can still use it, and pass signals from the engine, most classes in the engine are "unused" as such, but they still are relevant, even though they can't be interacted with in the exact same way as in the GDScript code

**Comment by xana43** [comment]
tbh, I'm confused as to why it's not used by classes like node. I'd think it'd cut down on the potential pain point of mis-spelling a signal that comes from a built-in class (source: I've done that many times while trying to connect a signal like visibility) and it was only recently that I found out this class even existed. Maybe this could be documented somewhere?

**Comment by AThousandShips** [comment]
Because they're not used in c++ in that way, the Godot-cpp code should match the ways it works, otherwise you can't make both modules and extensions, there isn't a simple way to do this in the engine itself, nor really here

How would you make this work for a custom class? How would it register this signal object on the class and initialize it with the class?

The GDScript code doesn't just have it as some data, it's created when fetched with `get`, so it's syntactic sugar in GDScript

**Comment by xana43** [comment]
> Because they're not used in c++ in that way, the Godot-cpp code should match the ways it works, otherwise you can't make both modules and extensions, there isn't a simple way to do this in the engine itself, nor really here, you'd have to have some kind of automated system to initialize the signal member variables on construction to link them to the object, and it'd be a lot of fragile code
> 
> How would you make this work for a custom class? How would it register this signal object on the class and initialize it with the class?
> 
> The GDScript code doesn't just have it as some data, it's created when fetched with `get`, so it's syntactic sugar in GDScript
> 
> > Maybe this could be documented somewhere?
> 
> Document what and where? The class is documented

oh ok, that makes more sense as to how it works in GDscript, for how to get it to work. Wouldn't it be possible to initialize it like a normal variable?(correct me if i'm wrong) but because signals are registered already and since the constructor for the signal used in the example just takes the current reference to the object and the signal wouldn't it be possible to do this in a constructor, or like at _ready()? (Also the part about the documentation, that was a typo, I originally wrote this on my phone and I accidentally clicked on the auto complete before sending and didn't realize)

**Comment by AThousandShips** [comment]
That would theoretically work but it would have to be in the constictor, but it'd be fragile, and error prone, and would have to be done in the engine first

So I'd suggest opening a [proposal](https://github.com/godotengine/godot-proposals) for this

Closing this as there's no issue here, but would be something that would be a proposal, and should be made there to first make this in the engine itself or it wouldn't make sense to add to Godot-cpp, as we have to match between the engine and here feature wise
