### ISSUE TITLE
Error on the command scons platform=linux

### ISSUE THREAD

**Issue by DexterFstone** [godotengine/godot-cpp#1537]
### Godot version

4.2.2.stable

### godot-cpp version

4.2

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - ANGLE (AMD, AMD Radeon HD 5570 (0x000068D9) Direct3D11 vs_5_0 ps_5_0, D3D11-8.17.10.1433) () - Intel(R) Pentium(R) CPU G2030 @ 3.00GHz (2 Threads)

### Issue description

Hi, I'm working on GDExtension, when I run the command scons platform=linux, I get the error.
I don't know if it is a bug or if I miss something.

```
PS C:\Users\Dexter\Documents\gdextension_cpp_example> scons platform=linux
scons: Reading SConscript files ...
Auto-detected 2 CPU cores available for build parallelism. Using 2 cores by default. You can override it with the -j argument.
Building for architecture x86_64 on platform linux
scons: done reading SConscript files.
scons: Building targets ...
Linking Static Library godot-cpp\bin\libgodot-cpp.linux.template_debug.x86_64.a ...
scons: C:\Windows\System32\cmd.exe: No such file or directory
scons: *** [godot-cpp\bin\libgodot-cpp.linux.template_debug.x86_64.a] Error 127
scons: building terminated because of errors.
```

### Steps to reproduce

1. create a GDExtension
2. run the command scons platform=linux

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I don't know if cross-compiling from Windows to Linux is supported by godot-cpp. You may have better luck using [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install) and compiling "natively" for Linux in the WSL terminal.

**Comment by ag-rutger** [comment]
I had this error when (cross) compiling for a console platform. I managed to fix it by using this code snippet that I lifted from tools/android.py to my platform.py :
    if sys.platform == "win32" or sys.platform == "msys":
        my_spawn.configure(env)
