### ISSUE TITLE
Web export fails due to Uncaught LinkError

### ISSUE THREAD

**Issue by 2shady4u** [godotengine/godot-cpp#1553]
### Godot version

v4.3-stable

### godot-cpp version

4.3

### System information

Windows 10

### Issue description

Exporting to web fails because of following error:
```
TypeError: a.default.detectStore(...) is undefined h1-check.js:1:1301
Uncaught (in promise) LinkError: imported function 'env._ZNSt3__29to_stringEx' signature mismatch
```

I have tried exporting with both threads enabled and disabled and I get the same issue.
I used Firefox, Chrome and Vivaldi and all of them report the same error.

My build system uses Emscripten v3.1.39 and can be found here:
[https://github.com/2shady4u/godot-sqlite](https://github.com/2shady4u/godot-sqlite)

### Steps to reproduce

- Run the minimal reproduction project
- Open the 'Web Developer Tools' in your browser.
- Observe the error.

### Minimal reproduction project

[demo.zip](https://github.com/user-attachments/files/16649233/demo.zip)

**Comment by 2shady4u** [comment]
I have tried re-compiling my binaries using Emscripten 3.1.64 (as found [here](https://github.com/godotengine/godot/blob/master/.github/workflows/web_builds.yml)), but I get the exact same error...

**Comment by Faless** [comment]
Possibly related issue: https://github.com/godotengine/godot/issues/96492 .

We should test if this is a regression from https://github.com/godotengine/godot/pull/93853
