### ISSUE TITLE
Ref cannot be used in tweens

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot-cpp#1565]
### Godot version

4.4-dev1

### godot-cpp version

4.4-dev1

### System information

Godot v4.4.dev1 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 32.0.15.6070) - 13th Gen Intel(R) Core(TM) i5-13500HX (20 Threads)

### Issue description

Trying to tween properties on a Ref<> object does not work because it expects an Object*
![image](https://github.com/user-attachments/assets/c3bee43c-2626-4363-9f42-f7df3e65a5ff)
![image](https://github.com/user-attachments/assets/5d89e58e-04ca-4e51-b5c0-88a5f4c2f8bf)

Trying to compile:
![image](https://github.com/user-attachments/assets/f2500722-924e-4c60-b25a-28f501140e2a)

### Steps to reproduce

Create a tween inside a function
Try to tween the properties of a Ref<> instead of an object or node pointer
Watch as it does not compile

`Source\BopimoCPP\Classes\GUI\HoverStar.cpp(31): error C2664: 'godot::Ref<godot::PropertyTweener> godot::Tween::tween_property(godot::Object *,const godot::NodePath &,const godot::Variant &,double)': cannot convert argument 1 from 'godot::Ref<godot::ShaderMaterial>' to 'godot::Object *'
Source\BopimoCPP\Classes\GUI\HoverStar.cpp(31): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
godot-cpp\gen\include\godot_cpp/classes/tween.hpp(93): note: see declaration of 'godot::Tween::tween_property'
Source\BopimoCPP\Classes\GUI\HoverStar.cpp(31): note: while trying to match the argument list '(godot::Ref<godot::ShaderMaterial>, const char [24], const float, const float)'
Source\BopimoCPP\Classes\GUI\HoverStar.cpp(32): error C2664: 'godot::Ref<godot::PropertyTweener> godot::Tween::tween_property(godot::Object *,const godot::NodePath &,const godot::Variant &,double)': cannot convert argument 1 from 'godot::Ref<godot::ShaderMaterial>' to 'godot::Object *'
Source\BopimoCPP\Classes\GUI\HoverStar.cpp(32): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
godot-cpp\gen\include\godot_cpp/classes/tween.hpp(93): note: see declaration of 'godot::Tween::tween_property'
Source\BopimoCPP\Classes\GUI\HoverStar.cpp(32): note: while trying to match the argument list '(godot::Ref<godot::ShaderMaterial>, const char [24], float, const float)'
scons: *** [Source\BopimoCPP\Classes\GUI\HoverStar.windows.template_debug.x86_64.obj] Error 2
scons: building terminated because of errors.`

### Minimal reproduction project

n/a

**Comment by pupil1337** [comment]
use `tween_property(*material, xxx, xxx, xxx);` or `tween_property(material.ptr(), xxx, xxx, xxx);`
detail see ref.hpp

Additionally, you can enable C++ Intellisense by godot doc [Configuring an IDE/Visual Studio Code](https://docs.godotengine.org/en/latest/contributing/development/configuring_an_ide/index.html)

**Comment by FireCatMagic** [comment]
oh i'm stupid thanks
