### ISSUE TITLE
[C++] Regression in 4.3: `std::set_terminate` fails to set termination handler

### ISSUE THREAD

**Issue by int-72h** [godotengine/godot-cpp#1576]
### Tested versions

- Reproducible in 4.3.stable
- Not reproducible in 4.2.2.stable

### System information

Arch Linux - Ryzen 5 5600X (x86_64)

### Issue description

The C++ function `std::set_terminate` sets the termination function when an exception's not handled. In Godot 4.3.stable, this function doesn't seem to do anything: the stock termination handler is always used. In 4.2.2.stable, this issue isn't there - the function is called.
This doesn't seem to depend on the version of godot_cpp - same version is used (latest) therefore the bug's in the main engine presumably.

### Steps to reproduce

- Download the MRP
- ``git submodule update --init`` to obtain godot-cpp
- Use scons to build the library + godot-cpp
- Open the project using godot 4.2.2 (with console). It will crash, however the terminate handler will be called, printing a few extra lines before crashing.
- Launch godot 4.3 (with console output)
- Open the project. It will also crash, however the output will be of the standard C++ terminate handler.

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/16936840/mrp.zip)

**Comment by int-72h** [comment]
I was using the latest version of godot-cpp in both instances (as that's what the example project does).
The build of 4.3.stable was obtained from the Arch Linux repos, the 4.2.2.stable build from the archive.

I'll try testing this with 4.3.stable from the archive as well, but I don't believe this is a config issue since an exception is thrown in both cases, if there wasn't an exception handler *at all* it would presumably just crash.

**Comment by int-72h** [comment]
> I was using the latest version of godot-cpp in both instances (as that's what the example project does). The build of 4.3.stable was obtained from the Arch Linux repos, the 4.2.2.stable build from the archive.
> 
> I'll try testing this with 4.3.stable from the archive as well, but I don't believe this is a config issue since an exception is thrown in both cases, if there wasn't an exception handler _at all_ it would presumably just crash with zero mention of an exception.

I stand corrected. The version from the arch repository doesn't work, however the version from the godot repos works fine. Closing, reopening if it somehow turns out to be a godot bug.

**Comment by dsnopek** [comment]
The Godot package on Arch Linux is known to have some problems with GDExtension:

https://gitlab.archlinux.org/archlinux/packaging/packages/godot/-/issues/2

Folks have reported that using the official builds or their own custom builds of Godot seem to work fine.
