### ISSUE TITLE
Language binding problem

### ISSUE THREAD

**Issue by JustDooooIt** [godotengine/godot-cpp#1578]
### Godot version

4.3.stable

### godot-cpp version

4.3.stable

### System information

windows 11

### Issue description

After using this method, the editor cannot detach the script and modify the visibility should be related to the implementation of GDExtensionScriptInstanceInfo3
![436c41cf926de932afdd4dfcaa720e9](https://github.com/user-attachments/assets/9f889584-c8c8-43cd-af27-43b751f579f5)

### Steps to reproduce

create instance_info and script_instance

### Minimal reproduction project

[test.zip](https://github.com/user-attachments/files/16972542/test.zip)

**Comment by Ivorforce** [comment]
Hi @JustDooooIt, can you explain the reason behind closing this issue?

**Comment by JustDooooIt** [comment]
@Ivorforce This issue has been resolved.Implementing `call_func` will suffice.
