### ISSUE TITLE
Possible bug with CMake and visual studio release type

### ISSUE THREAD

**Issue by enetheru** [godotengine/godot-cpp#1582]
### Godot version

-

### godot-cpp version

master

### System information

github ci

### Issue description

I pulled the build logs from the github ci, 🏁 Build (Windows, MSVC, CMake)
cmake command is 'cmake -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" .' but the visual studio build command has this in it: '/p:Configuration=Debug' is this a bug? I'm unfamilar with msvc
I'm submitting this so that it doesnt get lost, and can be reviewed by someone familiar with msvc

### Steps to reproduce

review the ci logs

### Minimal reproduction project

Release build of godot-cpp using CMake and Visual Studio

**Comment by enetheru** [comment]
I found the [answer](https://stackoverflow.com/questions/19024259/how-to-change-the-build-type-to-release-mode-in-cmake)

Visual Studio projects are multi-config projects like Ninja-MultiConfig which means you can't set the configuration at configure time as there are multiple, it always chooses the first one by default when not specified in the build command.

```shell
# Instead of this:
cmake -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 17 2022" .
cmake --build . --verbose
# It should be this
cmake -G"Visual Studio 17 2022" .
cmake --build . --verbose --config Release
```

**Comment by dsnopek** [comment]
Now that you've figured out what's going on with this, do we still need this issue? Or, is this something you think we should document somewhere?

**Comment by enetheru** [comment]
If there are build instructions please point me in their direction and I'll
update them.

**Comment by dsnopek** [comment]
I guess there's your build instructions in PR #1595?

**Comment by enetheru** [comment]
Those were simply what existed as comments just moved to an appropriate
location. Will likely require a rewrite sometime soon.
