### ISSUE TITLE
Include binaries or have binaries downloadable for somewhere

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot-cpp#159]
Once the binaries are build they pretty much become static, especially for the main release. It would be great if we make precompiled binaries available somehow for all the major platforms. This way someone who wants to build GDNative modules but doesn't want to use scons/python but just build something with their own build system, can just grab the binaries. 

Maybe see if Hugo is willing/interested on adding the master and 3.0 branch of this repo to his nightly build scripts?

**Comment by karroffel** [comment]
There are some binaries on the release pages here, but they aren't updated very often. Maybe we can add a CI that automatically creates nightly releases and also proper ones when we add tags or so?

**Comment by fire** [comment]
I have an idea how to do this, but will test this on my system before making it work on Travis.

**Comment by fire** [comment]
Concept: Take your generic ci system and use gothub to upload to the releases.

**Comment by Calinou** [comment]
I looked into doing this last year, but I don't think providing precompiled static libraries of godot-cpp makes sense. Many people would prefer not checking compiled code into version control. Think of the ABI incompatibilities that can stem from using libraries compiled with different compilers too.

**Comment by Calinou** [comment]
Pre-compiled static librarie are
 now provided with [GitHub Actions](https://github.com/godotengine/godot-cpp/actions), closing.
