### ISSUE TITLE
Wrong function conversion from Euler to Quaternion

### ISSUE THREAD

**Issue by fire** [godotengine/godot-cpp#1629]
### Godot version

Not in godot master.

### godot-cpp version

https://github.com/godotengine/godot-cpp/commit/a98d41f62bdb8b7aa903e8e37c1faa48fe8fdae8

### System information

Macos, m2 mac mini

### Issue description

Quaternion::Quaternion(const Vector3 &p_euler); https://github.com/godotengine/godot-cpp/blob/master/src/variant/quaternion.cpp#L335

Does not properly implement all 6 conversion or let the developer choose the rotation order. https://github.com/godotengine/godot/blob/master/core/math/basis.cpp#L457

This function was purposely left out of Quaternion because the math for this would be duplicated. I would recommend converting from basis as a wrapper.

### Steps to reproduce

Code review.

### Minimal reproduction project

The reproduction steps are by code review.

**Comment by dsnopek** [comment]
If I'm understanding correctly, you're saying that godot-cpp has this `Quaternion::Quaternion(const Vector3 &p_euler)` constructor, which Godot itself purposefully doesn't have?

We want to have compatibility with Godot, so assuming I'm understanding correctly, I think it makes sense to remove that construct from godot-cpp.

I don't know if the `Quaternion` class in godot-cpp has any other differences from the one in Godot, but if so, it would be good to rectify that as well.

**Comment by fire** [comment]
I can verify that this constructor does not exist in the latest Quaternion class.

https://docs.godotengine.org/en/latest/classes/class_quaternion.html

![image](https://github.com/user-attachments/assets/4635e7c0-2d54-4811-a2b4-e7d254b79a03)

**Comment by fire** [comment]
> I think it makes sense to remove that construct from godot-cpp.

I agree.
