### ISSUE TITLE
Godot-CPP think GDExtension built for Godot 4.4?

### ISSUE THREAD

**Issue by SentimeterGG** [godotengine/godot-cpp#1643]
### Godot version

4.3.stable

### godot-cpp version

4.3.stable

### System information

Arch Linux

### Issue description

To identify the source of the issue, I traced the error to `godot-cpp/src/godot.cpp`, specifically at line 323. I then modified the `godot.cpp` file to address the version compatibility check. from this:

```cpp
if (!compatible) {
    // We need to use snprintf() here because vformat() uses Variant, and we haven't loaded
    // the GDExtension interface far enough to use Variants yet.
    char msg[128];
    snprintf(msg, 128, "Cannot load a GDExtension built for Godot %d.%d.%d using an older version of Godot (%d.%d.%d).",
             GODOT_VERSION_MAJOR, GODOT_VERSION_MINOR, GODOT_VERSION_PATCH,
             internal::godot_version.major, internal::godot_version.minor, internal::godot_version.patch);
    ERR_PRINT_EARLY(msg);
    return false;
}
```

I modified it to the following:

```cpp
if (!compatible) {
    // Using snprintf() here because vformat() relies on Variant, which is unavailable at this stage
    // of the GDExtension interface initialization.
    char msg[128];
    snprintf(msg, 128, "Cannot load a GDExtension built for Godot %d.%d.%d using an older version of Godot (%d.%d.%d). (Its A Bug.)",
             GODOT_VERSION_MAJOR, GODOT_VERSION_MINOR, GODOT_VERSION_PATCH,
             internal::godot_version.major, internal::godot_version.minor, internal::godot_version.patch);
    ERR_PRINT_EARLY(msg);
    return true;
}
```

This changes bypass the checking and forces the GDExtensions to be run
I’m not sure if this is a bug or if I might be mistaken. so i put it in here

### Steps to reproduce

create a new project using godot-cpp version 4.3.stable

### Minimal reproduction project

N/A

**Comment by Ivorforce** [comment]
I have no issues with the 4.3 branch (56571dc584ee7d14919996c6d58fb5b35e64af63). Can you post the exact commit hash you're on? Ideally, please provide a reproduction project where the issue occurs.

**Comment by SentimeterGG** [comment]
Sorry for Late Answer
### ENVIRONMENT DETAILS:
- **Godot Version:**
```
[user@archlinux] godot --version
4.3.stable.arch_linux
```
- **Godot-CPP Commit Hash**
Godot-CPP 4.3 ([56571dc](https://github.com/godotengine/godot-cpp/commit/56571dc584ee7d14919996c6d58fb5b35e64af63))

---

### **STEP TO REPRODUCE:**
1. clone this repository [ARCameraOpenCV](https://github.com/SentimeterGG/ARCameraOpenCV) (I still used the gdexample code)
2. navigate to `godot-cpp/src/godot.cpp`
3. Modify the code at line 323
    - **Before:**
    ```cpp
	// Original Code:
	// if (!compatible) {
	// 	// We need to use snprintf() here because vformat() uses Variant, and we haven't loaded
	// 	// the GDExtension interface far enough to use Variants yet.
	// 	char msg[128];
	// 	snprintf(msg, 128, "Cannot load a GDExtension built for Godot %d.%d.%d using an older version of Godot (%d.%d.%d)",
	// 			GODOT_VERSION_MAJOR, GODOT_VERSION_MINOR, GODOT_VERSION_PATCH,
	// 			internal::godot_version.major, internal::godot_version.minor, internal::godot_version.patch);
	// 	ERR_PRINT_EARLY(msg);
	// 	return false;
	// }
	//Modified Code:
	if (!compatible) {
		// We need to use snprintf() here because vformat() uses Variant, and we haven't loaded
		// the GDExtension interface far enough to use Variants yet.
		char msg[128];
		snprintf(msg, 128, "Cannot load a GDExtension built for Godot %d.%d.%d using an older version of Godot (%d.%d.%d). (Its A Bug)",
				GODOT_VERSION_MAJOR, GODOT_VERSION_MINOR, GODOT_VERSION_PATCH,
				internal::godot_version.major, internal::godot_version.minor, internal::godot_version.patch);
		ERR_PRINT_EARLY(msg);
		return true;
	}
    ```
    - **After:**
    ```cpp
	// Original Code:
	if (!compatible) {
		// We need to use snprintf() here because vformat() uses Variant, and we haven't loaded
		// the GDExtension interface far enough to use Variants yet.
		char msg[128];
		snprintf(msg, 128, "Cannot load a GDExtension built for Godot %d.%d.%d using an older version of Godot (%d.%d.%d)",
				GODOT_VERSION_MAJOR, GODOT_VERSION_MINOR, GODOT_VERSION_PATCH,
				internal::godot_version.major, internal::godot_version.minor, internal::godot_version.patch);
		ERR_PRINT_EARLY(msg);
		return false;
	}
	// //Modified Code:
	// if (!compatible) {
	// 	// We need to use snprintf() here because vformat() uses Variant, and we haven't loaded
	// 	// the GDExtension interface far enough to use Variants yet.
	// 	char msg[128];
	// 	snprintf(msg, 128, "Cannot load a GDExtension built for Godot %d.%d.%d using an older version of Godot (%d.%d.%d). (Its A Bug)",
	// 			GODOT_VERSION_MAJOR, GODOT_VERSION_MINOR, GODOT_VERSION_PATCH,
	// 			internal::godot_version.major, internal::godot_version.minor, internal::godot_version.patch);
	// 	ERR_PRINT_EARLY(msg);
	// 	return true;
	// }

    ```

4. Open the project located in the demo folder using Godot.

---
Now, you should see this error
`Cannot load a GDExtension built for Godot 4.4.0 using an older version of Godot (4.3.0).`

**Comment by Ivorforce** [comment]
Hi, I cloned your repository, built the gdextension with `scons platform=macos arch=x86_64 dev_build=yes`, added a macos entry to the `.gdextension` and was able to load the demo project. Are you sure you aren't using 4.4 bindings or something like that?

I'd also like to comment that a GDExtension project for OpenCV exists already (https://github.com/matt-s-clark/godot-gdextension-opencv). Perhaps you'd like to contribute to that project? That would probably save both of you some time :)

**Comment by SentimeterGG** [comment]
Thanks for helping
but i didn't use any 4.4 bindings i just followed the docs from godot [https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html](https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html)

but when i try create a new project again from scratch, now it works for some reason, and i didn't know why
steps that i just changed just:
1. use `git submodule add -b 4.3 https://github.com/godotengine/godot-cpp` instead `git clone -b 4.3 https://github.com/godotengine/godot-cpp`
2. use this `git submodule update --init` instead 'git submodule update --init --recursive'
3. on godot create new project, i changed version control metadata from **None** to **git**
and it works some for reason, **is this error related to git?**

---
and thanks for the GDExtension i appreciate it

**Comment by Ivorforce** [comment]
Alright, good to hear you got it working. It's hard to say why you ran into the problem in the first place, but perhaps you were running into remnants or caches of a 4.4 clone of some sorts, or of a custom bindings file. Though it's hard to say for sure.
Let us know if you run into any more issues (or indeed, the same issue again).
