### ISSUE TITLE
CLion + CMake constantly freezes

### ISSUE THREAD

**Issue by chriztheanvill** [godotengine/godot-cpp#1664]
### Godot version

4.3 Stable

### godot-cpp version

4.3

### System information

Godot v4.3.stable - Fedora Linux 41 (Container Image) - Wayland - Vulkan (Mobile) - dedicated AMD Radeon RX 6600 (RADV NAVI23) - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

Hi.

I am having issues with CLion + CMake + Godot-Cpp, just freezes. I talked with CLion support and try to help me, but its weird that only happens with Godot-Cpp, because with SDL2, Raylib, other libs works excellent CLion.
Also post it in reddit. One person answer that he has not issues, but he is using Windows.

This is my CMakeLists, looks like the new godot-cpp cmakelist is different.

[CMakeLists.txt](https://github.com/user-attachments/files/17993493/CMakeLists.txt)

I understand that might not be a godot-cpp problem.

### Steps to reproduce

Just using CLion, try to open a file, and just freezes.

### Minimal reproduction project

Happens with a new or advanced project.

**Comment by Ivorforce** [comment]
Hi, do you have CLion Nova activated? CLion is much more responsive with its new engine as opposed to classic.

**Comment by chriztheanvill** [comment]
> Hi, do you have CLion Nova activated? CLion is much more responsive with its new engine as opposed to classic.

Yes, its an excellent upgrade. I tried to disable it, but still.

**Comment by Ivorforce** [comment]
Ok, good. 
I use CLion as well and had similar issues, but mostly only in the classic engine. Nova is OK for me. But I use SCons + `compile_commands.json`, not `CMake`. Tagging @enetheru if he has any idea.

**Comment by chriztheanvill** [comment]
> Ok, good. I use CLion as well and had similar issues, but mostly only in the classic engine. Nova is OK for me. But I use SCons + `compile_commands.json`, not `CMake`. Tagging [@enetheru](https://github.com/enetheru) if he has any idea.

Thank you so much :D

**Comment by enetheru** [comment]
I'm on my phone in a hotel right now so can't check exact. But in the gdscript module there is a file that is so macro heavy it freezes clion. I had to stub it out to work on my Tracy profiling code. Clion also provides some definitions you can use to stub the code.

When I get back to civilisation I can be more precise.

**Comment by enetheru** [comment]
The file that was causing me trouble was modules/gdscript/gdscript_vm.cpp

and I would use
```cpp
#if defined(__CLION_IDE__) || defined(__JETBRAINS_IDE__)
#endif
```
To stub out the content of `GDScriptFunction::call` where the macro madness lies.

I hope that helps.

**Comment by chriztheanvill** [comment]
> The file that was causing me trouble was modules/gdscript/gdscript_vm.cpp
> 
> and I would use
> 
> #if defined(__CLION_IDE__) || defined(__JETBRAINS_IDE__)
> 
> To stub out the content of `GDScriptFunction::call` where the macro madness lies.
> 
> I hope that helps.

Thanks for the answer, but, where is modules/gdscript/gdscript_vm.cpp and where should add that line.

**Comment by enetheru** [comment]
> Thanks for the answer, but, where is modules/gdscript/gdscript_vm.cpp and where should add that line.

Sorry I thought we were in godot source code for some reason. not godot-cpp I was not paying attention properly.

I have no idea then.

I havent had any issues with clion freezing. I've been working extensively on the cmake scripts and havent had any trouble.

Occasionally I might will make an infinite loop with cmake and have to figure that out, but there is nothing wrong with both clion and cmake.

**Comment by chriztheanvill** [comment]
> > Thanks for the answer, but, where is modules/gdscript/gdscript_vm.cpp and where should add that line.
> 
> Sorry I thought we were in godot source code for some reason. not godot-cpp I was not paying attention properly.
> 
> I have no idea then.
> 
> I havent had any issues with clion freezing. I've been working extensively on the cmake scripts and havent had any trouble.
> 
> Occasionally I might will make an infinite loop with cmake and have to figure that out, but there is nothing wrong with both clion and cmake.

Thanks, just moved the project to VSCode + CMake and everything works. Its weird, because using Clion with other projects works well.

**Comment by enetheru** [comment]
Sorry I'm being slow today, I finally get what you are asking.

You must be using the master branch, its being changed a lot by me recently, sorry about that. But the old stuff was so horrible that you've been having to basically re-write it every time.

You're CMakeLists.txt does heaps that it no longer needs to since the changes I've been making have been merged, it will need an overhaul your cmakelists.txt to remove all the setting of flags manually.

here's an example of how much simpler it is now.
```cmake
cmake_minimum_required( VERSION 3.17 )
project( godot-cpp-test
        VERSION 0.0.0
        DESCRIPTION ""
        HOMEPAGE_URL ""
        LANGUAGES CXX
)

include( FetchContent )

FetchContent_Declare( godot-cpp
        GIT_REPOSITORY https://github.com/enetheru/godot-cpp.git
        GIT_TAG "fix_crt_debug"
        SYSTEM
        EXCLUDE_FROM_ALL
)

FetchContent_MakeAvailable( godot-cpp )

# Testing Extension
# This is only linked to the template_release config.
# so it requires the template_release version of godot to run.

add_library( test SHARED )

target_sources( test
        PRIVATE
        src/example.cpp
        src/example.h
        src/register_types.cpp
        src/register_types.h
        src/tests.h
)

set( TEST_TARGET "template_debug" CACHE STRING "Which godot-cpp::target to link against" )
set_property( CACHE TEST_TARGET PROPERTY STRINGS "template_debug;template_release;editor" )

target_link_libraries( test
        PRIVATE
        godot-cpp::${TEST_TARGET} )

### Get useful properties of the library
get_target_property( GODOT_PLATFORM godot-cpp::${TEST_TARGET} GODOT_PLATFORM )
get_target_property( GODOT_TARGET godot-cpp::${TEST_TARGET} GODOT_TARGET )
get_target_property( GODOT_ARCH godot-cpp::${TEST_TARGET} GODOT_ARCH )

set( OUTPUT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/project/bin/" )

set_target_properties( test
        PROPERTIES
        CXX_STANDARD 17
        CXX_EXTENSIONS OFF
        CXX_VISIBILITY_PRESET ${GODOT_SYMBOL_VISIBILITY}

        POSITION_INDEPENDENT_CODE ON
        BUILD_RPATH_USE_ORIGIN ON
        LINK_SEARCH_START_STATIC ON
        LINK_SEARCH_END_STATIC ON

        # NOTE: Wrapping the output variables inside a generator expression
        # prevents msvc generator from adding addition Config Directories
        LIBRARY_OUTPUT_DIRECTORY "$<1:${OUTPUT_DIR}>"
        RUNTIME_OUTPUT_DIRECTORY "$<1:${OUTPUT_DIR}>"
        PDB_OUTPUT_DIRECTORY     "$<1:${OUTPUT_DIR}>" #MSVC Only, ignored on other platforms

        PREFIX "lib"
        OUTPUT_NAME "gdexample.${GODOT_PLATFORM}.${GODOT_TARGET}.${GODOT_ARCH}"
)

if( CMAKE_SYSTEM_NAME STREQUAL Darwin )
    get_target_property( OSX_ARCH godot-cpp::${TEST_TARGET} OSX_ARCHITECTURES )

    set( OUTPUT_DIR "${OUTPUT_DIR}/libgdexample.macos.${TEST_TARGET}.framework")

    set_target_properties( test
            PROPERTIES
            LIBRARY_OUTPUT_DIRECTORY "$<1:${OUTPUT_DIR}>"
            RUNTIME_OUTPUT_DIRECTORY "$<1:${OUTPUT_DIR}>"

            OUTPUT_NAME "gdexample.macos.${TEST_TARGET}"
            SUFFIX ""

            #macos options
            OSX_ARCHITECTURES "${OSX_ARCH}"
    )
endif ()

```

**Comment by enetheru** [comment]
Today is one of those days, you've specified that you are working on 4.3-stable. disregard previous comment

**Comment by chriztheanvill** [comment]
Could I share my project ?

**Comment by enetheru** [comment]
> Could I share my project ? Its in early stage.

Yes please, then I can see if it crashes for me, perhaps figure out why for you.

**Comment by chriztheanvill** [comment]
[Archive.tar.gz](https://github.com/user-attachments/files/18015612/Archive.tar.gz)

I omitted the Assets folder. 

Thank you so much :D

**Comment by enetheru** [comment]
I'll just give a rundown of what I've experienced.

I'm using CLion 2024.3 on Windows 11
No crash on load, but I'm missing conan, so installed through winget.
Closed and re-opened project, reset cache and reload CMake Solution.
My default toolchain is Msys2-ucrt64-gcc, so mixed it up with Msys2-clang64-clang, all good on the configure.
changed it to msvc, and it fails due to "	ConanException: The provided compiler.cppstd=gnu23 is not supported by msvc 194. Supported values are: ['14', '17', '20', '23']" and also cant find sqlite, but no crash
Configures even with llvm-mingw-w64, and mingw64 compiler variants.

Oh weird, ok so I didnt notice that the place it expected godot-cpp to be was '../../godot-cpp' , lets change that to where I actually have it.

reset-cache, reconfigure, and compiling, build failed at link stage, thats simply because I dont have a libgodot-cpp in the expected folder.

I can browse around, open files, sorry, but no problems can be detected.

**Comment by enetheru** [comment]
also double checked with the builtin clion toolchain just incase.. no problem.

**Comment by chriztheanvill** [comment]
> also double checked with the builtin clion toolchain just incase.. no problem.

This is what it happens to me:

- Open the project
- At first works excellent CLion, but after trying to open some files (at least 10 - 20 files, no matter if all files are opened or closed, just needs to be opened once), just freezes.
- In the image: 

1. Try to open all the files in the Utils folder, then close them.
2. Then try to open from GUIMenu to GUIPopSelectItems
    - Note: No matter if all the files are opened or closed, open and close, just try to open.

In my case, after open GuiObjectInfo.hpp or .cpp ( at least 20 files, no matter if all are opened or closed, just need to be opened once ), clion freezes.

Its weird, because I have other projects with SDL2, Raylib in CLion + CMake + Conan and I can open tons of files, close them and works. Note: I prefer to only have 4 or 5 files / tabs open.

- ![Image](https://github.com/user-attachments/assets/f949891e-81aa-422d-8a1e-df8b4503c83a)

**Comment by enetheru** [comment]
OK so I have managed to get it to halt, similar to my other issue with godot engine source it's waiting for clangd for something.

killing clangd breaks the waiting and revives clion, but it will just happen again soon after.
So it might not even be a CLion issue either, but a clangd issue. 

Clion does give me an option to dump threads using CTRL+D after a bit and it gives me a report. That might be handy to send to Jetbrains, but their bug tracker moves slowly(I know because I've got active bugs), i understand that they are a commercial company and need to choose where to spend their money to stay profitable.

So while I've confirmed that that its definitely experienced by at  least one other person it's not godot-cpp's issue to resolve, and might not even be CLion's issue to resolve.

You should close this bug report, refer to it in any report you have with Jetbrains, and search for similar issues with clangd.

**Comment by chriztheanvill** [comment]
> OK so I have managed to get it to halt, similar to my other issue with godot engine source it's waiting for clangd for something.
> 
> killing clangd breaks the waiting and revives clion, but it will just happen again soon after. So it might not even be a CLion issue either, but a clangd issue.
> 
> Clion does give me an option to dump threads using CTRL+D after a bit and it gives me a report. That might be handy to send to Jetbrains, but their bug tracker moves slowly(I know because I've got active bugs), i understand that they are a commercial company and need to choose where to spend their money to stay profitable.
> 
> So while I've confirmed that that its definitely experienced by at least one other person it's not godot-cpp's issue to resolve, and might not even be CLion's issue to resolve.
> 
> You should close this bug report, refer to it in any report you have with Jetbrains, and search for similar issues with clangd.

Thank you. I don't have the option to dump threads Ctrl + D.

**Comment by enetheru** [comment]
> Thank you. I don't have the option to dump threads Ctrl + D.

it didnt appear straight away, more like going back and forth from other windows eventually raised it.

**Comment by chriztheanvill** [comment]
Thank you.

**Comment by chriztheanvill** [comment]
> OK so I have managed to get it to halt, similar to my other issue with godot engine source it's waiting for clangd for something.
> 
> killing clangd breaks the waiting and revives clion, but it will just happen again soon after. So it might not even be a CLion issue either, but a clangd issue.
> 
> Clion does give me an option to dump threads using CTRL+D after a bit and it gives me a report. That might be handy to send to Jetbrains, but their bug tracker moves slowly(I know because I've got active bugs), i understand that they are a commercial company and need to choose where to spend their money to stay profitable.
> 
> So while I've confirmed that that its definitely experienced by at least one other person it's not godot-cpp's issue to resolve, and might not even be CLion's issue to resolve.
> 
> You should close this bug report, refer to it in any report you have with Jetbrains, and search for similar issues with clangd.

I have the project in VS Code and works excellent, but I tried with QtCreator and looks like tries to index 

![Image](https://github.com/user-attachments/assets/8e7adf5b-0962-4ca6-abc9-6f424aef57ab)

I think if should I have in CMake disable to look in godot-cpp or add it to the project.
