### ISSUE TITLE
CMake: 4.3 _bind_methods throws exception

### ISSUE THREAD

**Issue by LouChiSoft** [godotengine/godot-cpp#1667]
### Godot version

4.3-stable

### godot-cpp version

godot-4.3-stable

### System information

Windows 10, R9 7900, RX 7900XT

### Issue description

When using CMake to build a GDExtension, and using FetchContent to depend on godot-cpp, Godot will throw an exception when attempting to bind a function in _bind_method

### Steps to reproduce

- Clone repository (link below)
- Run `cmake -B ./build` (if using a single config generator, append -DCMAKE_BUILD_TYPE=Debug)
- Run `cmake --build ./build`
- Use Godot v4.3-stable to run the the project found the `./demo/`

Note: Both the version of Godot and the gdextension was made using a double precision build

### Minimal reproduction project

 Repository here: https://github.com/LouChiSoft/GDExtension-Template

**Comment by dsnopek** [comment]
Thanks!

So, are you saying that using `scons` won't lead to an exception, but using `cmake` will? What is the exception - "access violation" (aka segfault in non-Windows terms)?

You write:

```
Note: Both the version of Godot and the gdextension was made using a double precision build
```

... but looking at the build commands given above, you don't appear to be compiling for double precision:

> * Run `cmake -B ./build` (if using a single config generator, append -DCMAKE_BUILD_TYPE=Debug)
> * Run `cmake --build ./build`

I would have expected `-DGODOT_PRECISION=double` to be included there, as well as a custom `extension_api.json` via `-DGODOT_CUSTOM_API_FILE=...`.

If you don't try to use double precision, does the problem still occur?

**Comment by LouChiSoft** [comment]
> but looking at the build commands given above, you don't appear to be compiling for double precision:

So I have a function in my main CMakeLists.txt file that handles the FetchContent for godot-cpp:
```
#[[
    get_and_link_godot_cpp uses FetchContent to download godot-cpp
    from github, include it's CMakeList and link it to a target
    Variables:
    --- TARGET: target name
    --- TAG: Tag or Branch to checkout when linking godot-cpp 
    --- PRECISION: Floating point precision. Valid arguments: SINGLE, DOUBLE
    ]]
    get_and_link_godot_cpp(
        ${PROJECT_NAME} 
        godot-4.3-stable
        "DOUBLE"
    )
```
Here I pass "DOUBLE" and that is passed to the FetchContent command that corresponds to this line found in godot-cpp's CMakeLists.txt:
 `FLOAT_PRECISION:				Floating-point precision level ("single", "double")`

About the extensions_api.json. Does the one included in godt-cpp on the `godot-4.3-stable` branch not match the output of what a `4.3-stable` dump would have produced? I'd have assumed the that those sync up together. Also does the double precision affect the extension api? I thought it was a purely internal change

**Comment by LouChiSoft** [comment]
A couple of updates:
- There was a code gen bug that I accidentally pushed when cleaning up my code for submitting this report. They have been fixed so you might need to pull main again
- I noticed that I was using all caps for the precision instead of lower case like the CMake file lists. That has been changed.
- If I "run" the project through CLion instead of `debug`, then I get an access violation pop up box, and pressing retry on that box gets me this error message:
```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.3.stable.custom_build (77dcf97d82cbfe4e4615475fa52ca03da645dbd8)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```

**Comment by LouChiSoft** [comment]
> Yes, Godot built for double precision will generate a different extension_api.json.
So assuming that I passed the file location to the FetchContent command correctly, then the I still have the same issue using the extension_api.json file that was output from `godot --dump-extension-api`

Building with single precision and using the included extension_api.json file works as intended. So it seems related to double precision somehow

**Comment by LouChiSoft** [comment]
I think I narrowed it down. I tried double precision with Scons and I noticed that at the very top there was `Built-in type config: double_64` in my CMake project it is `Built-in type config: float_64` which to me indicates that it's not respecting the floating point precision definition.

This is the function that grabs and links godot-cpp
```
function(get_and_link_godot_cpp TARGET TAG PRECISION EXTENSION_FILE)
    include(FetchContent)

    FetchContent_Declare(
        godot-cpp
        GIT_REPOSITORY https://github.com/godotengine/godot-cpp.git
        GIT_TAG ${TAG}
        GIT_SUBMODULES_RECURSE 1
        # Provide any configuration options you want, for instance:
        CMAKE_ARGS
            -DGODOT_CPP_SYSTEM_HEADERS=ON
            -DGODOT_CPP_WARNING_AS_ERROR=OFF
            -DGENERATE_TEMPLATE_GET_NODE=ON
            -DFLOAT_PRECISION="double"
            -DGODOT_CUSTOM_API_FILE=${EXTENSION_FILE}
    )

    FetchContent_MakeAvailable(godot-cpp)

    set_target_properties(godot-cpp PROPERTIES
        CXX_VISIBILITY_PRESET hidden
        VISIBILITY_INLINES_HIDDEN ON
    )
    # Turn on LTO and export compile commands for VSCode to use
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)
    set(CMAKE_EXPORT_COMPILE_COMMANDS ON) # WARNING: On Windows, this flag has no effect for Visual Studio generators. Ninja or Ninja Multi-Config is recommended

    target_link_libraries(${TARGET} PRIVATE godot-cpp)

endfunction()
```

To test I hardcoded it to "double" which is what the CMake file says should be enough to mark it as double precision. But it's still coming up as a float_64

**Comment by LouChiSoft** [comment]
Found the issue. FetchContent doesn't work the same way as ExternalProject and silently ignores CMAKE_ARGS. Moving the defines to before the FetchContent call as saving them as CACHE INTERNAL variables fixes the issue. Sorry to waste your time
