### ISSUE TITLE
Linux binaries are too big

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot-cpp#300]
When I compile on Linux the binaries and my GDNative library are too big(over 60mb), but Windows binaries are very small, how can I fix this?.

**Comment by MightyPrinny** [comment]
I removed the -g flag from SConstruct that made the binaries about 5mb, still bigger than on windows but much smaller than before

**Comment by MightyPrinny** [comment]
The smaller binaries don't seem to work

**Comment by beniwtv** [comment]
I ran into the same problem - removing "-g" helped, and puts it as 6,9 MB.

**Comment by TGRCdev** [comment]
Adding `-s` to g++ link flags will strip unused symbols. This works for resulting GDNative libraries, but I'm not sure if it would make godot-cpp libs unusable.

**Comment by ngasull** [comment]
:wave: +1 to this issue

1. First I was very surprised that `godot-cpp`'s "release" build had debugging symbols, resulting is a  39MB hello world library. **Using `-g` shrinks the lib size down to 3.2MB** which is much more reasonable, but not ideal yet.
2. Then, I think **there must be a way to avoid compiling so much base code in every lib**. This could be done by only using the required parts of the lib or by having a shared lib that bridges native code to Godot engine. The latter sounds much cleaner and efficient.

What do you think?

**Comment by superRaptor911** [comment]
> wave +1 to this issue
> 
>     1. First I was very surprised that `godot-cpp`'s "release" build had debugging symbols, resulting is a  39MB hello world library. **Removing `-g` shrinks the lib size down to 3.2MB** which is much more reasonable, but not ideal yet.
> 
>     2. Then, I think **there must be a way to avoid compiling so much base code in every lib**. This could be done by only using the required parts of the lib or by having a shared lib that bridges native code to Godot engine. The latter sounds much cleaner and efficient.
> 
> 
> What do you think?

can we use -s flag?

**Comment by Zylann** [comment]
Ran into this as well. I think the `-g` should be removed from both SConstruct files (cpp bindings and your own projects) when compiling for release. I don't know if `-s` is still needed. If I understand correctly this would be a flag to add only to your own projects?
