### ISSUE TITLE
SConstruct build error on Windows

### ISSUE THREAD

**Issue by mdahlgrengadd** [godotengine/godot-cpp#308]
Getting error when generating bindings
```
c:\GitHub\gdnative_cpp_example\godot-cpp>scons P=windows bits=64 generate_bindings=yes use_custom_api_file=yes custom_api_file=../api.json
scons: Reading SConscript files ...
  File "C:\GitHub\gdnative_cpp_example\godot-cpp\SConstruct", line 41

    print "Unknown variables:", unknown.keys()

                             ^

SyntaxError: invalid syntax
```

Commenting out those lines does work, but probably they are important for something else :-)

**Comment by piiertho** [comment]
Hi there !

If you only want to generate bindings `use_custom_api_file=yes custom_api_file=../api.json` should not be there.
Use `scons godotbinpath="path to your godot executable" platform=windows generate_bindings=yes bits=64 target=release(or debug, depending what you want)` instead.

**Comment by mdahlgrengadd** [comment]
Thanks, but I need the new audio generator API which is not in there yet.

**Comment by Immac** [comment]
> Commenting out those lines does work, but probably they are important for something else :-)

This is because print <arg> is not valid python3 syntax, this works.

![image](https://user-images.githubusercontent.com/3265190/70731879-1a19e700-1ccd-11ea-8e2a-7ececf3da63b.png)

**Comment by Zylann** [comment]
Is this still an issue? I can't find the code anymore.

**Comment by Faless** [comment]
Closing as fixed, since that code seems long gone.
