### ISSUE TITLE
Error building library for Windows from Linux

### ISSUE THREAD

**Issue by DuncanSparks** [godotengine/godot-cpp#313]
I'm on Arch Linux and compiling my library for Linux works fine. However, I'm getting this error when trying to compile for Windows:
```
[duncan@duncan-linux CPPTest2]$ scons platform=windows
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/Controller.os -c -DWIN32 -D_WIN32 -D_WINDOWS -W3 -GR -D_CRT_SECURE_NO_WARNINGS -EHsc -D_DEBUG -MDd -fPIC -I. -Igodot-cpp/godot_headers -Igodot-cpp/include -Igodot-cpp/include/core -Igodot-cpp/include/gen -Isrc src/Controller.cpp
g++: error: unrecognized command line option ‘-W3’; did you mean ‘-W’?
g++: error: unrecognized command line option ‘-GR’; did you mean ‘-R’?
g++: error: unrecognized command line option ‘-EHsc’
g++: error: unrecognized command line option ‘-MDd’; did you mean ‘-MD’?
scons: *** [src/Controller.os] Error 1
scons: building terminated because of errors.
```
I have mingw-w64-gcc installed, but that isn't making any difference. I'm using the SConstruct file that comes with [the example project](https://docs.godotengine.org/en/3.1/tutorials/plugins/gdnative/gdnative-cpp-example.html), and there's nothing in it referencing MinGW. Do I need to modify it in any way to get it to work?

**Comment by 2shady4u** [comment]
mmmh sthis should work.

Did you check this discussion/Pr? https://github.com/GodotNativeTools/godot-cpp/pull/295

**Comment by loksangho** [comment]
I'm on OS X, and experiencing similar issues while trying to use scons on the example project. The godot-cpp library compiles successfully for all three platforms (windows, linux, OS X), just not the example project when compiling for windows. Compiling for OSX and Linux is successful.

**Comment by DanielKinsman** [comment]
@DuncanSparks can this be closed now? I'm guessing this is an old issue you have since fixed, as there is now a `use_mingw=yes` flag for the SConstruct and your recent commit (5c96e5ede5dd9adf0c744c9a425ecb0fc2a2729c) fixed the subsequent include errors for me.

**Comment by DuncanSparks** [comment]
@DanielKinsman Ah, yeah, sorry about that. This can be closed now.
