### ISSUE TITLE
Setting the basis and origin separately for Spatial class

### ISSUE THREAD

**Issue by noobaldrin** [godotengine/godot-cpp#317]
Let's say for example I have: 

`Basis B;`
`Vector3 O; // origin`
`Spatial S;`

Normally I would set the transform like this for Spatial S:

`S.set_global_transform( Transform( B,  O));`

**Here's my question:**
What if I want to change the basis only and not the origin? (or vice versa)

`// Not working: Won't change the basis`
`S.get_global_transform().basis = B;`
`// Not working: Won't change the origin`
`S.get_global_transform().origin = O;`

This is what I'm currently doing that works:
`// Changes the basis only and retains the origin`
`S.set_global_transform( Transform( B, S.get_global_transform().get_origin));`
`// Changes the origin and retains the basis`
`S.set_global_transform(Transform( S.get_global_transform().get_basis(), O));`

How do you guys actually do this?
Would it be a bad idea to have `set_basis()` and `set_origin()` methods for Spatial class?

**Comment by 2shady4u** [comment]
The Spatial class is not directly implemented in godot-cpp (as seen in the source of this repo)
And I also don't think its a good idea to add getters and setters for a property (=transform) of Spatial. Instead this problem should be tackled directly in Transform.cpp.
 
As found in Transform.cpp 

![Capture](https://user-images.githubusercontent.com/42484461/62411504-11652600-b5f4-11e9-8890-1c31ab92c659.PNG)

So both the basis and origin are public properties and should be modifiable by outside scripts.

What is your error? Does it crash? What is the crash message?

**Comment by noobaldrin** [comment]
I actually wanted to do it like this:

`// Not working: Won't change the basis`
`S.get_global_transform().basis = B;`
`// Not working: Won't change the origin`
`S.get_global_transform().origin = O;`

No I don't get any crashes, it just doesn't work correctly.
I'm expecting this:

`S.get_global_transform().basis = B;`
`S.get_global_transform().origin = O;`

and this:

`S.set_global_transform( Transform( B, S.get_global_transform().get_origin));`
`S.set_global_transform(Transform( S.get_global_transform().get_basis(), O));`

Should have the same effect although the latter set of codes does it differently.

I'm going to create a minimal project to check this.

**Comment by Zylann** [comment]
The underlying NativeScript API can only use `get_global_transform()` and `set_global_transform()`. That means it's all, or nothing. In any case, you have to get the whole transform, and set the whole transform.

In GDScript it looks like it works to set the basis, but in reality it's syntactic sugar from the language, which still does a full transform set behind the scenes.

Generated C++ bindings can't automagically "hide" this, the same way you can't do `get_translation().x = 42`, or even `get_transform().origin.y = 0.0`. Same story here.

**Comment by BastiaanOlij** [comment]
Keep in mind that `global_transform` does not exist. It's a calculated value, a copy of which is stored for convenience. It's basically all transforms of all parent nodes of your node multiplied together.

When you change the global transform it will take the inverse of the global transform of the parent node, multiply with the global transform you supply, and store the result as the transform of that node, which is the real value being maintained.

Giving direct access to the basis therefor doesn't actually do anything different in the background. It is still getting the transform, updating the basis, and calling the setter again to kick off all the logic above.

**Comment by noobaldrin** [comment]
Thanks for explaining. So it was something I've missed and that makes a lot of sense.
Although I can't remember when did I stop working on my project cause of busy schedule, I hope to get back to playing with godot engine soon.

I'm closing this one "issue" now.
