### ISSUE TITLE
Generation of android bindings fails due to "/nologo"-flag

### ISSUE THREAD

**Issue by 2shady4u** [godotengine/godot-cpp#361]
Generation of android bindings, using the latest master branch, fails due to Scons adding a "/nologo"-flag that shouldn't be there...

![Capture](https://user-images.githubusercontent.com/42484461/71452797-3f582c00-2788-11ea-87b9-1c950dcdb50b.PNG)

**EDIT** (without the use_mingw-flag):
![Capture](https://user-images.githubusercontent.com/42484461/71472085-02b12280-27d2-11ea-8d6d-c224ac9fbb48.PNG)

**Versions:**
- I'm using Windows 10 with Powershell
- Scons 3.0.1 (from Scoop)
- NDK r20b
- llvm 9.0.0 (from Scoop)

**Why does this happen?**
For some reason this flag is added with initializing the construction environment:
`env = Environment(ENV = os.environ)`
I have zero clue why this happens though...

**Temporary work-around:**
Explicitly removing the '/nologo'-flag from the env does the trick, like so:
![Capture](https://user-images.githubusercontent.com/42484461/71452766-0324cb80-2788-11ea-82be-9eb0f51929e2.PNG)
![Capture2](https://user-images.githubusercontent.com/42484461/71452771-0b7d0680-2788-11ea-928c-09905f1508cf.PNG)

Does anyone know what I am doing wrong? Or is this Scons' (or some other programs) fault?

**Comment by piiertho** [comment]
Hi ! 
Maybe I'm wrong, but I think nologo is the option to tell microsoft compiler to not display informations like version.
Try to remove use_mingw argument, to see if it changes anything.

**Comment by 2shady4u** [comment]
I'm not an expert in Scons so I don't really know (on an advanced) level how any of this works.
I'm not using any "use_mingw" arguments in my cmd in Powershell.

Commenting out the part about "mingw" in the SConstruct file, regarding android, crashes because the command's auto-generated flags are now totally wrong...

![Capture](https://user-images.githubusercontent.com/42484461/71470024-3c325f80-27cb-11ea-99f3-f2a1948eba12.PNG)

**Comment by piiertho** [comment]
On your first screen, the last command argument is use_mingw=yes

[Here](https://user-images.githubusercontent.com/42484461/71452797-3f582c00-2788-11ea-87b9-1c950dcdb50b.PNG)

**Comment by 2shady4u** [comment]
Apologies for some reason I included a picture that had this flag (because I was getting desperate and trying out all the flags), here is the same cmd crashing, but without the mingw-flag:

![Capture](https://user-images.githubusercontent.com/42484461/71472052-e4e3bd80-27d1-11ea-93c6-08e8cf4cb961.PNG)

**Comment by piiertho** [comment]
Hi !
As I am away from home I only have a macbook to test it.
From OSX there is no problem running `scons platform=android generate_bindings=yes ANDROID_NDK_ROOT="/Users/piertho/Library/android-sdks/ndk-bundle" android_arch=arm64v8`
I'll test on windows as soon as I come back home :)

**Comment by 2shady4u** [comment]
Just to get back to this: I am able to successfully build the necessary Android bindings on my Ubuntu VM without any issues.

This issue seems to be unique to Windows OS

**Comment by Zylann** [comment]
I can confirm `/nologo` (alone) is present on Windows 10 when the environment gets constructed, at https://github.com/GodotNativeTools/godot-cpp/blob/c2f765e49c7dd0c86729e6ba17f87c039203bce0/SConstruct#L148

**Comment by Zylann** [comment]
I made a small change in https://github.com/godotengine/godot-cpp/pull/501 to fix MinGW builds on Windows, let me know if that fixes things for you
