### ISSUE TITLE
Narrowing Conversion Warning in include/Vector2.hpp

### ISSUE THREAD

**Issue by BenjaminHinchliff** [godotengine/godot-cpp#385]
In Vector2.hpp the snapped method defined here:
```C++
inline Vector2 snapped(const Vector2 &p_by) const {
	return Vector2(
			p_by.x != 0 ? ::floor(x / p_by.x + 0.5) * p_by.x : x,
			p_by.y != 0 ? ::floor(y / p_by.y + 0.5) * p_by.y : y);
}
```

Has a narrowing conversion warning because 0.5 is a double, causing the result from `x / p_by.x` to be promoted to a double. This causes a narrowing conversion when it's passed into the Vector2's real_t (or float) parameter.

Assuming this isn't intended behavior (for some reason), this can be fixed very easily with either an explicit cast to real_t in the statement or by adding the float modifier to the 0.5 constant (shown below)

```C++
inline Vector2 snapped(const Vector2 &p_by) const {
	return Vector2(
			p_by.x != 0 ? ::floor(x / p_by.x + 0.5f) * p_by.x : x,
			p_by.y != 0 ? ::floor(y / p_by.y + 0.5f) * p_by.y : y);
}
```

**Comment by Zylann** [comment]
Another reason would be that `real_t` can be `double` (it is currently `float`), and to address this I thought C++ bindings should implement the missing `Math` functions, which contains implement `floor` for both `double` and `float`, choosing between `floorf` and `floor` at compile time https://github.com/GodotNativeTools/godot-cpp/issues/107#issuecomment-605355945

**Comment by SuniTheFish** [comment]
Yeah, in the end, I disabled it, but I thought it was a little weird. Thanks for taking the issue seriously.
