### ISSUE TITLE
Extend .gdns class

### ISSUE THREAD

**Issue by DaedricSpartan99** [godotengine/godot-cpp#390]
I'm trying to extend the `mycppnode` written in c++ inheriting the `godot::Node` class using this syntax in the gdscript:
`extend "res://bin/mycppnode.gdns"`
but it gives the following parse error:
```
res://myscript.gd:1 - Parse Error: Couldn't load the base class: res://bin/mycppnode.gdns
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 modules/gdscript/gdscript_tokenizer.cpp:1129 - Condition "tk_rb[ofs].type != TK_IDENTIFIER" is true. Returned: StringName()
```
When I simply extend a `Node` and assign the script using the gui it doesn't give any error.

**Comment by Zylann** [comment]
Are you able to `preload(res://bin/mycppnode.gdns` and use it in a test scene?

**Comment by Zylann** [comment]
Actually it looks like it's not supported, judging by this issue: https://github.com/GodotNativeTools/godot-cpp/issues/291

**Comment by BastiaanOlij** [comment]
I ran into this too, it's an annoying limitation...

**Comment by vnen** [comment]
This is a limitation of GDScript, so it should be opened in the Godot tracker. There's nothing to be done in godot-cpp
