### ISSUE TITLE
Is it possible to bind enum types?

### ISSUE THREAD

**Issue by DaedricSpartan99** [godotengine/godot-cpp#391]
Is there a way to bind an `enum class` type in gdnative?

**Comment by sheepandshepherd** [comment]
No, unfortunately.

You can still make a property an enum by using `GODOT_PROPERTY_HINT_ENUM` as hint and a comma-separated list of the enum member names as hint string.

```cpp
	register_property<GDExample, int>(
		"some_enum",
		&GDExample::set_enum,
		&GDExample::get_enum,
		GDExample::ENUM_A,
		GODOT_METHOD_RPC_MODE_DISABLED,
		GODOT_PROPERTY_USAGE_DEFAULT,
		GODOT_PROPERTY_HINT_ENUM,
		"ENUM_A, ENUM_B, ENUM_C"
	);
```

**Comment by DaedricSpartan99** [comment]
Ok cool :) thank you

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/15922, as this is a missing feature in Godot itself rather than the C++ binding.
