### ISSUE TITLE
MinGW tries to include alloca.h

### ISSUE THREAD

**Issue by DuncanSparks** [godotengine/godot-cpp#414]
MinGW seems to be trying to include `<alloca.h>` on all the platforms it's used on, which is making compilation of the bindings fail on both native Windows and when cross-compiling for Windows from Linux. This only happens after updating `Defs.hpp` with what was added in https://github.com/godotengine/godot-cpp/commit/165f1f30e875a4d4199529baeff3ba62bf4b7d11.
```cpp
#if defined(__linux__) || defined(__APPLE__) || defined(__MINGW32__)
#include <alloca.h>
#endif
```
I managed to fix the problem by changing it to the following:
```cpp
#if defined(__linux__) || defined(__APPLE__)
#include <alloca.h>
#else
#include <malloc.h>
#endif
```

**Comment by API-Beast** [comment]
Looks like MinGW now ships with a alloca.h and no longer defines alloca() in malloc.h, what a mess.
