### ISSUE TITLE
Vector2 struct does not contain move_toward implementation

### ISSUE THREAD

**Issue by Philosopho** [godotengine/godot-cpp#422]
Hi all, I am trying to use the method move_toward but it is not implemented in the struct, however in the gdnative/vector2.h it is declared there. Whenever I try to use it is unresolved. Everything else is working well and compiling though. Thank you!

**Comment by Zylann** [comment]
The way we implement `Vector2` in the bindings is to copy the implementation from the engine, as the GDNative function pointers would be slower and miss compiler optimization. The function should be added.

**Comment by Philosopho** [comment]
Hi Zylann, thank you for responding! I had a feeling I was using Vector2 incorrectly. Should I instantiate Vector2 another way to gain access to the move_toward method? This is how I instantiated it.
![move_toward unresolved](https://user-images.githubusercontent.com/17994918/87180018-b8931880-c2ad-11ea-83d7-79263f0c4c21.PNG)

The Vector2.hpp file I'm using from the bindings:
https://github.com/godotengine/godot-cpp/blob/master/include/core/Vector2.hpp

However, if I'm instantiating correctly, and we need to use the Struct Vector2, the master branch Vector2.hpp does not have move_toward in the link above. Thank you for your help again!

**Comment by Zylann** [comment]
You used it correctly. `move_towards` needs to be added to it.

**Comment by Philosopho** [comment]
Thanks Zylann! Any time frame of when it'll be added?
