### ISSUE TITLE
"StringName.hpp" not found.

### ISSUE THREAD

**Issue by juliotux** [godotengine/godot-cpp#428]
Hello everyone,

I'm trying to compile the godot bindings, however I get the following error:
```
src/gen/AnimationNodeAnimation.cpp:12:10: fatal error: StringName.hpp: No such file or directory
   12 | #include "StringName.hpp"
      |          ^~~~~~~~~~~~~~~~
```

It seems that the generation is not working properly...
How can I solve this?

**Comment by sheepandshepherd** [comment]
StringName wasn't exposed to the API until Godot 4.0. Is it possible you're using an API JSON generated by 4.0? Or does this also happen with the default API JSON in godot_headers?

My AnimationNodeAnimation.cpp generated from Godot's 3.2 branch doesn't have that line.

**Comment by juliotux** [comment]
I used the 4.0 API. However, after I check this resulted in compiled error, I returned to default (without clean) and the error remained. After clean the generated files, it worked.

**Comment by norton-corbett** [comment]
How can I generate bindings for Godot 4.0 classes? I'm not sure I understand how the generator works.

I was hoping to try opening my fairly large project with the Godot master branch to get an idea of how much work I'd need to do to upgrade when the time comes, but of course I'm roadblocked here.

I guess the process is to avoid adding new bindings altogether while the API is still in flux, but I'm wondering if it's trivial enough that I can just do it locally.

**Comment by sheepandshepherd** [comment]
It's not possible yet because part of the API, including StringName, needs to be manually ported to the GDNative bindings using the GDNative C API. The generator only handles classes that inherit Object, so it's missing StringName and the renamed core types (PackedArrays).

**Comment by Zylann** [comment]
Going to close this in favor of #449
