### ISSUE TITLE
Windows build fails to load DLL on another PC

### ISSUE THREAD

**Issue by SnailBones** [godotengine/godot-cpp#434]
Godot 3.2.2 stable (Also 3.2)

OS: Windows 10

I have a game that loads a GDNative C++ DLL. It compiles and runs fine on my computer, but testing it on multiple others, it crashes with the following error message:

![img_bug](https://user-images.githubusercontent.com/14878684/88739635-d7880c00-d0ef-11ea-8a91-be0b3f5e08f8.png)

My GDNS files are as follows:

```
[gd_resource type="NativeScript" load_steps=2 format=2]

[ext_resource path="res://bin/cell.gdnlib" type="GDNativeLibrary" id=1]

[resource]
resource_name = "cell"
class_name = "Cell"
library = ExtResource( 1 )
```

```
[gd_resource type="NativeScript" load_steps=2 format=2]

[ext_resource path="res://bin/cell.gdnlib" type="GDNativeLibrary" id=1]

[resource]
resource_name = "cell"
class_name = "Grid"
library = ExtResource( 1 )
```

```
[gd_resource type="NativeScript" load_steps=2 format=2]

[ext_resource path="res://bin/cell.gdnlib" type="GDNativeLibrary" id=1]

[resource]
resource_name = "cell"
class_name = "Model"
library = ExtResource( 1 )

```

Here is cell.gdnlib:
```
[general]

singleton=false
load_once=true
symbol_prefix="godot_"
reloadable=true

[entry]

X11.64="res://bin/x11/libgdexample.so"
Windows.64="res://bin/win64/cell.dll"
OSX.64="res://bin/osx/libgdexample.dylib"

[dependencies]

X11.64=[  ]
Windows.64=[  ]
OSX.64=[  ]
```

I'm puzzled by what could be leading to this unreliable behavior. Am I missing something here, or is this an issue with godot-cpp, or with the engine?

I have found a similar issue dating from 2018 [here](https://godotengine.org/qa/34377/exported-win64-build-cannot-find-gdnative-dll-on-another-pc).

**Comment by Zylann** [comment]
Are the other computers running a 64-bit OS?

**Comment by bruvzg** [comment]
> Maybe it has hidden dependencies

Default `godot-cpp` config use `/MD` flag when compiled with MSVC, this means it depends on Microsoft Visual C++ Redistributable.

**Comment by SnailBones** [comment]
Thanks @bruvzg, switching to the /MT flag solved the problem! I'm closing this issue as I have a solution to my problem. Though, I'm considering opening another issue to make /MT the default. Since Godot doesn't come with an installer that can handle dependencies like the Redistributable, I'm not seeing the use case for /MD. Is there something I'm missing?
