### ISSUE TITLE
get_node missing?

### ISSUE THREAD

**Issue by haekb** [godotengine/godot-cpp#464]
Hey there, 

I've followed along with the documentation and built the bindings and lib with `scons platform=windows generate_bindings=yes bits=32`. (My project requires 32-bit, due to some extra libs, but I've also tried it on 64-bit.) I can connect with godot just fine, and can create things like TextureRects fine. 

However I don't seem to have some of the basic functions like `get_node()`..I can see they're defined in api.json, but not in any other file. 

Am I missing a step? 

Thanks in advance!

**Comment by Silver1063** [comment]
After generating bindings `get_node()` is defined in `godot-cpp/include/gen/Node.hpp`

**Comment by haekb** [comment]
Whoops. Thanks for the info! Not sure how I missed that. 

Cheers
