### ISSUE TITLE
Vector2::ZERO is missing

### ISSUE THREAD

**Issue by EternalColor** [godotengine/godot-cpp#467]
I searched through the whole of godot-cpp repository https://github.com/godotengine/godot-cpp/search?q=ZERO&type=
Vector2::ZERO is missing, currently this forces me to write a Vector2Utility class containing the constant Vector2
`
const Vector2& Vector2Utility::DEFAULT_VECTOR = Vector2();`

Should probably be added, since its available in GDScript

**Comment by Zylann** [comment]
What's wrong with writing `Vector2()` though? It has less characters. You don't need a whole utility class for that 🤔

**Comment by EternalColor** [comment]
Nothing, just thought it would be nice. Maybe if someone is migrating his code from GDScript to C++. But I can see that using Vector2() is just as fast.

**Comment by Zylann** [comment]
The problem is, C++ does not allow to define such constants within the declaration of the class, because the type isn't defined yet.
