### ISSUE TITLE
Windows MinGW undefined reference when link

### ISSUE THREAD

**Issue by sent44** [godotengine/godot-cpp#468]
I don't know if I can ask something unrelate to bug in this place.
Also I almost become insane at this point so I don't want to write long post again so here [How to compile native C++ using MinGW in/target Windows?](https://godotforums.org/discussion/24564/how-to-compile-native-c-using-mingw-in-target-windows)
(except I now use `x86_64-w64-mingw32-gcc` instant of `gcc`)

**Comment by 2shady4u** [comment]
@sent44 
I'm able to compile the bindings using gcc using the latest master branch.

![image](https://user-images.githubusercontent.com/42484461/107149474-0ca3cf80-6959-11eb-8e4c-5d0fff5838d6.png)

could you check if this is still a problem? And if yes, what is the actual error message you get?

**Comment by sent44** [comment]
> is still a problem? And if yes, what is the actual error message you get?

I will try that after I finish test.
Sorry for late reply I just notice this notification.

**Comment by sent44** [comment]
And I forgot again 😂

I reread your comment and found out that you mean compile binding, while my issue is link GDNative scripts to dll files.
Compile binding is already pass (unless there is new bug recently).

**Comment by Faless** [comment]
Closing as fixed in `3.5` via godotengine/godot#62173 .
Please leave a comment if you are still encountering this issue after updating godot-cpp to the latest `3.5` branch so we can reopen it in case.
