### ISSUE TITLE
failing when building both master as 3.2

### ISSUE THREAD

**Issue by jkvargas** [godotengine/godot-cpp#482]
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/core/Variant.o -c -fPIC -std=c++14 -Wwrite-strings -Og -g -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Variant.cpp
src/core/Variant.cpp:8:10: fatal error: Object.hpp: No such file or directory
    8 | #include "Object.hpp"
      |          ^~~~~~~~~~~~
compilation terminated.
scons: *** [src/core/Variant.o] Error 1
scons: building terminated because of errors.

**Comment by Calinou** [comment]
Did you initialize Git submodules by cloning the repository with `--recursive` or running `git submodule init` at the root of the cloned repository?

**Comment by jkvargas** [comment]
yes, tried with both approaches. Still having the same issue. =(

**Comment by Calinou** [comment]
OP has managed to resolve this issue by passing `generate_bindings=yes` to SCons instead of `generate-bindings=yes`.
