### ISSUE TITLE
CMake project broken on systems without "python" interpreter

### ISSUE THREAD

**Issue by o01eg** [godotengine/godot-cpp#491]
I use Devuan Testing without `python2` so I don't have `python` interpreter only `python3`.

I suppose it should use `find_package(PythonInterp)` to detect correct python interpreter and call `${PYTHON_EXECUTABLE}`

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face:

**Comment by samsface** [comment]
pr here https://github.com/godotengine/godot-cpp/pull/514
