### ISSUE TITLE
GDNative C++ bindings build failed with godot 4.0 api.json

### ISSUE THREAD

**Issue by RevolNoom** [godotengine/godot-cpp#494]
**Godot version:** 4.0.dev.custom_build.8d4698db3

**OS/device including version:** Ubuntu 20.04 LTS, Dell Inspiron 3580

[EDITED:]
**Issue description:**
Scons builds unsuccessfully when using godot 4 custom api, and prevents future builds from succeeding.

**Steps to reproduce:**
First, open up a new terminal and copy paste these lines:

    mkdir gdnative_cpp_example
    cd gdnative_cpp_example
    git init
    git submodule add https://github.com/godotengine/godot-cpp
    cd godot-cpp
    git submodule update --init

After that, calling scons:

    scons platform=linux generate_bindings=yes -j4

The bindings are built without any hassle.
Continue on, I generate a custom api by:

    godot --gdnative-generate-json-api api.json 

Put the newly created json file at gdnative_cpp_example/ , and then run:

    scons platform=linux generate_bindings=yes -j4 use_custom_api_file=yes custom_api_file=../api.json

It gives out errors in [custom_api.txt](https://github.com/godotengine/godot/files/5860433/custom_api.txt)
After custom api build fails, calling scons like usual:
    
     scons platform=linux generate_bindings=yes -j4

Does not work anymore, and generate errors in [no_custom_api.txt](https://github.com/godotengine/godot/files/5860436/no_custom_api.txt) instead.

**Minimal reproduction project:**
[gdnative_cpp_example.zip](https://github.com/godotengine/godot/files/5860445/gdnative_cpp_example.zip)

**Comment by 2shady4u** [comment]
@RevolNoom The godot-cpp doesn't currently support Godot 4.0 so do take this into account!

- What branch of godot-cpp are you currently on?
- I have a godot-cpp-ci project running that compiles the bindings on Ubuntu 20.04 perfectly here: https://github.com/2shady4u/godot-cpp-ci/runs/1752196002?check_suite_focus=true 

So it should work :/

**Comment by RevolNoom** [comment]
@2shady4u So, I have tried removing the project folder and try building again. This is what I get:
Firstly, open up a new terminal and copy paste these lines:
        mkdir gdnative_cpp_example
        cd gdnative_cpp_example
        git init
        git submodule add https://github.com/godotengine/godot-cpp
        cd godot-cpp
        git submodule update --init
After that, calling scons:

    scons platform=linux generate_bindings=yes -j4

The bindings are built without any hassle.
Continue on, I tried using a custom godot 4 api.json, and run:

    scons platform=linux generate_bindings=yes -j4 use_custom_api_file=yes custom_api_file=../api.json

It gives out errors in [custom_api.txt](https://github.com/godotengine/godot/files/5860433/custom_api.txt)
After custom api build fails, calling scons like usual:
    
     scons platform=linux generate_bindings=yes -j4

Does not work anymore, and generate errors in [no_custom_api.txt](https://github.com/godotengine/godot/files/5860436/no_custom_api.txt) instead.
