### ISSUE TITLE
Remove CMake support

### ISSUE THREAD

**Issue by vnen** [godotengine/godot-cpp#509]
Not sure how many people follow this but I'm considering removing the support for CMake. Main reason is that it's another buildsystem to maintain, and I can't see a point in keeping more than one buildsystem.

It's possible that Godot starts using Meson and if that happens this repository should do the same move (and ditch SCons).

Publishing this here to hear opinions.

BTW, I can see a potential advantage for people already doing a project with CMake, which makes it easier to integrate this but I'm not sure if that's enough to make it worth it, especially since you don't have to build this library very often.

**Comment by schleinzer** [comment]
Please do **not** drop CMake support :-) !

**Comment by o01eg** [comment]
This library isn't distributed as system-wide library on Linux so other projects have to include it even if they don't have to build it very often.

**Comment by Calinou** [comment]
> This library isn't distributed as system-wide library on Linux so other projects have to include it even if they don't have to build it very often.

We can now offer prebuilt static libraries using GitHub Actions, so you may not have to build it at all.

**Comment by o01eg** [comment]
I also use cmake to do Android cross compilation of the library.

**Comment by vnen** [comment]
> I also use cmake to do Android cross compilation of the library.

Well, you should be able to do the same with SCons (after all Godot does the same). If it doesn't work it should be fixed.

I know this repo haven't got any love in a good while, but I do intend to bring it back into working order, including supporting the common compilation scenarios.

**Comment by vnen** [comment]
> > This library isn't distributed as system-wide library on Linux so other projects have to include it even if they don't have to build it very often.
> 
> We now offer prebuilt static libraries using [GitHub Actions](https://github.com/godotengine/godot-cpp/actions), so you may not have to build it at all. The build is currently broken on Windows + MinGW but it can likely be resolved.

Ideally this should be published as releases as well, at least matching Godot releases (since both are used together). But the libs are also compiler-dependent so people might need to rebuild it anyway.

----

I think integrating calling SCons into whatever buildsystem you have shouldn't be too hard, instead of adding support in this project for the buildsystem you want to use. For now we can keep the CMake file (since it's already there) and I'll try to merge all fixes to it, but I won't work on it myself.

**Comment by samsface** [comment]
Ha I was just about to open a pr to see if we wanted the CMake project to find python and run the bindings generator to avoid that manual step.

I'd like to see the CMake generation stay, I'm one of those that has a small GDNative adapter to a large existing C++ codebase.

**Comment by Mempler** [comment]
I use CMake as my main build system... well rather used, i just switched to meson so if the whole project either stay as cmake or switch to meson, would be fine by me. but if that's gone than rip me.

**Comment by vnen** [comment]
Well, if you people want to support it, fine. As mentioned, I've been merging some fixes to the CMake file, but I can't vouch whether those are good or not, since I'm not familiar with it. I'll rely on the users to review those PRs.
