### ISSUE TITLE
Scons cannot compile .a library bindings for Android Arm-v7 & Arm-64v8 on OS X, library table of contents empty

### ISSUE THREAD

**Issue by abrajam92** [godotengine/godot-cpp#510]
I have tried different ways and I can't compile the bindings with scons, when i generate the bindings for android Arm-v7 or Arm-64v8  with scons I get an .a file but only weights like 6 mb and terminal warnings me that:

`bin/libgodot-cpp.android.debug.armv7.a the table of contents is empty (no object file members in the library define global symbols)`

then when I try to get the shared library i get this error:

`error: godot-cpp.android.debug.armv7: no archive symbol table (run ranlib)`

I had to instead compile with ndk-build and Android.mk files, but I have to report this issue, because would be good to have it done just in Scons without needing to worry about external tools, I mean that is supposed to be the purpose of Scons.

**Comment by vnen** [comment]
Moved to godot-cpp since it's not about the headers but about the C++ bindings.

**Comment by waruqi** [comment]
same issue, because scons use incorrect ranlib for android. we need let scons use ndk/ranlib instead of osx/ranlib.

> warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/
ranlib: archive library: bin/libgodot-cpp.android.release.armv7.a the table of contents is empty
 (no object file members in the library define global symbols)
scons: done building targets.

**Comment by waruqi** [comment]
I created a pr to fix it. see https://github.com/godotengine/godot-cpp/pull/539

**Comment by akien-mga** [comment]
Fixed by #547.
