### ISSUE TITLE
Include a .gdignore

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot-cpp#522]
When godot-cpp is added as a submodule in a Godot project, Godot will wrongly try to import `.obj` compilation files and lock for a very long time because of it.

The solution is usually to add a `.gdignore` to prevent Godot from importing anything in there, but it's not possible for such integration to add that file because the submodule then becomes altered.
It is also inconvenient to put the `.gdignore` in the parent folder because it will also ignore things there that might need to be considered by Godot. In my project this makes my `.gdns` and `.gdnlib` unreachable in the editor.

So I think it would help to have a `.gdignore` already present in `godot-cpp`.

**Comment by aaronfranke** [comment]
An alternative solution is to store the `godot-cpp` submodule/folder outside of the Godot project, like in the current master of the GDNative demo projects. But yes, adding a `.gdignore` is a good idea.

**Comment by Xrayez** [comment]
Kind of similar to godotengine/godot#28343...

**Comment by furrykef** [comment]
I don't mean to be rude, but why is it taking nearly two years to add a single blank file to the repo?

**Comment by Calinou** [comment]
> I don't mean to be rude, but why is it taking nearly two years to add a single blank file to the repo?

Feel free to open a pull request for this 🙂
