### ISSUE TITLE
Some recent changes to godot-cpp are breaking my builds

### ISSUE THREAD

**Issue by filipworkson** [godotengine/godot-cpp#523]
I been trying for the past day or so to fix this but I think it may be an actual change with godot-cpp.  It keeps complaining about `gdnative_api_struct.gen.h`. I always get this issue no matter what I do. The file exists and is there and it can even find it but the builder no longer finds it not sure exactly how or why.

```
gdlibrary.cpp
godot-cpp\include\core\Godot.hpp(7): fatal error C1083: Cannot open include file: 'gdnative_api_struct.gen.h': No such file or directory
scons: *** [src\gdlibrary.obj] Error 2
scons: building terminated because of errors.
```

Building with a much older version of godot-cpp that I had around works fine.

**Comment by filipworkson** [comment]
Hey guys just to follow up . I hard reset my submodule to eafe6d9 and it now builds. Deff the naming changes are breaking my build.  I am assuming my current build scripts which are from the earlier gdnative example are no longer working with the new godot-cpp . I would have to manually change all the names/paths in my current build scripts?

**Comment by Zylann** [comment]
Yes, in every place where you wrote `godot_headers` in an include path, you have to replace it with `godot-headers`, because the repo was renamed and so was the directory of the submodule.

For example in my SConstruct, if I have this:

```py
env.Append(CPPPATH = [
    '.', 
    'godot-cpp/godot_headers/', 
    'godot-cpp/godot_headers/include/'
])
```

Now I have to write this instead:

```py
env.Append(CPPPATH = [
    '.', 
    'godot-cpp/godot-headers/', 
    'godot-cpp/godot-headers/include/'
])
```

I'm not sure why that rename was necessary. If it was `-` vs `_` I'd have preferred `_` for both :p

**Comment by filipworkson** [comment]
Thank you @Zylann . You are welcome to close this because I got the answer and is not something that can be fixed from the repo.  This is solely and issue with those who are using old build scripts but have recently updated their godot-cpp.
