### ISSUE TITLE
sending array from C++ to Godot (using Gdnative)

### ISSUE THREAD

**Issue by nosa999** [godotengine/godot-cpp#545]
I have written some codes in c++ and It produces an array and I want to receive this array in Gdscript. but I receive true and false!!! the function in c++ is in the below image:
![image](https://user-images.githubusercontent.com/40929193/115493904-d1d3e700-a279-11eb-96b1-c97ce1c194ab.png)

and the code I have written in godot is the below:

![image](https://user-images.githubusercontent.com/40929193/115494205-69d1d080-a27a-11eb-8854-2f488c521122.png)

![image](https://user-images.githubusercontent.com/40929193/115494178-5c1c4b00-a27a-11eb-874e-b20bc3d84bec.png)

and the result is:

![image](https://user-images.githubusercontent.com/40929193/115494383-c7feb380-a27a-11eb-815f-c7822da7289f.png)

how I should resolve this issue?

**Comment by 2shady4u** [comment]
@nosa999 C++ Arrays are NOT the exact same as Godot Arrays.
If you want your function to return an Array that is useable in Godot you'll have to do something like this:

```
Godot::Array dllGodot() 
{
   Godot::Array res = Array();
   return res;
}
```

**Comment by nosa999** [comment]
> @nosa999 C++ Arrays are NOT the exact same as Godot Arrays.
> If you want your function to return an Array that is useable in Godot you'll have to do something like this:
> 
> ```
> Godot::Array dllGodot() 
> {
>    Godot::Array res = Array();
>    return res;
> }
> ```

Thank you, I do that like that you said:

![image](https://user-images.githubusercontent.com/40929193/115524419-5c7d0c00-a2a3-11eb-8524-3273a7f898d0.png)

but when I run godot, it can only receive some arrays and suddenly it stopped.

**Comment by 2shady4u** [comment]
What is temp? Where is it defined?

**Comment by nosa999** [comment]
> What is temp? Where is it defined?
> It stopped with an error?

no, it stopped without error.
but I resolved this problem and I receive arrays in godot completely. just I put the below code in the "get_board_data" function instead of "_get_data" function:
temp.push_back(buf[i]);
thank you for your help 👍 🥇

**Comment by 2shady4u** [comment]
@nosa999 could you please close this issue if it is fixed? 😆
