### ISSUE TITLE
register_property with default value is not being set

### ISSUE THREAD

**Issue by AbanoubNassem** [godotengine/godot-cpp#560]
I'm not sure, if this is intended behavior or it's a bug, but when I register a property using`register_property` and define a `default_value`, when I check it on the `_ready()` method the property value is `0` , it only work if I edit the value from the `Godot-Editor` app : 

`register_property<MainCamera, real_t>("speed", &MainCamera::set_speed, &MainCamera::get_speed, 5.1f);`

```
    void MainCamera::_ready() {
// always 0 unless I change it from the editor
        godot::Godot::print(std::to_string(speed).c_str());
    }
```

shouldn't the value on the `_ready()` method be `5.1`?

**Comment by Calinou** [comment]
Isn't this bug on the Godot editor end?

**Comment by AbanoubNassem** [comment]
> Isn't this bug on the Godot editor end?

am not really sure , but I posted it here since if I used `GDScript` the default values works just fine, so I thought maybe the issue is within the binding itself not in the `Editor`, correct me if I'm wrong.

**Comment by AbanoubNassem** [comment]
closed in favor of this issue : https://github.com/godotengine/godot/issues/26237
