### ISSUE TITLE
I get an error when using scons to try and compile this, i think it's because the script tries to use Python 2.7

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot-cpp#572]
Hi

I have mac OSX 10.13.16

I am following the instructions for this repo

I run scons:

```
richs-Air:godot-cpp rich$ scons platform=osx generate_bindings=yes
scons: Reading SConscript files ...
ImportError: No module named pathlib:
  File "/Users/rich/GodotLocal/EEGodot2X_NativeTests/SimpleLibCPPEXAMPLE/SimpleLibrary/godot-cpp/SConstruct", line 430:
    import binding_generator
  File "/Users/rich/GodotLocal/EEGodot2X_NativeTests/SimpleLibCPPEXAMPLE/SimpleLibrary/godot-cpp/binding_generator.py", line 6:
    from pathlib import Path
```

I think it is defaulting to 2.7 as pathlib does not exist on 2.7

I have now installed Python 3.9, with macports, and set it as default, i still have no sucess

Python 2.7 is included in mac os as a os component, perhaps this would be why the error would occur on mac

is there any way i can get this to work?

**Comment by Calinou** [comment]
You need to install SCons using Python 3.9-provided pip to make sure it uses Python 3.

**Comment by RichardEllicott** [comment]
okay thanks i managed to install using macports, python3 and pip
