### ISSUE TITLE
is the folder "godot-headers" supposed to be called "godot_headers"?

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot-cpp#573]
I am trying to build the demo:
https://github.com/godotengine/gdnative-demos/tree/master/cpp/simple

i solved the issue i was having by renaming the folder godot-headers => godot_headers

this cannot be right!?!?!
what is the real name?

i still have nightmare issues:
https://github.com/godotengine/gdnative-demos/issues/50
(likely mac specific)

but this folder name is a typo somewhere

**Comment by Calinou** [comment]
The demo should be updated as the repository was renamed from `godot_headers` to `godot-headers` in 2019.

**Comment by aaronfranke** [comment]
The C demos should be good, I haven't gotten around to the C++ demos yet. What needs to be done is that I (or anyone really) need to update the C++ demos to be in a similar format to the C ones and make sure they work on all platforms.

**Comment by RichardEllicott** [comment]
I have finally got a hello world on c++ after someone helped me with realising this SConstruct file in the demo "simple"

on line 46 i had to rename:
libgodot-cpp.linux.debug.64 => libgodot-cpp.osx.debug.64

similar inside the demo project when opened, it was set up for linux but i had to link the osx 64 bit in the native lib to "res://bin/libsimple.dylib"


so this folder name, and these two things might be common mac os issues.

Also previous to these issues, getting scons itself working:
I found the best route to be homebrew -> python39 and pips39. ..... then pips39 to get scons (i found the default scons to be python 2.7 based and incompatible as people seem to have started calling python 3 specific libraries)

**Comment by aaronfranke** [comment]
Thanks for reporting this. It's now been fixed in the demos. In general all the C++ demos should be good examples now.
