### ISSUE TITLE
Is there a proper way to pass an Image or a PoolByteArray to Godot from memory?

### ISSUE THREAD

**Issue by aleksandrbazhin** [godotengine/godot-cpp#574]
It seems like there is no way to copy an array of bytes at once. PoolByteArray has only methods that allow copying bulk data from other Godot PoolArrays or byte-by-byte. Can be the data copied to PoolByteArray or Image not from GDNative arrays?

There is a repo https://github.com/lukacu/bouncy/tree/master/native with OpenCV bindings, which resorts to C api to allow pointer conversions. Is there a way to make something alike at least without creating Godot bindings in C?
Seems like currently PoolArrays can not be instantiated with underlying godot_pool_arrays (to which you can write some memory chunk), so the only way is to have C GDNative bindings, exposing those arrays from there. Am I missing something?

Even StreamPeerBuffers seem to be able to process only PoolByteArrays. So what is supposed to be done with data acquired from other libraries in their datatypes?

**Comment by aleksandrbazhin** [comment]
If anyone interested, here is the solution:
```
PoolByteArray arr;
arr.resize(buffer_size);
PoolByteArray.Write write = arr.write();
memcpy(destiny_buffer, write.ptr(), buffer_size);
```
I guess, it's good enough, just not cpp enough.

**Comment by Calinou** [comment]
> I guess, it's good enough, just not cpp enough.

What would be a "more C++" way to do it?

**Comment by aleksandrbazhin** [comment]
> Can you describe what would be a "more C++" way to do it?

I am not a pro in C++, I was just surprised, that memcpy() is used widely in C++ code. Being unaware of Godot structure, I also assumed, that it's PoolArrays datastructures could have some complex memory layout.
By more cpp way I thought to have a type cast or constructor from, for example, godot_pull_byte_array (which is private and inline explicit https://github.com/godotengine/godot-cpp/blob/master/include/core/PoolArrays.hpp#L23). Or maybe have a method to copy bytes, that would call that memcpy for me and take away my responsibility - you can set a byte, but cannot set several at once from the API.
