### ISSUE TITLE
"cl" not found as an internal or external command 

### ISSUE THREAD

**Issue by Onganne** [godotengine/godot-cpp#577]
I have seen other issues about this but no clear and direct answer is given, other beginners like me also find this confusing so I hope this can be clarified.

for the godot cpp building, it says such an error about cl not being found.
Some answers suggest something about venv not being connected or something wrong of its PATH. There are two problems to this, one is that I do not know how to connect cl to path in the first place (mines is windows). However, Most important is the problem where I was told venv wasn't needed. Hence I want to ask if there is a solution to this and why the error exists even though I dont use venv, may I have accidentally download venv? Is there a way I can delete it and find it?

Hope I can get beginner friendly replies and yes I knwo this does not relate as much to the Godot part but this is essential to go start it so I truly apologize fir my question, but pls be sincere and thx again c:

**Comment by Calinou** [comment]
If you have Visual Studio 2017 or later installed, make sure to open its dedicated command prompt (something like **Visual Studio x64 Native Tools**) instead of a generic comamnd prompt.

If you don't have Visual Studio installed and use MinGW instead, pass `use_mingw=yes` to the SCons command line.

**Comment by Onganne** [comment]
When you say to pass such command, may you clarify to a beginner like me?
Do you mean to type such command on bash or to change the scons code itself?
Thx again c:

p.s It will also help if its possible to explain the part abt visual studio about "open its dedicated command prompt

I apologize for being such a beginner but thx again!

**Comment by Calinou** [comment]
> p.s It will also help if its possible to explain the part abt visual studio about "open its dedicated command prompt

Open the Start Menu and search for "x64". You should see several Visual Studio command prompt options appear. Pick the **x64 Native Tools** one. Use `cd` to reach the `godot-cpp` folder and build the bindings by calling SCons in that command prompt.

**Comment by Onganne** [comment]
Thx, and to clarify before closing this issue, it will help the cl command problem, yes?
Once again, Thanks!

**Comment by Calinou** [comment]
> I asked this due to this error I got after typing:
scons use_mingw_yes platform=windows generate_bindings=yes

It's `use_mingw=yes`, not `use_mingw_yes`. I made a typo in my comment.

**Comment by Onganne** [comment]
Ah, I see, thats why, its all good though since you are replying to this and I am eternally grateful.
and since that issue has finally been solved, there is the final error I was talking about (before the cl and the typo), and its this one:

Once I typed the code, this was shown, and this is something I am very confused about since it did not really specify an error...meaning I couldnt really search what to do, and this may relate to the cl problem but I am not use..

$  scons use_mingw=yes platform=windows generate_bindings=yes
scons: Reading SConscript files ...

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\Users\User\SimpleLibrary\godot-cpp\SConstruct", line 73, in <module>

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\Users\User\SimpleLibrary\godot-cpp\SConstruct", line 75, in <module>

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\Users\User\SimpleLibrary\godot-cpp\SConstruct", line 182, in <module>

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\Users\User\SimpleLibrary\godot-cpp\SConstruct", line 191, in <module>
src\gen: File exists
src\gen: File exists
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src\core\AABB.o -c -O3 -std=c++14 -Wwrite-strings -I. -Igodot-headers -Iinclude -Iinclude\gen -Iinclude\core src\core\AABB.cpp
scons: *** [src\core\AABB.o] The system cannot find the file specified
scons: building terminated because of errors.

You do not need to mind the visual compiler error, since I was told Visual Compiler was not needed, unless it is related to the error I have please clarify.

I once again thank you for replying to these messages and this may be the final error, but I hope u help other like you help me too, and of course and simple explanation and solution is really helpful and I cannot thank you enough.

I will be waiting once again hopefully for a solution or explanation to this problem, and I will be closing this issue after, thx again c:

**Comment by Calinou** [comment]
Your shell prompt has a `$` symbol, which hints that you're using Git Bash or the WSL instead of a Visual Studio command prompt.

**Comment by Onganne** [comment]
Meaning you wish of me to use a Visual Studio command prompt instead of git bash?
I used git bash due to the godot cpp instructions saying so, may you clarify on a solution?
Thx

**Comment by Calinou** [comment]
> Meaning you wish of me to use a Visual Studio command prompt instead of git bash?

Yes :slightly_smiling_face: 

> I used git bash due to the godot cpp instructions saying so, may you clarify on a solution?

Git Bash will only work if you're using MinGW, not MSVC.

**Comment by Onganne** [comment]
Thx A Lot!
You've been a great help
If I have other questions, it may not relate to this so I will close it with this comment
Thx Again c:
