### ISSUE TITLE
the CMakeLists makes it so godot-cpp's output static lib is placed in the wrong directory

### ISSUE THREAD

**Issue by SeleDreams** [godotengine/godot-cpp#598]
I think godot-cpp has a small issue in its CMakeLists, rather than using CMAKE_CURRENT_SOURCE_DIR to get the directory of the current cmakelists, it uses CMAKE_SOURCE_DIR which gets the path of the top level cmakelists
the result is that instead of building the .a in its own directory, it will create a bin directory on the top level source directory with the .a inside which is unwanted behaviour since it clutters the directory

a fix would be to replace CMAKE_SOURCE_DIR by CMAKE_CURRENT_SOURCE_DIR

**Comment by enetheru** [comment]
This is actually intended behaviour. The goal for the cmake build system is to match scons, as scons puts its binaries in godot-cpp/bin so shall cmake.

A change in this behaviour would require a change in the behaviour of scons aswell.
