### ISSUE TITLE
New Godot 4 GDExtension development discussion, when to merge

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot-cpp#603]
Hi All,

Just copying my post from @vnen's PR #602 so we can have the discussion here without polluting his work:
> while vnen left this as a draft I actually believe we should move to merging this into master sooner rather than later. As the current Godot master no longer works with the old gdnative approach we need to start focusing development on this. Merging this will make it easier for others to submit PRs and help out completing this. It will also open the door to raising issues to discuss further enhancements/short comings and get more people to help out by seeing what needs to be done.
>
> We'll need to create a `3.x` branch from the current master and then merging this into master. Everyone can then review their own PRs and decide to either link it to the `3.x` branch or to modify it for Godot-cpp 4. That also means we're in line again with Godot development branches.
>
> I don't want to pollute this post any further, we should move this discussion into an issue and link it here. I'll set that up in a minute. 
We've had a prelude to this discussion on #scripting on the Godot chat server but I think we only have a subset of our community there so it is worth having the discussion here.

**Comment by paddy-exe** [comment]
@BastiaanOlij Since the GDExtension system was merged, this issue can be closed, can't it?
