### ISSUE TITLE
[GDExtension] getting various objects crashes Godot

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot-cpp#609]
Looks like something broke in the last few days that causes Godot to become unstable when fetching certain object.

The test project in the repo fails on `Example::return_something_const()`, the failure happens when it attempts to obtain the viewport with the `get_viewport()` call. It looks like the object returned is getting released before its time.

**Comment by victorholt** [comment]
> Looks like something broke in the last few days that causes Godot to become unstable when fetching certain object.
> 
> The test project in the repo fails on `Example::return_something_const()`, the failure happens when it attempts to obtain the viewport with the `get_viewport()` call. It looks like the object returned is getting released before its time.

So, I know this is not a solution, and I haven't looked into preventing the crash when using `get_viewport()`, however I did notice that if you place the following:

`get_viewport()->duplicate();`

somewhere in your code (I placed mine in an AppController::_ready() method), the crash is prevented when closing the application. Again, not a solution, but if you're just trying to get past the crash it helps..., also may give some insight into a solution I hope.

**Comment by vnen** [comment]
Is this still a problem? Last time I checked the issue in the test project was fixed.

**Comment by victorholt** [comment]
This may not be relevant, but I did recently (today) create a fresh GDNative project (not GDExtension) and experienced the crash when calling `get_viewport()` and closing the app. The issue happens (for me) only as the application is closing.

**Comment by vnen** [comment]
@victorholt GDNative isn't supported anymore on the Godot master branch.

**Comment by BastiaanOlij** [comment]
@vnen sorry yes, this works fine in Godot master now thanks :)
