### ISSUE TITLE
[GDExtension] Properties are not visible in inspector

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot-cpp#614]
Properties defined on a GD extension class are shown in the help system and work fine, but they are not visible in the property inspector:

![image](https://user-images.githubusercontent.com/1945449/134098139-7ee4f4cd-9ff5-4f61-9e41-b700bb3c7b94.png)

**Comment by BastiaanOlij** [comment]
@reduz you may want to give some feedback on what you think may be causing this as I think this may be a problem on the Godot side.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/53710.
