### ISSUE TITLE
[GDExtension] Can't extend gd extension class

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot-cpp#615]
This wasn't possible before in GD native but I was under the impression that GD extensions would allow this, it's been a long requested feature to extend these classes with GDScript

![image](https://user-images.githubusercontent.com/1945449/134100092-649c02c9-e706-4137-9d34-efb989167ab9.png)

**Comment by ellenhp** [comment]
Wouldn't the node that this script is attached to have to be of the `Example` type? It looks like you're attaching it to a control. I might be misunderstanding though.

**Comment by BastiaanOlij** [comment]
@ellenhp I'm attaching it to the Example node:
![image](https://user-images.githubusercontent.com/1945449/134150802-bb8729cd-97df-467d-a73c-eb701e50822b.png)

I have a feeling this may be caused by the issue Fales mentioned around the class not being recognised correctly. I also have a feeling this may be the exact same reason why the properties don't show in the inspector because the inspector also thinks this is Control (which is the superclass of Example).

**Comment by BastiaanOlij** [comment]
Ok after more investigation it looks like @ellenhp was on the right track afterall.

The moment I assign my script to this node, behind the scenes, it changes my node back to being of type Control:
```
[node name="Example" type="Control" parent="."]
script = ExtResource( "2_6hifa" )
__meta__ = {
"_edit_use_anchors_": false
}
```

And it's pretty consistent in changing it every time I try to change it back...

**Comment by dsnopek** [comment]
This issue is out-dated. It _is_ currently possible to attach a script to a node defined in GDExtension. There is some weirdness around virtual methods, but there's dedicated issues for that, for example: https://github.com/godotengine/godot-cpp/issues/1199 and https://github.com/godotengine/godot-cpp/issues/1022
