### ISSUE TITLE
Putting Transforms into Array leaks memory

### ISSUE THREAD

**Issue by BimDav** [godotengine/godot-cpp#647]
3.3.4 on Windows 10.

[TransformsLeak.zip](https://github.com/godotengine/godot-cpp/files/7454225/TransformsLeak.zip)

In this mini project I have a GDNative script with this simple method:

```
Array transforms;

....

void TransformsLeak::_physics_process(float delta) {
	for (int i = 0; i < 100; i++) {
		transforms[i] = Transform2D::IDENTITY;
	}
}
```

this leaks memory, as can be seen in the project's monitor.

I have not tested everything, but Transform also leaks, while Vector3 and Basis don't.

**Comment by akien-mga** [comment]
Fixed by #666.
