### ISSUE TITLE
Hanging and undefined behavior in register_virtuals when overriding RigidDynamicBody3D's _integrate_forces for GDExtension class

### ISSUE THREAD

**Issue by nwroyer** [godotengine/godot-cpp#651]
I've noticed  this when attempting to override `_integrate_forces` when extending `RigidDynamicBody3D` for a GDExtension. `_physics_process`, `process`, and `_ready` all execute without any issue, but the moment I attempt to uncomment the class's `_integrate_forces`, Godot hangs, displaying the opening splash screen and never actually loading the scene. Use of a debugger and print statements reveals that the overriding `_integrate_forces` isn't even called, and the hang occurs after `_ready` is executed.

Using the debugger reveals that the hang is occurring when `register_virtuals` is called in `RigidDynamicBody3D`, specifically in the following call stack:

- `RigidDynamicBody3D::register_virtuals` 
- `call_with_ptr_args` (expanded from the `BIND_VIRTUAL_METHOD` macro)

Occasionally, this will crash with an abort signal instead of hanging, but I've been unable to nail down what will allow me to reproduce a crash. The hang always occurs when there's no crash, and will do so regardless of the content of `_integrate_forces.`

I suspect the issue is related to #630 since overriding any of the virtual functions that take basic types doesn't produce this behavior, and `_integrate_forces` has a single parameter of type `PhysicsDirectBodyState3D*`.

**Comment by nwroyer** [comment]
After some more investigation, I've observed that occasionally a `SIGABRT` will end up being raised within `Object::get_instance_binding` in the first two lines. When `_integrate_forces` is commented out, the program runs as expected; when it's left in, the error reappears, with no compile-time errors in either case.

```C++
1    void *Object::get_instance_binding(void *p_token, const GDNativeInstanceBindingCallbacks *p_callbacks) {
2      	void *binding = nullptr;
3              _instance_binding_mutex.lock();
...
``` 
The error is being raised in the line labeled 3 above.

Further exploration with GDB indicates that `RigidDynamicBody3D::register_virtuals` is as follows:

```
	template <class T>
	static void register_virtuals() {
		PhysicsBody3D::register_virtuals<T>();
		if constexpr (!std::is_same_v<decltype(&RigidDynamicBody3D::_integrate_forces),decltype(&T::_integrate_forces)>) {
			BIND_VIRTUAL_METHOD(T, _integrate_forces);
		}
	} 
```

Setting a message tracepoint and print statements at the start and end of this function reveals that this function is actually being called twice but not actually finishing, and is being called from `PhysicsBody3D`'s attempt to call the virtual `_integrate_forces`. It seems that this behavior itself might be part of the issue, as it's attempting to register the virtual functions while calling them, it seems.

Within the `BIND_VIRTUAL_METHOD`'s expansion that calls `` is where the error appears to be raised, on the second call.

When debugging with GDB, the following error message is produced from the command line itself is sometimes produced:

`godot.linuxbsd.tools.64: tpp.c:82: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.`

Getting a call stack is proving difficult, however, as usually the program will simply hang as noted in the previous comment, and only occasionally produce the above message and crash outright. This leads me to suspect that something - perhaps the `_instance_binding_mutex` - is in an undefined state.

**Comment by lukas-toenne** [comment]
It seems that one level of pointer indirection is lost when the bound virtual function is called.

Where it goes wrong is in the `gdnative_object_get_instance_binding` function of godot-cpp, called by the `PtrToArg` utility template (full callstack below). This directly interprets the `p_args` as `Object` pointers.
```
static void *gdnative_object_get_instance_binding(GDNativeObjectPtr p_object, void *p_token, const GDNativeInstanceBindingCallbacks *p_callbacks) {
	Object *o = (Object *)p_object;
	return o->get_instance_binding(p_token, p_callbacks);
}
```
`GDVIRTUAL1` macro declares a callback (`GDNativeExtensionClassCallVirtual`) which takes as its 2nd argument an array of void pointers to the actual arguments, which is a `PhysicsDirectBodyState3D*` in this case. So a triple pointer in total, the typed pointer gets wrapped in a void ptr and then stuffed into an array.

Compare this to the PtrToArg of Godot itself which includes the additional pointer level:
```
	struct PtrToArg<m_type> {                                          \
		_FORCE_INLINE_ static m_type convert(const void *p_ptr) {      \
			return *reinterpret_cast<const m_type *>(p_ptr);           \
		}                                                              \
```

So i assume the PtrToArg template needs to be fixed to work along similar lines to core Godot.

callstack:
>  	000001e61ee71a90()	Unknown
 	godot.windows.tools.64.exe!mtx_do_lock(_Mtx_internal_imp_t * mtx, const xtime * target) Line 106	C++
 	godot.windows.tools.64.exe!std::_Mutex_base::lock() Line 51	C++
 	godot.windows.tools.64.exe!Object::get_instance_binding(void * p_token, const GDNativeInstanceBindingCallbacks * p_callbacks) Line 1793	C++
	godot.windows.tools.64.exe!gdnative_object_get_instance_binding(void * p_object, void * p_token, const GDNativeInstanceBindingCallbacks * p_callbacks) Line 833	C++
 	mobility.dll!godot::PtrToArg<godot::PhysicsDirectBodyState3D *>::convert(const void * p_ptr) Line 169	C++
 	mobility.dll!godot::call_with_ptr_args_helper<godot::Chassis,godot::PhysicsDirectBodyState3D *,0>(godot::Chassis * p_instance, void(godot::Chassis::*)(godot::PhysicsDirectBodyState3D *) p_method, void * const * p_args, IndexSequence<0> __formal) Line 152	C++
 	mobility.dll!godot::call_with_ptr_args<godot::Chassis,godot::PhysicsDirectBodyState3D *>(godot::Chassis * p_instance, void(godot::Chassis::*)(godot::PhysicsDirectBodyState3D *) p_method, void * const * p_args, void * __formal) Line 173	C++
 	mobility.dll!godot::RigidDynamicBody3D::register_virtuals::__l6::<lambda>(void * p_instance, void * const * p_args, void * p_ret) Line 128	C++
 	mobility.dll!void <lambda>(void *, void * const *, void *)::<lambda_invoker_cdecl>(void * p_instance, void * const * p_args, void * p_ret) Line 128	C++
 	godot.windows.tools.64.exe!RigidDynamicBody3D::_gdvirtual__integrate_forces_call(PhysicsDirectBodyState3D * arg1) Line 231	C++
 	godot.windows.tools.64.exe!RigidDynamicBody3D::_body_state_changed(PhysicsDirectBodyState3D * p_state) Line 522	C++
 	godot.windows.tools.64.exe!RigidDynamicBody3D::_body_state_changed_callback(void * p_instance, PhysicsDirectBodyState3D * p_state) Line 504	C++
 	godot.windows.tools.64.exe!GodotBody3D::call_queries() Line 776	C++
 	godot.windows.tools.64.exe!GodotSpace3D::call_queries() Line 1152	C++
 	godot.windows.tools.64.exe!GodotPhysicsServer3D::flush_queries() Line 1654	C++
 	godot.windows.tools.64.exe!PhysicsServer3DWrapMT::flush_queries() Line 91	C++
 	godot.windows.tools.64.exe!Main::iteration() Line 2654	C++
 	godot.windows.tools.64.exe!OS_Windows::run() Line 667	C++
 	godot.windows.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 163	C++
 	godot.windows.tools.64.exe!_main() Line 185	C++
 	godot.windows.tools.64.exe!main(int argc, char * * argv) Line 199	C++
 	[Inline Frame] godot.windows.tools.64.exe!invoke_main() Line 78	C++
 	godot.windows.tools.64.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!00007ff8bbcf7034()	Unknown
 	ntdll.dll!00007ff8bd65d0d1()	Unknown
