### ISSUE TITLE
Connecting and emitting signals from GDExtension doesn't work

### ISSUE THREAD

**Issue by valentinAlkan** [godotengine/godot-cpp#657]
Trying to connect or emit a signal from GDExtensions doesn't work. Connecting and emitting via GDScripts extending GDExtension classes does work.

For example, main node (GDExtension class Main.cpp) has signal game_ready

```gdscript
extends Main
signal game_ready

func _ready():
	emit("game_ready")
```

A gdextension class extended with GDScript can connect to this signal and the signal can be emitted and received just fine. This even works if the slot is a function defined in cpp so long as the function has been bound in _bind_methods();

```gdscript
extends GDExtensionBaseClass

func _ready():
	var main = $"/root/Main"
	main.connect("game_ready", Callable(self, "_on_game_ready"))
```

However, trying to do the same thing in pure cpp doesn't work.

Main.h
```cpp
#pragma once
#ifdef WIN32
#include <windows.h>
#endif

#include "tools.h"
#include "GPS.h"
#include <godot_cpp/core/binder_common.hpp>
#include <godot_cpp/classes/global_constants.hpp>

using namespace godot;
using namespace std;

class Main : public Node {
	GDCLASS(Main, Node);

protected:
	static void _bind_methods(){
        ADD_SIGNAL(MethodInfo("game_ready")));
    };

public:	
    virtual void _ready() override{
        UtilityFunctions::print("Game Ready!");
        //emit game ready
        emit_signal("game_ready");
};
    virtual void _enter_tree() override {};
private:
};
```

GDExtensionBaseClass.h
```cpp
#pragma once
#ifdef WIN32
#include <windows.h>
#endif

using namespace godot;
using namespace std;

class GDExtensionBaseClass: public Node2D {
	GDCLASS(GDExtensionBaseClass, Node2D);

protected:	
    static void _bind_methods(){
        ClassDB::bind_method(D_METHOD("_on_game_ready"), &GDExtensionBaseClass::_on_game_ready);
    };

public:	
    virtual void _process(double dt) override;
    virtual void _ready() override {
         //assume main is a valid pointer to the Main node. I have other code that makes the reference valid but that is out of the scope
         // of the issue since I know it is a valid reference.
         main->connect("game_ready", Callable(this, "game_ready"));
    }
    void _on_game_ready();
};
```

This code compiles, but the game produces the following error at run time:

```
USER ERROR: In Object of type 'Window': Attempt to connect nonexistent signal 'game_ready' to callable 'GameWorld(GameWorldGD.gd)::_on_game_ready'.
   at: connect (core/object/object.cpp:1328) - Condition "!signal_is_valid" is true. Returning: ERR_INVALID_PARAMETER
```

I'm adapting this code to try to illustrate the error - it may not be 100% reproduceable based on what I have written above. I'm using macros for signal names, which I tried to remove for this example. So if there's typos, that likely isn't the issue. However, the gist of it is that something about signals inside GDExtensions is broken - whether its declaring them, or connecting them, I haven't figured out yet. Emitting from GDExtensions seems to be ok. Will do some more testing and update if I find anything.

**Comment by BastiaanOlij** [comment]
@valentinAlkan can you try if this issue persists if you build Godot with: https://github.com/godotengine/godot/pull/55282
That bug can cause a mismatch in classdb data making things inaccessible. 
That said you don't have any constructor in your sample code, which makes it less likely this is the problem (unless you omitted that for clarity).

Signals are definitely still working for me in the test project.

**Comment by valentinAlkan** [comment]
@BastiaanOlij I'll try it with a constructor, I don't usually add them unless I need to do something different. Since I often pass parameters to my objects at build time, I usually just use an init() function as a constructor. 

If we're required to explicitly declare a constructor for certain functionality to work, I think that's worth mentioning in the docs and example, since normal c++ rules dont require that, and I dont' think GDNative was like that - though maybe it was.

**Comment by valentinAlkan** [comment]
Adding constructors doesn't fix it. I've noticed it only on a few nodes, most nodes allow connecting and emitting signals from GDExtensions. Will try 55282 fix when I can get the engine to compile cleanly.

**Comment by BastiaanOlij** [comment]
Well it is more that when you have a constructor and do certain things in it, it breaks, but if you don't have a constructor it's unlikely this is the problem.

Is this a typo btw? `main->connect("game_ready", Callable(this, "game_ready"));`
Should be `main->connect("game_ready", Callable(this, "_on_game_ready"));`
You are reacting to the signal "game_ready" by calling "_on_game_ready".

**Comment by valentinAlkan** [comment]
> Is this a typo btw? main->connect("game_ready", Callable(this, "game_ready"));
Should be main->connect("game_ready", Callable(this, "_on_game_ready"));
You are reacting to the signal "game_ready" by calling "_on_game_ready".

Probably, I use macros for this type of stuff and replaced them to illustrate my problem.

However it looks like the issue was that my pointer was pointing to the root instead of the my main node.

**Comment by BastiaanOlij** [comment]
Glad you found it :)
