### ISSUE TITLE
_instance_bindings is initialized multiple times

### ISSUE THREAD

**Issue by saki7** [godotengine/godot-cpp#679]
Forked from #668

### Error summary

```
ERROR: Condition "_instance_bindings != nullptr" is true.
   at: Object::set_instance_binding (core\object\object.cpp:1781)
```

### Steps to reproduce

Scene tree:
- TestContainer
  - Node

Extension code:

```cpp
class TestContainer : public Node
{
    GDCLASS(TestContainer, Node);

public:
    static void _bind_methods() {}

    void _ready() override
    {
        WARN_PRINT("TestContainer::_ready()");
        get_node<Node>("Node"); // <-----------------------------------
    }
};
```

Note that I picked `get_node` solely as an example here; all other functions which access the instance binding object may trigger the same issue.

### My findings
When `Object::get_instance_binding` is called before `Object::set_instance_binding`, godot core fallbacks to newly created instance ([object.cpp#L1799-L1815](https://github.com/godotengine/godot/blob/4ea309b405f09fb9c1425c688ea3eaeb24cce477/core/object/object.cpp#L1799-L1815)). I am suspecting that fallback instance is reason for multiple initialization in `Wrapped::_postinitialize`. If that's the case, we must fix the godot core first, then fix godot-cpp accordingly.

**Comment by saki7** [comment]
I've rebuilt godot and godot-cpp on current master (godotengine/godot@9b3972ad48393559f772151646304e28f938a6fa) but the `_instance_bindings` assertion errors are still flooding my console.

I have also confirmed that the workaround I posted on https://github.com/godotengine/godot-cpp/pull/668#issuecomment-1005669289 is working, however I'm not sure if it is the correct fix (see the caveat mentioned by vnen, https://github.com/godotengine/godot-cpp/pull/668#issuecomment-1006688536)

I really want to propose an appropriate fix for this, but I'm still not sure where the multiple initialization of `_instance_bindings` comes from.

**Comment by Kev** [comment]
Unless I massively screwed up, I'm running with godot 5ca09b322c0dea3f71de3239c2da2a72d987f67d and godot-cpp 9aa129caabb9f26bd1b1822ba823c3d10a7f8fa5 and I'm still seeing a lot of 'Condition "_instance_bindings != nullptr" is true.' - these commits shouldn't be showing this any more should they?

**Comment by Kev** [comment]
Very sorry - the library rename meant I was running my old dylib, not the new one. Ignore the report - no sign of this now.
