### ISSUE TITLE
[3.4.2] Make TextureRect::get_texture() return the correct texture derived type

### ISSUE THREAD

**Issue by Lecrapouille** [godotengine/godot-cpp#698]
The  `TextureRect::get_texture()` will always return `Ref<Texture>` while in the editor TextureRect can use derived textures (ie ImageTexture). We cannot downcasting directly from the gd script, right ? So crash is possible.

cpp/src/gen/TextureRect.cpp:

```
void TextureRect::___init_method_bindings() {
	___mb.mb_get_texture = godot::api->godot_method_bind_get_method("TextureRect", "get_texture");
...

Ref<Texture> TextureRect::get_texture() const {
	return Ref<Texture>::__internal_constructor(___godot_icall_Object(___mb.mb_get_texture, (const Object *) this));
}
```

My c++ code:
```
void Foo:bar(godot::Ref<godot::ImageTexture> texture) // ideally const& ?
{ ... }

void Foo::_register_methods()
{
   godot::register_method("bar", &Foo::bar);
   ...
}
```

Scene graph:
```
+ Control
   + TextureRect (configured as ImageTexture)
   + Foo
```

gd script:
```
var rec = get_node("TextureRect")
var foo = get_node("Foo")

foo.bar(rec.get_texture())     # will crash silently (no dynamic_cast check possible ?)
```

Cannot have something similar `TextureRect::get_texture<ImageTexture>()` in gdscript ?

**Comment by Zylann** [comment]
What is the problem exactly?
Godot crashes when you send a texture from GDScript to your extension method `bar`?
What are you doing inside `bar`? Did you find that `texture` is `null`? (it's recommended to check before calling anything on pointers)

**Comment by Lecrapouille** [comment]
@Zylann thank for your reply, I did not notice your comment. I'll try your method (not before 1 week).

`Godot crashes when you send a texture from GDScript to your method bar?`
yes, when I want to use it.

`What are you doing inside bar?`
Call methods like create_from_image().

`Did you find that texture is null? (it's recommended to check before calling anything on pointers).`
I did not. I'll try it.

My C++ native code in my 1st comment shows: `void Foo:bar(godot::Ref<godot::ImageTexture> texture)` is expecting an ImageTexture (to use create_from_image()) while the gdscript `TextureRect` can only return the base class `Texture`. To be more precise the Foo comes from an external C++ API in where I can access to a texture from a raw C pointer. So I need to to fill the raw texture into Godot texture. My original code Foo returns it's Ref<godot::ImageTexture> to TextureRect and it worked perfectly while not optimized:

```
// For gdscript
godot::Ref<godot::ImageTexture> Foo::get_texture() { return m_texture; }
godot::register_method("get_texture", &Foo::texture);

// Asynchronous internal callback
void Foo::on_paint(const void* buffer, int width, int height)
{
    // Copy CEF image buffer to Godot PoolVector
    m_data.resize(width * height * 4 * sizeof(char));
    godot::PoolByteArray::Write w = m_data.write();
    memcpy(&w[0], buffer, width * height * 4 * sizeof(char));

    // Copy Godot PoolVector to Godot texture.
    m_image->create_from_data(width, height, false, godot::Image::FORMAT_RGBA8, m_data);
    m_texture->create_from_image(m_image, godot::Texture::FLAG_VIDEO_SURFACE);
}
```

Member variables for Foo:
```
    godot::Ref<godot::ImageTexture> m_texture;
    godot::Ref<godot::Image> m_image;
    godot::PoolByteArray m_data;
```

gdscript (working):
```
var rec = get_node("TextureRect")
var foo = get_node("Foo")

rec.texture = foo.get_texture()
```

Now I just wanted TextureRect pass its textures to Foo instead of using member variable m_texture.

I'm starting with Godot I probably do not know how, from the editor, to configurate TextureRect to use an ImageTexture therefore I'm not sure if TextureRect has an already created texture ready to use (or if from the editor I have to force explicitly to create one) and not sure of the REAL type of texture returned by `get_texture()`. In the case it returns a real Texture, the crash is normal because of downcasted instance with missing methods (create_from_image). If Godot would offer dynamic cast it would probably return null.

`Ref<ImageTexture> image_texture = texture;` I saw the C++ code Ref will just increment / decrement the number of reference like std::shared and create / delete the instance. But if it does not destroy Texture and create ImageTexture I'll have the same crash. I have to read more the C++ code.

My current not working code, simplified:
```
godot::Ref<godot::ImageTexture> Foo::get_texture() { return m_texture; }
godot::register_method("get_texture", &Foo::texture);

int Foo::init(godot::Ref<godot::ImageTexture> const& texture)
{
   m_texture = texture;
}
godot::register_method("init", &Foo::init);

void Foo::on_paint(const void* buffer, int width, int height)
{
same code
}
```

gdscript (not working):
```
var rec = get_node("TextureRect")
var foo = get_node("Foo")

foo.init(rec.get_texture())
// crash on on_paint
```

The idea was to have:
```
var rec = get_node("TextureRect")
var foo1 = get_node("Foo1")
var foo2 = get_node("Foo2")

foo1.init(rec.get_texture(), viewport1)
foo2.init(rec.get_texture(), viewport2)
// foo1 and foo2 drawing on the same texture on two different regions
```

**Comment by Zylann** [comment]
> // Asynchronous internal callback

As in, another thread? Careful with that, there might be issues with Godot not handling well some function calls from different threads and resource creation (even though it should work in theory).

```
var rec = get_node("TextureRect")

foo1.init(rec.get_texture(), viewport1)
```

Well, once again. The problem is the same: at this point, you must have assigned an `ImageTexture` to `TextureRect` before calling `get_texture`. Otherwise it will give you null and will crash. The return value being the base type does not matter. 

> I'm starting with Godot I probably do not know how, from the editor, to configurate TextureRect to use an ImageTexture therefore I'm not sure if TextureRect has an already created texture ready to use (or if from the editor I have to force explicitly to create one) 

`TextureRect` does not have any texture assigned by default, you have to assign one. And since pixels are loaded from code, I'd suggest you create it from code as well (why do that in two separate locations anyways? Doing things in the scene editor implies they are done by a designer, but if you always need a new `ImageTexture` either way that's a bit pointless to require the designer to assign one everytime). 
If you really want to, assign it in editor by clicking on the property and doing `New ImageTexture`.

> and not sure of the REAL type of texture returned by get_texture()

As I said, you can determine that. When you do `Ref<TypeA> a = other_ref; // other_ref is Ref<TypeB>`, Godot attempts to do a cast automatically. And if it fails, `a` will be `null`. Otherwise it will contain the type you want. If you assign an `ImageTexture` to `TextureRect` it should not fail.

**Comment by Lecrapouille** [comment]
@Zylann thank you ! I'll give a try when I can check it back.
