### ISSUE TITLE
CMake: unsupported option '-fPIC' for target 'x86_64-pc-windows-msys' when compiling on Windows with clang

### ISSUE THREAD

**Issue by API-Beast** [godotengine/godot-cpp#733]
```
$ make -j4
[  0%] Bindings
[  1%] Building CXX object godot-cpp/CMakeFiles/godot-cpp.dir/src/core/AABB.cpp.obj
[  1%] Building CXX object godot-cpp/CMakeFiles/godot-cpp.dir/src/core/Basis.cpp.obj
[  1%] Building CXX object godot-cpp/CMakeFiles/godot-cpp.dir/src/core/Array.cpp.obj
[  1%] Building CXX object godot-cpp/CMakeFiles/godot-cpp.dir/src/core/CameraMatrix.cpp.obj
clang++: error: unsupported option '-fPIC' for target 'x86_64-pc-windows-msys'
clang++: error: unsupported option '-fPIC' for target 'x86_64-pc-windows-msys'
```

Adding the -fPIC flag to the compiler options is outdated, the [POSITION_INDEPENDENT_CODE](https://cmake.org/cmake/help/latest/prop_tgt/POSITION_INDEPENDENT_CODE.html) property should be set to ON instead.

On 3.x branch, using clang 11.0.0.4

**Comment by API-Beast** [comment]
It might have been caused by me accidentally installing the msys version of clang instead of the regular one. It's of course still a bug but maybe supporting msys isn't that high on the priority list.

**Comment by dsnopek** [comment]
In current `master`, we appear to already be using `POSITION_INDEPENDENT_CODE`: https://github.com/godotengine/godot-cpp/blob/master/CMakeLists.txt#L240

I'm assuming this was fixed some time between when this issue was made and now. So, closing!
