### ISSUE TITLE
godot-cpp master doesn't work with Godot 4.0 alpha 7

### ISSUE THREAD

**Issue by 2shady4u** [godotengine/godot-cpp#744]
Users of my GDExtension project are reporting errors:
https://github.com/2shady4u/godot-sqlite/issues/71#issuecomment-1112661365

```
ERROR: Condition "!method" is true. Returning: 0
   at: get_builtin_method_hash (core/variant/variant_call.cpp:1172)
ERROR: Error getting method , hash mismatch.
   at: gdnative_variant_get_ptr_builtin_method (core/extension/gdnative_interface.cpp:475)
```

Most likely the `godot-headers` just need to be updated to alpha 7 as well to fix this issue.

**Comment by akien-mga** [comment]
Synced with 0b05044.
