### ISSUE TITLE
Missing header files on 3.x

### ISSUE THREAD

**Issue by Crakmaks** [godotengine/godot-cpp#745]
I hope it is just an easy to fix problem on my end but I'm not able to include basic header like physics_body.h into my GDNative project. I checked both this repository and the godot-headers and physics_body.h is not included. So it would make sense, that I can't included them in my project if they aren't in the libraries, I guess. I followed the GDNative C++ example to create this project and used the 3.x versions. Are these files really missing or am I missing a different step to get them into my project? Thank you!

**Comment by Calinou** [comment]
These headers are automatically generated by godot-cpp's buildsystem using the information supplied by a JSON file generated by Godot (which is included in the repository).

Did you compile godot-cpp with the `generate_headers=yes` SCons option?

**Comment by Crakmaks** [comment]
It was a spelling error on my end, I'm really sorry!

**Comment by Calinou** [comment]
> It was a spelling error on my end, I'm really sorry!

What kind of spelling error, to be specific? If this is about `generate_bindings=yes`, we should consider instructing SCons to warn about unknown options passed to it.
