### ISSUE TITLE
Ref<T> pointer cast is unsafe

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot-cpp#76]
Ref<T> is implemented by doing many casts to `(T*)`, which means any object that don't match `T` will end up being referenced, produce corruption and crash the engine with no way to check and very little information given to the developper. This can happen either in C++, or even when used in GDScript, where you wouldn't expect such things.

In Godot, the same implementation does a cast too, because downcasting is needed, for example if you use `Resource::duplicate()`. However it's a safer cast because `Object::cast_to` is used instead, which produces an empty reference if the cast fails, which can be checked for null.
In GDNative we only have Object::is_class, but it requires a String argument, which is less efficient because we would need to convert class names from UTF-8 everytime a Ref<T> is constructed from a variant (everytime Godot calls a GDNative function, basically). But maybe it's our only option...

In general, I think GDNative safety should be worked on, like checking arguments and object casting in order to *at least* have a way to null-check references and objects.

**Comment by BastiaanOlij** [comment]
Seeing @karroffel fixed a bunch of things around this in nativescript 1.1 and @Zylann mentioned he won't be looking back into this for awhile, closing this as fixed. Marc feel free to open up a new issue when you get back into GDNative and are still having issues on the latest version. Thanks!

**Comment by SnailBones** [comment]
I'm still experiencing this issue! Comments in the code also suggest this still hasn't been resolved.

**Comment by Zylann** [comment]
One way to check if the problem still exists is to try something like this:
```cpp
Ref<ArrayMesh> test(SurfaceTool::_new());
// Then call functions on it
```

The expected behavior is at least for `test` to be `null`, like it behaves in the engine. A better step would be to make it not compile, but the fact it's not done in the engine hints that it might not be possible.
