### ISSUE TITLE
Android compilation fails on master due to Github Actions virtual environment updates

### ISSUE THREAD

**Issue by 2shady4u** [godotengine/godot-cpp#765]
Seems like something broke in the compilation of the `master`-branch when Github updated their virtual environment.
(Other branches, like the 3.4 one, are also broken)

![image](https://user-images.githubusercontent.com/42484461/173588417-ed48d835-7470-45b5-a947-2cadfee280ed.png)

The updated virtual environment probably has some different version/dependencies that aren't compatible anymore with whatever is set in this project's SConstruct.

**Working version of virtual env:** 
https://github.com/godotengine/godot-cpp/actions/runs/2447445726

https://github.com/actions/virtual-environments/blob/ubuntu18/20220529.1/images/linux/Ubuntu1804-Readme.md

**Non-working version of virtual env:**
https://github.com/2shady4u/godot-cpp/actions/runs/2495452077

https://github.com/actions/virtual-environments/blob/ubuntu18/20220605.1/images/linux/Ubuntu1804-Readme.md

Maybe it's some other issue, but the version of the virtual environment seems to me to be the most likely culprit.

**Comment by 2shady4u** [comment]
> This should be fixed in `3.x` via: #691 , for the `master` branch you can try: #762 .

😃 That's great news!
Any change this might be back-ported to 3.4?

**Comment by Faless** [comment]
I think we can backport just the android fix to call `llvm-ar` without the target path name for `3.4`.
