### ISSUE TITLE
GDExtension Crash When Launching Game At Alpha 10

### ISSUE THREAD

**Issue by hakuhan** [godotengine/godot-cpp#769]
ERROR: Index p_type_b = 1122114304 is out of bounds (Variant::VARIANT_MAX = 35).
   at: Variant::get_ptr_operator_evaluator (core\variant\variant_op.cpp:919)
ERROR: Condition "!method" is true. Returning: 0
   at: Variant::get_builtin_method_hash (core\variant\variant_call.cpp:1172)
ERROR: Error getting method , hash mismatch.
   at: gdnative_variant_get_ptr_builtin_method (core\extension\gdnative_interface.cpp:485)

**Comment by Calinou** [comment]
@hakuhan Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by hakuhan** [comment]
> @hakuhan Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
> 
> Could you reproduce this issue on 4.0.alpha9?

No. Alpha 9 is OK.

**Comment by hakuhan** [comment]
I finally fond the reason. lib name changed: 
![image](https://user-images.githubusercontent.com/18411187/174237880-3371ca80-c35e-42af-a2fb-5326f6460369.png)
