### ISSUE TITLE
Paths referenced by "Load As Placeholder" don't get updated when moving files in FileSystem tab.

### ISSUE THREAD

**Issue by API-Beast** [godotengine/godot-cpp#777]
Version: Godot 3.5 RC 5

If you mark an node as placeholder using the context menu, save the scene, close it and then move the referenced node using the FileSystem tab the reference is not updated and thus the scene file can't be opened in the editor anymore and the tscn file needs to be manually fixed using a text editor.

**Comment by API-Beast** [comment]
oops wrong repo

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/37818.
