### ISSUE TITLE
Callable::bind has no implementation

### ISSUE THREAD

**Issue by bearman92** [godotengine/godot-cpp#802]
Callable::bind method has no implementation

```
lld-link: error: undefined symbol: public: class godot::Callable __cdecl godot::Callable::bind<class godot::StringName>(class godot::StringName const &) const
```

**Comment by Zylann** [comment]
Confirmed here. I can't port some code using it.

**Comment by rburing** [comment]
> It isn't possible to call callables either.

Since https://github.com/godotengine/godot/pull/66177 it is possible to call a `Callable`, using the `callv` method and passing the arguments as a single array, e.g. constructed using `Array::make`.

**Comment by Daylily-Zeleen** [comment]
Confirmed here. I can't use Callable::bind() to connect a signal
