### ISSUE TITLE
Maybe remove the licenses from the example code

### ISSUE THREAD

**Issue by derammo** [godotengine/godot-cpp#813]
This is just a suggestion.

Not sure what the intent is, but maybe the example code that everyone uses as the basis for their plugin should not have the standard Godot license header?   I doubt using "register_types.cpp" as a basis for our own work is a "substantial" portion being copied, but I am not a lawyer.

So maybe it would be good to just not have any copyright on those files so people don't end up in the awkward situation of having to rewrite the same file essentially just to have it not be part of the Godot engine.   Again, I am not a lawyer, so maybe this isn't required, but it was awkward for me when I started working on a plugin.

**Comment by you-win** [comment]
> So maybe it would be good to just not have any copyright on those files so people don't end up in the awkward situation of having to rewrite the same file essentially just to have it not be part of the Godot engine.

Your code is not part of the Godot Engine, even if you use substantial portions of the example code. Unless you contribute your code back to the Godot Engine, the only requirement is to include Godot's license in your project (this does not give the Godot Engine ownership over your code!).

What is required is that the license be included in all copies or substantial portions of code associated with the Godot Engine (e.g. the example).

**Comment by derammo** [comment]
There is a misunderstanding here.  I am saying precisely because starting with the sample code does not mean people sign up to their software becoming part of Godot, the example files should NOT be stamped with that attribution.   They are:  https://github.com/godotengine/godot-cpp/blob/master/test/src/register_types.cpp

Everyone who starts an Extension project will copy that demo project and modify it.  I just noticed it doesn't make much sense how those files are stamped.   It's not a big deal either way, just not convenient for "customers."

**Comment by akien-mga** [comment]
This project is meant to be some sort of unit/integration test, it's not meant to be the demo project that users should base their projects off. Since GDExtension is still heavily under development we haven't made such "starter kit" but there should likely be one eventually, and indeed it should be as permissively licensed as possible (e.g. public domain / Unlicense).

That being said, I'm not against removing the license headers from the test project(s) too, it's just added automatically by our style scripts but an exception can be made for this folder.

**Comment by derammo** [comment]
I have only found Extensions online that were created by copying the test program.  That's the reality, because there is no template and no instructions.

**Comment by derammo** [comment]
Ahahahha, ok now we know why the stamp is there :).

For context:  What I am trying to do to help is create a reference implementation of a ScriptLanguageExtension here:
https://github.com/derammo/derammo_testlang

In the end, it will demonstrate how to use all the required API correctly and create some threads and make those threads debuggable.   By struggling through that process, I will find all the things that don't work in Godot yet and fix them or file issues where I can't fix it myself.

I only found two projects using ScriptLanguageExtension and they both appear to have failed (for now.)  Which makes sense, because there are pieces missing that I believe make it impossible to use.  But once I get to the end of the example/reference implementation actually working, then it won't be :)

**Comment by akien-mga** [comment]
See #817.

**Comment by paddy-exe** [comment]
@akien-mga This is very much appreciated! I created my demo project (https://github.com/paddy-exe/GDExtensionSummator) based on the godot-cpp and the summator example from the custom module docs exactly for the showcasing purpose
