### ISSUE TITLE
Merged PR #816 force to use "using namespace godot;" in namespace where GDCLASS macro is used

### ISSUE THREAD

**Issue by ComradeNixco** [godotengine/godot-cpp#821]
One might not want to "polute" the namespace by having to use `using namespace godot;` in a header file. Fix would be to use godot::* for each class used in the macro that comes from the `godot` namespace

**Comment by ComradeNixco** [comment]
The PR where the "breaking" change occurs: #816

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by Faless** [comment]
Fixed via #823
