### ISSUE TITLE
`NOTIFICATION_`* constants are missing

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-cpp#827]
It seems that the `NOTIFICATION_`* constants are missing from godot-cpp / GDExtension. When I try to use constants such as `NOTIFICATION_PAUSED`, it doesn't work, but this is works in the engine's C++ code and in GDScript.

**Comment by Zylann** [comment]
The parsing of `constants` is missing for classes in `bindings_generator.py`.
