### ISSUE TITLE
demo test project won't load in Godot 4.0 Beta 1

### ISSUE THREAD

**Issue by frankhale** [godotengine/godot-cpp#845]
With recent commits to `godot_cpp` the demo test project will no longer load in Godot 4 builds

![image](https://user-images.githubusercontent.com/190154/190652652-d5c2fc68-62bd-4691-b9ef-0dbf7fd43da7.png)

**Comment by frankhale** [comment]
The demo works in Godot 4.0 Beta 1 if I roll `godot_cpp` back to commit 420c86eb90f13194b26e8a28d8173d22bd9d064f

**Comment by akien-mga** [comment]
Which godot-cpp commit did you build when it failed? Did you try https://github.com/godotengine/godot-cpp/commit/be7ed4c775243b85e7ac082c1556b28026b7e5ae ?

**Comment by frankhale** [comment]
Oh I was pulling down the latest commit 3276688c825308199e8be6f6e7f9e90822d50643 and building against that. Thank you for the information. I will try the commit you mentioned. THANK YOU!

**Comment by frankhale** [comment]
Yes, I can confirm that commit be7ed4c775243b85e7ac082c1556b28026b7e5ae works fine. Thank you so much for the quick response.
