### ISSUE TITLE
Exposing a method to change the Node icon

### ISSUE THREAD

**Issue by paddy-exe** [godotengine/godot-cpp#863]
There's doesn't seem to be an exposed method or another possibility to change the icon of a node written with GDExtension.

**Comment by alessandrofama** [comment]
As a workaround you can call 
```
get_editor_interface().get_base_control().get_theme().set_icon("YourGDExtensionClass, "EditorIcons", your_icon)
```
in an EditorPlugin and the icon will appear in all places.

**Comment by paddy-exe** [comment]
> As a workaround you can call 
> 
> ```
> 
> get_editor_interface().get_base_control().get_theme().set_icon("YourGDExtensionClass", "EditorIcons", your_icon)
> 
> ```
> 
> in an EditorPlugin and the icon will appear in all places.

Good to know! I will try that, thanks

**Comment by aaronfranke** [comment]
@alessandrofama Unfortunately, this work-around does not seem to scale the icons. They are tiny on my 4K screen where I have the system and Godot running with 200% scaling.

**Comment by bitbrain** [comment]
@aaronfranke it does scale on my 4K but only after reloading the addon (disabling and re-enabling it in the settings) However, when I restart Godot the icon is scuffed again...
