### ISSUE TITLE
godot::Directory get_current_dir() not returning "res://" as part of its path for Android build

### ISSUE THREAD

**Issue by sanjodev** [godotengine/godot-cpp#878]
I recently switched from v3.3.2 to v3.5 and I noticed the get_current_dir() method of the godot::Directory class isn't returning "res://" as part of its path for for Android build. 

```
godot::Ref<godot::Directory> dir = godot::Directory::_new();
            
if (dir->open("res://_Plugins") != godot::Error::OK)
    return;

dir->list_dir_begin();

godot::String file = dir->get_next();

while (file != "")
{
    if (!dir->current_is_dir())
    {
         godot::String dirPath= dir->get_current_dir().get_basename();

         // other code here
    }

    file = dir->get_next();
}
```

I expect "res://" to be part of dirPath

Windows and Linux build work fine.
Android build seems to strip "res://"

**Comment by Calinou** [comment]
Can you try this in GDScript to make sure this issue is specific to GDNative/godot-cpp?

**Comment by MGilleronFJ** [comment]
This is not a GodotCpp issue https://github.com/godotengine/godot/issues/64074

**Comment by Calinou** [comment]
Closing per @MGilleronFJ's comment.
