### ISSUE TITLE
Godot 4 - Android - GdExtension - Missing shared library in export

### ISSUE THREAD

**Issue by NicoZobernig** [godotengine/godot-cpp#905]
I have been trying to get the new gdextension framework to run in an android export, unfortunately to no avail... It seems like the shared library for android doesn't get packaged properly with the apk, resulting in an error while trying to open it (see error below).
I tested from an Ubuntu 20 platform, building onto arm64 android devices running Android 11 and 12.

### LINUX
The test/demo example within this repo builds successfully for **linux**, both in the editor and as an export. 

### ANDROID
Building `godot-cpp` as well as the `test` lib works without issues when setting `platform=android` and also setting `ANDROID_NDK_ROOT` to the correct path.

The shared lib gets generated inside the `bin` folder as `libgdexample.android.template_debug.arm64.so`.

I extended the `.gdextension` file from the demo like so (might already be a source of error, could not find any info on this...)
```
[configuration]

entry_symbol = "example_library_init"

[libraries]

macos.debug = "res://bin/libgdexample.macos.template_debug.framework"
macos.release = "res://bin/libgdexample.macos.template_release.framework"
windows.debug.x86_32 = "res://bin/libgdexample.windows.template_debug.x86_32.dll"
windows.release.x86_32 = "res://bin/libgdexample.windows.template_release.x86_32.dll"
windows.debug.x86_64 = "res://bin/libgdexample.windows.template_debug.x86_64.dll"
windows.release.x86_64 = "res://bin/libgdexample.windows.template_release.x86_64.dll"
linux.debug.x86_64 = "res://bin/libgdexample.linux.template_debug.x86_64.so"
linux.release.x86_64 = "res://bin/libgdexample.linux.template_release.x86_64.so"
linux.debug.arm64 = "res://bin/libgdexample.linux.template_debug.arm64.so"
linux.release.arm64 = "res://bin/libgdexample.linux.template_release.arm64.so"
linux.debug.rv64 = "res://bin/libgdexample.linux.template_debug.rv64.so"
linux.release.rv64 = "res://bin/libgdexample.linux.template_release.rv64.so"
android.debug.arm64-v8a = "res://bin/libgdexample.android.template_debug.arm64.so"
```

which seems to work as intended, since android then knows about the library path I set. (Both `android.debug.arm64` and `android.debug.arm64-v8a` seem to work and lead to the same error). Setting `arm64-v8a` does lead to the `.so` being present inside the `android/build` folder though, where I cannot find it there when using `arm64` only. 

When trying to *export* for **android** however, the demo project doesn't work, failing to load the lib:
```
org...engine.gdextensiontestproject  E  USER ERROR: Can't open dynamic library: bin/libgdexample.android.template_debug.arm64.so, error: dlopen failed: library "bin/libgdexample.android.template_debug.arm64.so" not found.
org...engine.gdextensiontestproject  E     at: open_dynamic_library (platform/android/os_android.cpp:166)
org...engine.gdextensiontestproject  E  USER ERROR: GDExtension dynamic library not found: bin/libgdexample.android.template_debug.arm64.so
org...engine.gdextensiontestproject  E     at: open_library (core/extension/native_extension.cpp:270)
org...engine.gdextensiontestproject  E  USER ERROR: Failed loading resource: res://example.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
org...engine.gdextensiontestproject  E     at: _load (core/io/resource_loader.cpp:228)
org...engine.gdextensiontestproject  E  USER ERROR: Error loading extension: res://example.gdextension
org...engine.gdextensiontestproject  E     at: load_extensions (core/extension/native_extension_manager.cpp:120)
```
and then not finding the Example class as a result
```
org...engine.gdextensiontestproject  E  USER SCRIPT ERROR: Parse Error: Identifier "Example" not declared in the current scope.
org...engine.gdextensiontestproject  E     at: GDScript::reload (res://main.gd:17)
org...engine.gdextensiontestproject  E  USER SCRIPT ERROR: Parse Error: Identifier "Example" not declared in the current scope.
org...engine.gdextensiontestproject  E     at: GDScript::reload (res://main.gd:18)
org...engine.gdextensiontestproject  E  USER SCRIPT ERROR: Parse Error: "Example" was not found in the current scope.
org...engine.gdextensiontestproject  E     at: GDScript::reload (res://main.gd:28)
org...engine.gdextensiontestproject  E  USER SCRIPT ERROR: Parse Error: Identifier "ExampleRef" not declared in the current scope.
org...engine.gdextensiontestproject  E     at: GDScript::reload (res://main.gd:35)
org...engine.gdextensiontestproject  E  USER ERROR: Cannot get class 'Example'.
org...engine.gdextensiontestproject  E     at: instantiate (core/object/class_db.cpp:325)
org...engine.gdextensiontestproject  E  USER WARNING: Node Example of type Example cannot be created. A placeholder will be created instead.
org...engine.gdextensiontestproject  E     at: instantiate (scene/resources/packed_scene.cpp:201)
org...engine.gdextensiontestproject  E  USER ERROR: Cannot get class 'ExampleMin'.
org...engine.gdextensiontestproject  E     at: instantiate (core/object/class_db.cpp:325)
org...engine.gdextensiontestproject  E  USER WARNING: Node ExampleMin of type ExampleMin cannot be created. A placeholder will be created instead.
org...engine.gdextensiontestproject  E     at: instantiate (scene/resources/packed_scene.cpp:201)
org...engine.gdextensiontestproject  E  USER WARNING: Icon not supported by this display server.
org...engine.gdextensiontestproject  E     at: set_icon (servers/display_server.cpp:515)
```

If I then look inside the build folder `android/build` I can find both the `.gdextension` file (in the `assets` folder), as well as the `.so` inside `libs/debug/arm64-v8a`. 

How can I resolve this issue?
Thanks

**Comment by Faless** [comment]
This:

```
android.debug.arm64-v8a = "res://bin/libgdexample.android.template_debug.arm64.so"
```

Should likely be:
```
android.debug.arm64 = "res://bin/libgdexample.android.template_debug.arm64.so"
```

**Comment by Faless** [comment]
> Setting `arm64-v8a` does lead to the `.so` being present inside the `android/build` folder though, where I cannot find it there when using `arm64` only.

I see, it might a be an issue with the exported then. Can you post the log of the export process?

**Comment by bruvzg** [comment]
Seems like there are two issues:
- Android exporter is looking for `get_abis()` tags (e.g. `arm64-v8a`) instead of proper arch.
- Libs are exported to the `libs/abi/name.so`, but Android `open_dynamic_library` is using path from `.gdextension` as is.

**Comment by bruvzg** [comment]
GDNative was removing file path from the loaded library name, GDExtension do not:

https://github.com/godotengine/godot/blob/92aedd506375356d3323d8896a02d6c9bc11661e/modules/gdnative/gdnative.cpp#L317-L321

Probably it should be done in the `open_dynamic_library`, since other platforms do the library search in there.
