### ISSUE TITLE
GDextension classes unregistered in the wrong order

### ISSUE THREAD

**Issue by Skwint** [godotengine/godot-cpp#914]
godot-cpp 4.0.dev (merge #908)
Windows 11 and Windows 7

All extension classes are unregistered automatically on exit, which results in  `ERROR: Attempt to unregister class 'Fruit' while other extension classes inherit from it.` at: `core\extension\native_extension.cpp:252` because classes are unregistered before other classes inhereting from them are unregistered.

The version of ClassDB exposed in godot_cpp does not include the unregister_class function so we can't fix this by hand in our extensions.

Weirdly, this seems to give a polite error message on Windows 11, and crash completely on Windows 7, so this bug may be the same as #62152 and #66475 raised against Godot itself except now with a useful error message.

**Comment by Zylann** [comment]
I think that's a Godot bug, not a GodotCpp bug, perhaps it should be reported in the Godot repository. Godot should be able to figure out the right order.

**Comment by Skwint** [comment]
Perhaps, yes. I don't really know the workings well enough to make that call. I know it is a bug that cannot be encountered by people who aren't using godot-cpp ...

**Comment by Zylann** [comment]
> I know it is a bug that cannot be encountered by people who aren't using godot-cpp ...

How do you know that? It very much sounds like a bug that can be encountered by other language bindings. It's directly something Godot is doing, not something GodotCpp does.

**Comment by Zylann** [comment]
Perhaps something like this would work
```cpp
void ClassDB::deinitialize(GDNativeInitializationLevel p_level) {
	// Wrapper of ClassInfo including a flag for unregistration. We only need this here.
	struct ClassItem {
		const ClassInfo *info;
		bool unregistered = false;
	};

	struct L {
		static void unregister_class(const ClassInfo &cl) {
			internal::gdn_interface->classdb_unregister_extension_class(internal::library, cl.name);

			for (auto method : cl.method_map) {
				memdelete(method.second);
			}
		}

		static void unregister_class_and_children(ClassItem &ci, std::vector<ClassItem> &classes) {
			if (ci.unregistered) {
				return;
			}
			// Find if there are child classes, and unregister them first
			for (ClassItem &other : classes) {
				if (other.info->parent_ptr == ci.info) {
					unregister_class_and_children(other, classes);
				}
			}
			unregister_class(*ci.info);
			ci.unregistered = true;
		}
	};

	// Gather all classes of the current level.
	std::vector<ClassItem> level_classes;
	for (const std::pair<std::string, ClassInfo> pair : classes) {
		const ClassInfo &cl = pair.second;
		if (cl.level != p_level) {
			continue;
		}
		level_classes.push_back(ClassItem{ &cl, false });
	}

	for (ClassItem &ci : level_classes) {
		L::unregister_class_and_children(ci, level_classes);
	}
}
```

**Comment by Skwint** [comment]
> How did you find that?
The error message is printed in one function only, and that function is not called by any code in godot (at least, not that I can see? I might have missed some function pointer magic).
I can't make the debugger work with godot today (scons always wants to fight me) and I'm not going to try to play guess-the-call-stack.

Your solution looks like it ought to work unless there's some way a child can hide by not being the same level as its parent. I honestly have no idea if that's a thing or not.

**Comment by Zylann** [comment]
A child class should not be registered before its parent, and a child class should not be registered in a level lower than its parent. These cases should probably be checked for during registration.
