### ISSUE TITLE
GDCLASS doesn't use godot namespace on StringName

### ISSUE THREAD

**Issue by Skwint** [godotengine/godot-cpp#918]
The GDCLASS macro uses StringName instead of godot::StringName, which forces header files of exported classes to use the `using` keyword. It didn't use to force that and it probably shouldn't.

I'm using pull request #896.

**Comment by saviilsy** [comment]
Same problem here, on top of this the console fills up like this and the engine crashes :
> ...
> ERROR: Condition "!method" is true. Returning: 0
>    at: get_builtin_method_hash (core/variant/variant_call.cpp:1235)
> ERROR: Condition "!method" is true. Returning: 0
>    at: get_builtin_method_hash (core/variant/variant_call.cpp:1235)
> ERROR: Condition "!method" is true. Returning: 0
>    at: get_builtin_method_hash (core/variant/variant_call.cpp:1235)
> ERROR: Condition "!method" is true. Returning: 0
>    at: get_builtin_method_hash (core/variant/variant_call.cpp:1235)
> ERROR: Condition "!method" is true. Returning: 0
>    at: get_builtin_method_hash (core/variant/variant_call.cpp:1235)
> ERROR: Condition "!method" is true. Returning: 0
>    at: get_builtin_method_hash (core/variant/variant_call.cpp:1235)
> ...

This does not happen with #908, one can test it with https://github.com/saviilsy/HowToStartMakingGDExtensionsForGodot

**Comment by Skwint** [comment]
Yep, I also have those crashes, but weirdly only in the editor - if I build the latest godot for template_debug it runs just fine including loading my extension.

**Comment by Skwint** [comment]
For Saviilsy and those that find this page in a web search of the error messages, the cure for *that* problem seems to be to do a complete `scons --clean` of godot and rebuild it. The *workaround* for *this* problem is `using godot::StringName`.

**Comment by akien-mga** [comment]
CC @touilleMan

**Comment by touilleMan** [comment]
I guess the example in Godot-cpp should also be modified to remove the `using godot` (given it's the primary way of testing changes are running fine)

**Comment by saviilsy** [comment]
> For Saviilsy and those that find this page in a web search of the error messages, the cure for _that_ problem seems to be to do a complete `scons --clean` of godot and rebuild it. The _workaround_ for _this_ problem is `using godot::StringName`.

I did clean from CMake side and it did not fix it. I reverted to beta 4 commit and keep it in that until next release. Easier than using latest anyway until API is stable😅

**Comment by touilleMan** [comment]
I've created #920 that fix this issue ;-)
