### ISSUE TITLE
Properties bound by `_set()`, `_get()`, `_get_property_list()` will lost `name`,`hint`,`hint_string`.

### ISSUE THREAD

**Issue by Daylily-Zeleen** [godotengine/godot-cpp#921]
The demo Example Node's properties:
![image](https://user-images.githubusercontent.com/61624558/201407780-3f38a026-d7ce-4fdb-a61c-1bac4c8cc457.png)

I found that in GDExtension side, the `PropertyInfo` in `_get_property_list()` will be append successfully, all infomation are exist.
But in godot core, the `StringName` which reinterpret_cast from `GDNativeStringNamePtr` will be a empty string, and `String` which reinterpret_cast from `GDNativeStringPtr` usually throw a "read access violation" exception in `String`'s constructor( it is not occur certainly, but almost certainly).
![image](https://user-images.githubusercontent.com/61624558/201412159-28e03d98-e3ad-414d-9f63-1339ed826fe0.png)

I'm pretty sure this is a bug introduced recently, I have been using `_set()`, `_get()`, `_get_property_list()` in GDExtension for some time.

**Comment by groud** [comment]
Hmm, I've just stumbled upon this bug, but no crash on my side. It made it impossible for me to save some custom resources defined in a GDExtension with `ResourceSaver.save`.

**Comment by Daylily-Zeleen** [comment]
> Hmm, I've just stumbled upon this bug, but no crash on my side. It made it impossible for me to save some custom resources defined in a GDExtension with `ResourceSaver.save`.

Crash may be an another bug, but I can't spcify what is the reson. Usually happen with `String` and `StringName`.

**Comment by Daylily-Zeleen** [comment]
Yes, this issue is happen after pulling [#896](https://github.com/godotengine/godot-cpp/pull/896). But I have not ablility to find out the reason from this diff. I hope someone can repair it.

**Comment by touilleMan** [comment]
@Daylily-Zeleen can you test #940 and see if it fix your issue ?
