### ISSUE TITLE
`video_stream.h` virtual functions are not exposed in generated header files

### ISSUE THREAD

**Issue by justofisker** [godotengine/godot-cpp#943]
I am attempting to create a VPX implementation for Godot 4. When I generate header files for `video_stream.h` all of the virtual functions do not exist. I need to override them for my implementation of this class.

**Comment by akien-mga** [comment]
See @KidRigger's work in https://github.com/godotengine/godot/pull/62737 :)

This is pending review/merge and then my understanding is that KidRigger already has a working WebM plugin implementation.

**Comment by kidrigger** [comment]
WebM can be found at https://github.com/kidrigger/godot-video-reference
