### ISSUE TITLE
Test project builds but dynamic library can't be loaded (error 126)

### ISSUE THREAD

**Issue by TheSecondReal0** [godotengine/godot-cpp#944]
I'm able to build the test project fine but when I try to open the project in Godot I get error 126 and running with `--verbose` gives me this:
```
ERROR: Can't open dynamic XlRi:b rClaerayr: iCn:g/ Gpordiomtary int/eGrofdaocte
Projects/gdextXeRn:s iRoenm-otveesdt iinngt/ebrifna/cleiNbagtdievxea mmpolbei.lwei
nXdRo:w sR.etmeomvpelda tien_tdeerbfuagc.exO8p6e_n6X4R.
dll, error: Error 126: The specified module could not be found.
.
   at: (platform/windows/os_windows.cpp:256)
ERROR: GDExtension dynamic library not found: C:/Godot/Godot Projects/gdextension-testing/bin/libgdexample.windows.template_debug.x86_64.dll
   at: open_library (core/extension/native_extension.cpp:295)
ERROR: Failed loading resource: res://example.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:214)
ERROR: Error loading extension: res://example.gdextension
   at: (core/extension/native_extension_manager.cpp:120)
Godot Engine v4.0.beta6.official.7f8ecffa5 - https://godotengine.org
```
Running without `--verbose` doesn't show the error that gets scrambled but still gives error 126.

I'm on windows 10 using mingw 12.2.0

**Comment by pondc1** [comment]
Does the test project actually function? I.E. can you see the `Example` node in the hierarchy with no errors?

I ran into a similar issue before where everything seemed like it was building correctly but the dynamic library wasn't loading. My issue ended up being that I didn't have CMake installed. The way I solved it was installing the c++ package via the Visual Studio Installer.

**Comment by TheSecondReal0** [comment]
I can see the nodes in the hierarchy but they have class not found errors. I've made sure I have CMake installed and it's still giving error 126.

**Comment by TheSecondReal0** [comment]
Fixed after installing the Desktop Development with C++ workload with VS installer and running sfc /scannow
