### ISSUE TITLE
ClassDB::bind_method not properly casting Variant to Node

### ISSUE THREAD

**Issue by WildRackoon** [godotengine/godot-cpp#966]
I reproduced the error in this forum issue : [https://godotforums.org/d/31691-how-to-bind-a-function-with-a-node-as-parameter](https://godotforums.org/d/31691-how-to-bind-a-function-with-a-node-as-parameter)

Methods using a `Node` as parameter works in Godot internal modules, but not when using `godot-cpp` in a GDExtension.

```
void MyClass::my_func(godot::Node *p_node) {
  // ...
} 

void MyClass::_bind_methods()
{
  godot::ClassDB::bind_method(godot::D_METHOD("my_func", "node"), &MyClass::my_func);
}
```

Outputs following Templates errors:
```
godot-cpp\include\godot_cpp/core/binder_common.hpp(89): error C2440: 'return': cannot convert from 'const godot::Variant' to 'T'
        with
        [
            T=godot::Node *
        ]
```

I can't figure how internal modules obtain this casting behaviour, any ideas ?

**Comment by DmitriySalnikov** [comment]
Probably this PR can help https://github.com/godotengine/godot-cpp/pull/950

**Comment by zhehangd** [comment]
The latest version does not seem to have this problem anymore.
