### ISSUE TITLE
Test project builds on Windows 11 64-bit but doesn't work in Godot

### ISSUE THREAD

**Issue by aliendisco** [godotengine/godot-cpp#976]
I tried compiling beta 8 and 9 versions of Godot-cpp and demo project and they compile ok. But extension doesn't work in Godot b8/b9.

I also tried building GDExtensionSummator and got same results.
Here's also link to GDExtensionSummator issue I posted: [Link](https://github.com/paddy-exe/GDExtensionSummator/issues/29)

Everything work OK on linux x64.

The error:
```
  Can't open dynamic library: C:/Users/Bostjan/work/git/godot-cpp/test/demo/bin/libgdexample.windows.template_debug.x86_64.dll, error: Error 126: The specified module could not be found.
  .
  core/extension/gdextension.cpp:400 - GDExtension dynamic library not found: C:/Users/Bostjan/work/git/godot-cpp/test/demo/bin/libgdexample.windows.template_debug.x86_64.dll
  Failed loading resource: res://example.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  Transient parent has another exclusive child.
  Cannot get class 'Example'.
  Cannot get class 'ExampleMin'.
  In Object of type 'MissingNode': Attempt to connect nonexistent signal 'custom_signal' to callable 'Node(main.gd)::_on_Example_custom_signal'.
```

**Comment by fatduckling** [comment]
I'm getting a similar issue on Linux:
```
  Can't open dynamic library: /home/saleem/GodotProjects/Multiplayer1/src/build/libGodotMultiplayerLibrary.so. Error: /home/saleem/GodotProjects/Multiplayer1/src/build/libGodotMultiplayerLibrary.so: undefined symbol: _ZN5godot4Node8_processEd
  core/extension/gdextension.cpp:400 - GDExtension dynamic library not found: /home/saleem/GodotProjects/Multiplayer1/src/build/libGodotMultiplayerLibrary.so
  Failed loading resource: res://example.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
```

**Comment by fatduckling** [comment]
I got it to work after doing a make clean.

I ran directly from terminal: `cmake .. && make`  instead of doing through Visual studio.

**Comment by epchain** [comment]
I have the same issue with Godot 4.0beta10. I do clean and successful builds of godot-cpp and godot-cpp/test (commit `3da6db4...`) according to instructions from [this page](https://godotengine.org/article/introducing-gd-extensions) (a bit outdated) with the same error messages in Godot. Both official Godot 4.0beta10 build and custom build of commit `d0398f6...` behave similarly. I build on Windows 10 x64 with MSYS2 Mingw-w64 v12.2.0.
Before building I dumped `extension_api.json` and `gdextension_interface.h` from Godot as suggested in godot-cpp/gdextension/README.md, updated them in godot-cpp/gdextension and immediately see difference: godot-cpp's `extension_api.json` doesn't have entries for `FramebufferCacheRD` and `UniformSetCacheRD` which are present in Godot. This means godot-cpp `3da6db4...` looks like not so synced with Godot `d0398f6...`
If it helps, I attached my build options and logs:
[godot-cpp_build-flags.zip](https://github.com/godotengine/godot-cpp/files/10335323/godot-cpp_build-flags.zip)
[godot-cpp_build-log.zip](https://github.com/godotengine/godot-cpp/files/10335324/godot-cpp_build-log.zip)
[godot-cpp-test_build-log.zip](https://github.com/godotengine/godot-cpp/files/10335325/godot-cpp-test_build-log.zip)

**Comment by AmberOrange** [comment]
Having the same issue here too, Windows 10 x64 with MSYS2 Mingw-w64

**Comment by feiyunw** [comment]
You can use [Dependencies](https://github.com/lucasg/Dependencies/releases) to check your DLL dependcies.
Copy them (libgcc_s_seh-1.dll, libstdc++-6.dll and libwinpthread-1.dll) from MinGW installation to the same directory where libgdexample.windows.*.dll resides (i.e. godot-cpp\test\demo\bin).

Better to link the DLL statically, without any external MinGW DLL dependency.

**Comment by epchain** [comment]
Thanks, @feiyunw!
I've walked through the whole building process from scratch on Godot v.4.0.stable / Windows 10 x64 / MSYS2 Mingw-w64 v12.2.0 and can confirm that missing dependency libraries are cause of this issue. Default build of `godot-cpp/test` depends on dynamic libraries `libgcc_s_seh-1.dll`, `libstdc++-6.dll` and `libwinpthread-1.dll`. Copying them to `godot-cpp/test/demo/bin` solves the issue. You can get them from `<MSYS2-installation>\mingw64\bin`. As for linking those libraries statically, you can add the following line to `godot-cpp/test/SConstruct` file:
```
...
else:
    # This line
    env["LINKFLAGS"] = "-static-libgcc -static-libstdc++ -static -pthread"
    library = env.SharedLibrary(
...
```
However, the error message Godot gives out in this situation is still misleading. It could be something like "failed to load" instead of "couldn't find" a library.

**Comment by feiyunw** [comment]
> As for linking those libraries statically, you can add the following line to `godot-cpp/test/SConstruct` file:
You may be interested in PR #1082

**Comment by doonv** [comment]
I was also having this issue, and @epchain 's solution solved it for me! Thank you so much!

**Comment by NatGazer** [comment]
Devs, I love your work but, if possible **I would like to know why, in 08/2023 with Godot 4.1.1, do I still have this problem**. And by the way, thank you so much @feiyunw and @epchain for giving the solution, I've lost a week just to put gdextension to work because of this issue.
