### ISSUE TITLE
Engine::add_singleton is not exposed

### ISSUE THREAD

**Issue by kiran-kp** [godotengine/godot-cpp#993]
I am attempting to write a custom server using GDExtension and realized `Engine::add_singleton` is not exposed. Would it be possible to add this? My understanding is that modules are currently the only way to write a new server.

**Comment by Daylily-Zeleen** [comment]
In Godot core, there have 2 class which named `Engine`, one is for Godot core self, another one is for GDScript binding. And the  GDExtension's interfaces is generated with the GDScript binding one.
Currently, if you want to create a custom server, you can code it as a custom module.

**Comment by DmitriySalnikov** [comment]
Wait, but `GDScript` and `GDExtension` have `register_singleton`. I've been using it for quite some time.
```cpp
Engine::get_singleton()->register_singleton("name", ptr);
```

It is exposed [here](https://github.com/godotengine/godot/blob/0e4e782ada0bdd4ef19415f82a6373e2d79f7ecc/core/core_bind.cpp#L1561-L1570)

**Comment by Daylily-Zeleen** [comment]
> 

`Engine::add_singleton()` is not equal to `Engine::register_singleton()`.
`add_singleton()` let a object can be auto complement in GDScript, `register_singleton()` should use a String to retrieve the object.

I never use a custom server, I'm not sure `add_singleton()` is required or not, but in tutorial, it use `add_singleton()` and `register_server_type()`.

**Comment by DmitriySalnikov** [comment]
![Godot_v4 0-beta13_win64_tpICkGM30u](https://user-images.githubusercontent.com/7782218/213139569-2e47f239-c693-47b4-a021-0d75d57ab605.gif)

🤷‍♂️
https://github.com/DmitriySalnikov/godot_debug_draw_3d/blob/b9a7055251f5dc5efea59de585ff18f348fba7e5/src/register_types.cpp#L37-L38
