### ISSUE TITLE
`Object::cast_to` works incorrectly for GDExtension custom classes

### ISSUE THREAD

**Issue by VanessB** [godotengine/godot-cpp#995]
Copy of [this issue#71332](https://github.com/godotengine/godot/issues/71332#issue-1532399391) from main repository, as it is related to GDExtension.

### Issue description

`Object::cast_to` does not work properly in case of custom GDExtension classes. For example, a `nullptr` is NOT returned in some cases where an object can not be casted to the desired type:

(Let `TestNode` inherit from `Node2D`, `some_node_2d` be of type `Node2D`)
```cpp
godot::Node::cast_to<TestNode>(some_node_2d) != nullptr;  // true, must be false, as Node2D can not be casted to TestNode.
```

From my experience, it seems that `cast_to` works with custom classes as if they are their base classes, as (in this example) I can cast all the classes inherited from `Node2D` to `TestNode`, and can not cast any other type (see steps to reproduce and reproduction project).

The GDScript, although, works fine with casting of custom classes, see example. C++ code for casting in-engine types also seems to work fine.

Steps to reproduce and example project with GDExtension source code can be seen [here (issue#71332)](https://github.com/godotengine/godot/issues/71332#issue-1532399391)

**Comment by dsnopek** [comment]
I was also caught by this in trying to port SG Physics 2D. Here's a PR that fixes it in my testing:

https://github.com/godotengine/godot-cpp/pull/1037

**Comment by akien-mga** [comment]
Reopening as #1037 was reverted.

**Comment by zhehangd** [comment]
I saw the very helpful background information provided by @dsnopek  in #1042 , and did my own investigation tonight and would like to add some more.

Basically we have no control over which godot-cpp wrapper gets bound to an engine object. It all depends on who comes first that references this object in the extension (who calls `object_get_instance_binding` or `object_set_instance` and provides `___binding_callbacks` first).

Here are three examples:
1. Our extension `memnew` a `godot::PackedScene`. The wrapper will forever be this `godot::PackedScene`.
https://github.com/godotengine/godot-cpp/blob/f5133c08a529d027e3232d593b0f6c3ca45a0545/src/classes/wrapped.cpp#L46

2. A `PackedScene` is initially passed to a function as a parameter in form of a `Variant` --  the wrapper will forever be a `godot::Object`.
https://github.com/godotengine/godot-cpp/blob/f5133c08a529d027e3232d593b0f6c3ca45a0545/src/variant/variant.cpp#L414

* A `PackedScene` is initially passed to a function as a parameter in form of `godot::PackedScene*` or `Ref<godot::PackedScene>` --  the wrapper will forever be a `godot::PackedScene`.

(Note that these two places are buggy in the `master` branch so I am linking to my pending PRs.

https://github.com/godotengine/godot-cpp/blob/891bcca9ec027d16cbdabf9dece080dd5afc0b46/include/godot_cpp/core/method_ptrcall.hpp#L172

https://github.com/godotengine/godot-cpp/blob/517db6686a11130293b1ddf644a5b5f472228807/include/godot_cpp/classes/ref.hpp#L245

I see two options here:

Option 1: give `object_get_instance_binding` the ability to find the true type of an object and the binding_callbacks of the corresponding godot-cpp wrapper class. 

Option 2: Implement a magical `engine.is_base_of(T::class(), engine.get_real_class(obj))` function, and `Object::cast_to` returns nullptr if that function returns false.

Not sure if they are easy to do as I have little knowledge of the Godot class system

**Comment by dsnopek** [comment]
> Option 1: give `object_get_instance_binding` the ability to find the true type of an object and the binding_callbacks of the corresponding godot-cpp wrapper class. Then we can do `dynamic_cast<T*>(reinterpret_cast<Object*>(api_obj_ptr)) in Object::cast_to`

I have an almost finished implementation of this option. I'll make a PR (or really a pair of PRs since there will be Godot engine changes and godot-cpp) when it's ready!

**Comment by dsnopek** [comment]
Here's the pair of PR's I promised:

- https://github.com/godotengine/godot-cpp/pull/1050
- https://github.com/godotengine/godot/pull/73511

They're still a work-in-progress, as noted on the first PR, there's a couple things I'd still like to do.

**Comment by Darker** [comment]
This is why I gave up on godot about 6 months ago, seems it was only reported recently. My workaround was to make use of the godot reflection feature:

```
      if (ShootableObject* shootable = Object::cast_to<ShootableObject>(body))
      {
        if (body->get_class() != "ShootableObject")
        {
          return;
        }

        if(shootable->is_inside_tree())
          shootable->receiveDamage(props.damage);
      }
```

**Comment by RonYanDaik** [comment]
I have `CustomClassA(inherits Node)` and `CostumClassB(inherits Node)` in c++. In GDScript `GDCustomClassC(inherits CustomClassB)`

in c++ `cast_to<Custom_ClassA>(pointer_To_gd_custom_class_C)` retrurns a Custom_ClassA reference
